### ISSUE TITLE
Cesky psana uzivatelska prirucka

### ISSUE THREAD

**Issue by fvacek** [Quick-Event/quickbox#138]
Na Wiki projektu by mela vzniknout Uzivatelska prirucka, obsahovat by mela nekolik kapitol:
- Instalace
- Pripojeni periferii (tiskarny, SI reader)
- Zalozeni zavodu
- Losovani
- Zavod
- Zpracovani vysledku
- Trouble shooting

**Comment by frantisekpasek** [comment]
Existuje již nějaká příručka, kde je popsáno co a jak funguje?
Ušetřilo by to práci jak uživatelům, tak programátorům. 
Nemuselo by to být nic super podrobného, stačilo by vždy pár řádek o daném tématu.

**Comment by fvacek** [comment]
jasne, proto jsem vytvoril tuto issue :) Mame Wiki stranky, kazdy tam muze prispet, jinak dokumentace nevznikne

**Comment by frantisekpasek** [comment]
OK.
Myslím si, že by příručku měl psát programátor té které části (což jsi ve většině případů asi ty). Jedině on ví jak to funguje. Zatím mi spíš ale přijde, že se očekává, že by to měli psát uživatelé.

**Comment by fvacek** [comment]
To se neocekava, to je jiste, ja na tohle fakt nemam cas. Pisu to po vecerech pro zabavu a muj cas, ktery muzu tydne venovat konickum je ze shora omezeny :)

**Comment by paukert** [comment]
Česká uživatelská příručka (https://github.com/fvacek/quickbox/wiki/QuickEvent-Users-Guide-CZ) všechny výše zmíněné kapitoly již obsahuje + je tam i něco navíc  :-)

Je aktualizována pro verzi QE 2.3.4

**Comment by paukert** [comment]
Může se asi zavřít :)
