### ISSUE TITLE
Subcategories - for semifinal race / print global startlist for semifinal subcategories

### ISSUE THREAD

**Issue by xkenia** [Quick-Event/quickbox#178]
For semifinal you need subcategories H21A/B/C/D, but you still need to print startlist for H21 - parent category for this.

no, především v QE vůbec nejde mít "imaginární" kategorie, což je nutné pro semifinále MČR, kde losuju startovku např. pro H21A, H21B, H21C a H21D, ale startovky tisknu pro H21.

Tento problem by se dal nyni zjednodusit jako tisk vice kategorii jako jedna kategorie.

Ale pocitam, ze v budoucnu budeme chtit automaticky prenos dat ze semifinale do finale, coz uz bych resil pomoci nejake "nadrazene/grupovaci" kategorie (napr. H21).

**Comment by fvacek** [comment]
I think that I will need tiny explanation on HSH :)

**Comment by VoiToi** [comment]
Ahoj, koukám, že už jste toto založili za mě, děkuji. :-)
Nejkorektnější a podrobný popis je v soutěžním řádu: [http://www.orientacnibeh.cz/dokumenty](url), kapitola MČR na krátké trati. Obdobné vychytávky jsou i u MČR na klasice.

**Comment by fvacek** [comment]
Nepodarilo se mi to najit, ve kterem PDF dokumentu to ma byt?

**Comment by VoiToi** [comment]
Je to hned 2. dokument, jmenuje se Soutěžní řád soutěží sekce OB. :-)
Přesné URL je zde: [http://www.orientacnibeh.cz/upload/dokumenty/sekce-ob/sr-ob16.pdf](url).

Pak ještě konkrétněji pro MČR na krátké trati se jedná o body 2.9 - 2.14 a 2.19 - 2.23.
Pro MČR na klasice jsou tam obdobné body 1.7 - 1.14 a 1.22 - 1.23.

**Comment by fvacek** [comment]
Tak jsem si to precetl a porad nechapu, proc je v semifinale treba tisknout startovku pro H21 a ne 5 startovek pro H21A - H21E?

**Comment by VoiToi** [comment]
Ahoj, protože závodníci nesmí vědět, jaký rozběh poběží a s kým. To má být tajné. :-)

**Comment by fvacek** [comment]
Aha, pak mi to spis nez na vymejsleni virtualnich kategorii vychazi spis na tisk startovky pro vic kategorii najednou (myslim tim treba H21?)

**Comment by VoiToi** [comment]
Ahoj, určitě. Mohlo by být u kategorie nové pole s názvem třeba Skupina pro tisk. Pokud by byla vyplněna a bylo by více kategoriií se stejnou skupinou, pak by se v tisku sloučily a vypadaly by jako jedna kategorie. V oddílové startovce pak stačí jen uvádět skupinu místo normálního náznu kategorie. Bacha na to, že pak ve startovce jsou třeba 4 lidi se stejným časem z různých rozběhů každý interval, ale tisk by se tim neměl snad nijak rozbít. Reálný příklad startovky je zde:
http://sk-praga.cz/zavody/mcrkt2016/dokumenty/startovka_kategorie_semifinale.html

**Comment by fvacek** [comment]
A slo by v hlavicce kategorie uvest misto skupiny pro tisk neco jako:

H21A + H21B + H21C + H21D + H21E

rad bych se vyhnul pridavani novych sloupcu, pokud by se neukaz, ze sloupec **Skupina_pro_tisk** ma univerzalnejsi pouziti nez je jen MCR na KT

**Comment by VoiToi** [comment]
Tohle jsem asi úplně nepochopil. Podle mě toto je fakt užitečné jen pro MČR na krátké trati a na klasice, případně pro světové závody.. Takže minimálně do půli září to asi nikdo nevyužije. Ale název kategorie v hlavičce startovky musí být doslova H16, H18, H20, H21 a totez u zen. To je v souteznim radu. Jiny (treba slozeninovy) nazev ve startovce pouzit nelze, mě by to rozhodčí určitě nedovolil.
Vojta

**Comment by fvacek** [comment]
Jasny, celkem mi pripada uzitecny, mit moznost pridat ke kategorii jeste nejaky label nebo atribut nebo nejakou skupinu. Napada te jeste nejaky jiny pouziti takovyho sloupce, nez jsou startovky MČR na krátké trati a na klasice?

**Comment by VoiToi** [comment]
Napadá mě už jen mistrovství světa, evropy, případně akademické MS. Tam je úplně stejný princip semifinálových rozběhů a finále. Akorát pozor, výsledky už sloučené nejsou (ani na MS, ani na ME, ani na MČR). Výsledky jsou zvlášť pro každý rozběh.

**Comment by lukaskett** [comment]
Ahoj, v jakém stavu tahle issue je?

**Comment by fvacek** [comment]
pokud vim, tak na ni nikdo jeste ani nesahl

**Comment by lukaskett** [comment]
Můžete se na to, prosím, mrknout? Byl by to super krok k vývoji pro uspořádání MČR na klasice nebo krátké trati.

**Comment by fvacek** [comment]
Rad bych to zrekapituloval, nez zacnu neco programovat:
* vse co nam ted chybi je moznost vytisknout souhrnou startovku pro vic kategorii najednou s exaktnim nazvem, ktery definuje soutezni rad.

@VoiToi, @paukert  muzete to prosim promyslet?

**Comment by VoiToi** [comment]
> Rad bych to zrekapituloval, nez zacnu neco programovat:
> 
> * vse co nam ted chybi je moznost vytisknout souhrnou startovku pro vic kategorii najednou s exaktnim nazvem, ktery definuje soutezni rad.
> 
> @VoiToi, @paukert muzete to prosim promyslet?

Ahoj, spíše mít možnost definovat u kategorie název skupiny pro tisk (např. D21 místo D21A, B, C, D) a pak při tisku startovky bude v tisku místo 4 kategorií a, b, c, d jen jedna. A důležité je, aby to šlo takto vytisknout pro všechny kategorie najednou (tedy i rozběhy DH16, 18, 20, 21), přičemž některé kategorie (např. DH14) takové rozběhy mít nebudou a pro ně to bude to klasická startovka jedné kategorie.
Ideální by bylo, kdyby sis někdy zkusil uspořádat MČR, vše by sis to tam vyzkoušel. :-D
Díky, V.

**Comment by fvacek** [comment]
dobre, tak pridame sloupec do tabulky kategorie, neco jako `class_group` a v print option dialogu moznost `print class groups`, jak potom dostaneme do nadpisu kategorie spravny nazev? Jako `join(class_name, ' + ')`, tohle by stacilo?

**Comment by VoiToi** [comment]
Ahoj, jo, určitě stačilo. V.

**Comment by VoiToi** [comment]
Jinak, název kategorie bych nedělal žádným komínem - místo názvu původních kategorií bude ve startovce vidět jen název skupiny.

**Comment by fvacek** [comment]
> Ale název kategorie v hlavičce startovky musí být doslova H16, H18, H20, H21 a totéž u žen. To je v soutěžním řádu. 

ja spatne pochopil tohle :) ted uz tomu rozumim

**Comment by xkenia** [comment]
Ja o tom uvazoval podobne, ale mirne jinak - pridat sloupec do tabulky kategorie, ktery bude rikat, ze dana kategorie je "podkategorie" a jmeno se vezme substring(class_name, 0, length(class_name)-1). A groupovat se bude podle stejneho nazvu. Ma to nevyhodu, ze se budou muset hlidat nazvy kategorii, ale to budou muset stejne kvuli tisku vysledku.

**Comment by xkenia** [comment]
Pak jeste musime vymyslet, jak tisknout poradi v minute u takto spojenych podkategorii, protoze nemuzeme tisknout, napr. pro H21:
start H21
st. cas 0
clovek z H21A
clovek z H21B
clovek z H21C

st. cas 4
clovek z H21A
clovek z H21B
clovek z H21C
....

Je potreba to v jednotlivych minutach seradit, aby se nedalo vydedukovat, kdo s kym jde rozbeh.

Ja to treba delal tak, ze jsem si na netu nechal vygenerovat nahodne poradi ABCACBBCACBA... a pak jsem tam nahazel lidi z jednotlivych rozbehu.

**Comment by fvacek** [comment]
muzeme lidi v ramci jedne minuty seradit podle abecedy nebo podle `competitorId`

**Comment by xkenia** [comment]
Obe reseni jsou spravna. Muzu se poptat par rozhodcich, co pripadne preferuji.

Nez odpovi, tak bych sel cestou abecedy.

**Comment by arnost00** [comment]
Ja si myslim ze jsme je pokazde radili podle abecedy (podle prijmeni a jmena). Je to jasne definovane, nikoho to nemate. A neda se z toho dedukovat kdo co bezi.

**Comment by frostidllo** [comment]
Osobně jsem to vyřešil tak, že jsem startovky nalosoval v jednotlivých podkategoriích a vyexportoval závod jako .qbe. Pak jsem si založil nový a naimportoval to .qbe, kde jsem sloučil vždy podkategorie do té parent kategorie a z toho vyjel startovky (na start, na shromaždiště, na ORIS).
Vzhledem k tomu, že do ORISu se již standardně na všech závodech startovky nahrávají pomocí xml, tak bych řekl, že sloučení pro tisk tohle určitě nevyřeší.
Je mi jasné, že v roce 2016 byla situace jiná, ale teď je to takto.

**Comment by lukaskett** [comment]
Tohle můžeme pro případ českých závodů zavřít. Nově budou startovky rozběhů známy dopředu:
https://www.orientacnibeh.cz/upload/dokumenty/sekce-ob/zapissk281121.pdf

```
Novelizace Soutěžního řádu soutěží sekce OB
1.7.Zrušit: Rozdělení závodníků do kvalifikačních skupin nesmí být známo dopředu. Neprošel návrh na zrušení
karantény při kvalifikaci.
M ČR na krátké trati:
2.7.Zrušit: Rozdělení závodníků do kvalifikačních skupin nesmí být známo dopředu. Neprošel návrh na zrušení
karantény při kvalifikaci.
```

**Comment by arnost00** [comment]
Takze ted uz je jen potreba umet sdruzit katerogie pro potreby prenosu dat ze semifinale do finale.

**Comment by lukaskett** [comment]
Jestli sdružením myslíš tvorbu startovek, tak na to máme issue #524

**Comment by arnost00** [comment]
Ano. Pak uz tahle issue je na zavreni.

**Comment by paukert** [comment]
Můžeme tedy zavřít :)
