### ISSUE TITLE
na lístečky s mezičasy přidat ztrátu na průběžného vítěze 

### ISSUE THREAD

**Issue by fvacek** [Quick-Event/quickbox#187]
(celkovou ztrátu na nejlepší mezičasy?)

**Comment by viktorm2015** [comment]
Za mne celkovou průběžnou ztrátu na jednotlivých kontrolách. Tj. další sloupec. Pokud by se vešlo i jak celkové pořadí na x-té kontrole, tak i mezičasu. Vhodné konfigurovat alespoň typ lístečku - "základ" ;"rozšířený". Pokud by to někdo nechtěl mít tak složité.
Příkl.řádek:
1. 121  2.31(5.)  2.31(5.)  +0.15
2. 122  5.45(4.)  3.14(3.)  +0.35
3.123  xx.xx(x.)  xx.xx(x.)  +xx.xx
...
-----------------------------------
OK  xx.xx(xx.)  xx.xx(x.)  +xx.xx

**Comment by Paukert** [comment]
V tom příkladu ti chybí ještě ztráta na daném postupu, potom by to vypadalo asi nějak takhle:

Pořadí kontroly, číslo kontroly, mezičas na daném postupu, pořadí na daném postupu, ztráta na postupu, celkový čas na dané kontrole, průběžné umístění na kontrole, celková průběžná ztráta na kontrole

1. 121 2.30 (5.) +0.15 2.30 (5.) +0.15
2. 122 5.15 (4.) +0.20 7.45 (3.) +0.35
3. 123 xx.xx (x.) +xx.xx xx.xx (x.) +xx.xx

**Comment by fvacek** [comment]
![1](https://cloud.githubusercontent.com/assets/4949019/20033164/294a63b6-a39b-11e6-85f1-495e3032807d.jpg)

**Comment by paukert** [comment]
Může se zavřít - #361 řeší stejnou věc a je tam více názorů.
