### ISSUE TITLE
Startovka pro startéra - formát

### ISSUE THREAD

**Issue by opokorny** [Quick-Event/quickbox#201]
Startéry vůbec nezajímá registračka. Chtěli jenom SI, čas, kategorii a jméno. Na normálních etapách chtěli seřadit závodníky v minutě podle posledního trojčíslí SI. 

Startovky pro starty na krabičku jsou OK - seřazené podle jména.

**Comment by xkenia** [comment]
Na startu potrebuje startovku podle startovniho casu. Na beznych zavodech jsou startujici na krabicku pouze HDR a P/T. U zbytku je dulezite cele ciso SI, pripadne startovni cislo v tomto poradi. Zbytek je pouze podruzna zalezitost.

**Comment by fvacek** [comment]
co je predmetem tyhle issue
* [ ] vyndat sloupec registrace?
* [ ] radit zavodniky v minute jinak?

**Comment by paukert** [comment]
Takhle vypadá startovka pro startéra teď (s/bez startovních čísel):

![27](https://user-images.githubusercontent.com/15065907/97119322-b7c4ac00-170f-11eb-9b8d-bd3e7bdef3f1.PNG)
![27_2](https://user-images.githubusercontent.com/15065907/97119320-b72c1580-170f-11eb-9de3-8eb4a2a53f80.PNG)

Řadí se podle startovního času //  Název kategorie // Příjmení
Je podle vás na tom potřeba něco měnit? @opokorny @xkenia

**Comment by paukert** [comment]
Může se tedy asi zavřít :)
