### ISSUE TITLE
Počet závodníků v lese při tisku výsledků

### ISSUE THREAD

**Issue by Osin01** [Quick-Event/quickbox#242]
Aby závodníci věděli, zda už je kategorie uzavřená, hodila by se tato informace přidat např. k parametrům kategorie.

**Comment by fvacek** [comment]
o uzavreni kategorie nerozhoduje pocet zavodniku v lese, ale cas tretiho a start posledniho

**Comment by Osin01** [comment]
Ano, čas do uzavření je super funkce pro pořadatele, ale jde o to, aby měli i závodníci přehled, kolik lidí je ještě může přeběhnout. Navíc ten čas do uzavření není úplně stoprocentní, když není vyčítání přímo u doběhu, může si někdo vyčíst trochu později.

**Comment by fvacek** [comment]
pokud si nekdo vycte pozdeji, neobjevi se to ani v poctu lidi v cili. Tohle je zrovna jednoducha vec, treba se najde dobrovolnik :)

**Comment by paukert** [comment]
Co neco takoveho (dobehlo / melo startovat)?

Jen otazka - kdyz by se omezil tisk na prvnich n mist / vybralo se Exclude disk, tak by to asi melo byt porad stejne, ne?

![pocet](https://user-images.githubusercontent.com/15065907/128175900-cf4e36b4-8a25-4f06-bb37-501fa59d14c5.PNG)

**Comment by fvacek** [comment]
podle me, by mela byt stejna

**Comment by otahirs** [comment]
> ![pocet](https://user-images.githubusercontent.com/15065907/128175900-cf4e36b4-8a25-4f06-bb37-501fa59d14c5.PNG)

jen poznamka: z UX pohledu by imo neměl být počet závodníků stejně výrazně jako kategorie. (Když hledám v papírech tu svoji kategorii, nechci okolo vizuální smog.)

**Comment by paukert** [comment]
ok, tucne necham jen nazev kategorie :)
