### ISSUE TITLE
Omezený přístup pro komentátora

### ISSUE THREAD

**Issue by Osin01** [Quick-Event/quickbox#266]
Přijde mi nebezpečné, aby měl komentátor přístup během závodu ke všem databázím. 
Zkoušel jsem omezit jeho přístup vytvořením uživatele v s omezenými právy přístupu takto:
CREATE ROLE koment LOGIN PASSWORD 'koment' NOSUPERUSER NOINHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;
GRANT USAGE ON SCHEMA optbm2017 TO koment;
GRANT SELECT ON ALL TABLES IN SCHEMA optbm2017 TO koment;
Takto sice nejde měnit databáze a data jsou vidět, ale v aplikaci jde položka změnit a poté  to vyhazuje neustále hlášky, že není povolen zápis do databáze, dokud se tam nedá původní hodnota, nebo aplikace rovnou spadne.
Je nějaký lepší způsob, jak to udělat ve stávající verzi aplikace?

**Comment by fvacek** [comment]
Tento problem jsem zatim vubec neresil, napadaji me 2 moznisti

1. implementovat read-only mode pro QE
1. QE se necha spustit pouze s nekterymi pluginy https://github.com/fvacek/quickbox/wiki/Application-profiles

**Comment by arnost00** [comment]
A co takhle komentatora udelat jako samostatny program? Podobne jako quickshow
Protoze komentator bude vzdy bokem od hlavniho programu.

**Comment by fvacek** [comment]
muzeme udelat soubor quickcomment.bat, ktery s[posti QE s configem pro komentatora

**Comment by arnost00** [comment]
Jo, to je taky varianta.
Vsechno je lepsi nez delat cele QE readonly.

**Comment by Osin01** [comment]
Zkoušel jsem spustit samostatný plugin Speaker :\ quickevent --profile Speaker.conf, ale stále tam vidím Runs a můžu měnit třeba startovní časy apod.
Muselo by se to udělat tak, aby tam  komentátor nemohl nic měnit - aby viděl skutečně jen modul Speaker.
Případně si v batu vybrat, co všechno uvidím.
Jinak spouštěcí bat soubor určitě stačí.

**Comment by fvacek** [comment]
jeste se to nepouzivalo, mrknu se na to

**Comment by Tomaqa** [comment]
Samostatný modul Komentátor není (alespoň v současnosti) dostatečný, protože se třeba nemůžou podívat na startovky.

**Comment by fvacek** [comment]
pozadavky na komentatora jsou sepsany zde #804 , prosim pokracovat v diskuzi tam.
