### ISSUE TITLE
Lokalizace programu

### ISSUE THREAD

**Issue by frantisekpasek** [Quick-Event/quickbox#281]
(už to tady asi zaznělo)

Nestálo by konečně za to, mít pole a ostatní v programu v jazyku, který je vybrán? 
Stav, kdy např. část je anglicky a část česky a často ani nelze z názvu poznat o co jde, mi přijde zoufalý.

**Comment by fvacek** [comment]
Zrovna lokalizace je vec velice jednoducha a zasluzna. Nejsou na to potreba zadne programatorske schopnosti, takze by se mohl najit dobrovolnik, ja to proste nestihnu :)

**Comment by fvacek** [comment]
existuje projekt weblate https://weblate.org/en/ , coz je webove rozhrani, pres ktere by mohli uzivatele QE sami chybejici fraze doplnit/opravit. Musi to ale nekdo hostovat a asi by to bylo fajn na quickevent.cz/localization, co myslite kluci? @arnost00

**Comment by xkenia** [comment]
pracuje se na instalaci toho weblate ...

**Comment by dg0yt** [comment]
OpenOrienteering Mapper [uses](https://hosted.weblate.org/projects/openorienteering/) Weblate's free hosting for open source projects. See https://weblate.org/cs/hosting/. Main disadvantage of the free hosting is the lack of control over users/contributions.

**Comment by fvacek** [comment]
hlavnim vyvojarem weblate Michal Čihař, coz bude asi cech, treba i beha orientaky :) Jestli to ale Kena dokaze nainstalovat, bude to pro nas asi jednodussi.

**Comment by frantisekpasek** [comment]
Až to bude někde zprovozněné, tak s tím pomůžu.

**Comment by dg0yt** [comment]
Pitfalls with Weblate (and maybe also with similar services):
- Formatting of `.ts` files modified edited in Weblate differs from the output of `lupdate`. This creates a lot of `git` noise.
- Plural forms in Weblate are different from plural forms in Qt, and processing with `lupdate`/`lrelease` is likely to drop the wrong form. I just discovered this for Hungarian. At least with the (free) hosted Weblate, it is not possible to change plural rules.

Both issues can be mitigated by pre-/postprocessing of `.ts` files. But I don't know how if this can be integrated in a `qmake` build process as easily as with `cmake`.

**Comment by xkenia** [comment]
Kai, do you know another tool, which is possible to use for quickevent easily?
Thanks

**Comment by dg0yt** [comment]
Despite the issues, I'm quite happy with Weblate and have no experience with other online services. Other proposals for OpenOrienteering Mapper included Transifex (popular) and Launchpad (used by Purple Pen), cf. https://github.com/OpenOrienteering/mapper/issues/605

Support from the Weblate developer is great. Reasonable feature requests were solved in fair time. (I also helped to eliminate some differences in formatting by contributing upstream (actually to https://github.com/translate/translate) but this takes some time to prepare.)

**Comment by fvacek** [comment]
Git noise is annoying thing but I thing that it is a good trade of for the community exposed localization. I'm fine with this.

If the plural forms are treated wrong in Weblate, than it is bug, which can be reported and fixed like bugs in QE :)

**Comment by Paukert** [comment]
I have quite a lot of free time after I have done my school leaving examination, so I can help with localization as well.

Is Weblate somewhere already instaled? @xkenia or can you just generate new localization files, please? @fvacek

**Comment by xkenia** [comment]
Weblate was not successfull :(
We have to use original localization tools for now ...

**Comment by dg0yt** [comment]
How did it fail?

**Comment by xkenia** [comment]
Not so easy to install on webhosting (no sufficient rights). We can talk via phone, write me email to kenia at seznam.cz.

**Comment by fvacek** [comment]
What about better hosting?

**Comment by fvacek** [comment]
Ahoj, zaridil jsem weblate, https://hosted.weblate.org/projects/quickbox/ takze, prosim, doprelozte, co chybi.

Fanda

**Comment by fvacek** [comment]
QE localization can be made via community now (thanks to Michal Cihar), please use https://hosted.weblate.org/projects/quickbox/

**Comment by jmacura** [comment]
Ahoj, koukal jsem na to a pár textů přeložil.
Otázky:
1. Některé řetězce jsou na Weblate přeložené, ale ve verzi 2.2.2, kterou jsem si dnes nainstaloval se zobrazují anglicky.
2. Plugin pro štafety má 0 textů k přeložení.
Čím to?

**Comment by fvacek** [comment]
>     1. Některé řetězce jsou na Weblate přeložené, ale ve verzi 2.2.2, kterou jsem si dnes nainstaloval se zobrazují anglicky.

lokalizace ve weblate se zatim automaticky nezakompiluji, musim to udelat rucne ja. Jde to zautomatizovat, ale jeste jsem se k tomu nedostal.
 
>     2. Plugin pro štafety má 0 textů k přeložení.
>        Čím to?

zapomnel jsem vygenerovat podklady pro preklad

**Comment by jmacura** [comment]
3. překlady, co jsem napsal včera, tam dnes nevidím..?

**Comment by fvacek** [comment]
nevim, jak se to mohlo stat, ja jsem rano cvicne dolokalizoval competitors a je to tam https://hosted.weblate.org/projects/quickbox/

**Comment by jmacura** [comment]
Já jsem přeložil část ORIS a Core, ale všechny mnou upravené řetězce tam jsou znova k přeložení.... 😞

**Comment by fvacek** [comment]
ja jsem ted prelozil `Nahrávám seznam zavodů z Orisu ...` a je to porad tam

**Comment by jmacura** [comment]
V [historii](https://hosted.weblate.org/changes/?page=4&limit=20&project=quickbox) je před 22 hodinami akce "Rebased repository". Nepřemazalo se to tím?
Taky koukám, že indikátor stavu přeložení klesnul z nedělních 80 % na 69 %.

**Comment by fvacek** [comment]
je to mozny, ja porad jeste uplne presne nevim, jak to funguje a co `rebased repository` vlastne znamena, psal jsem uz na support, ale jeste mi neodpovedeli.

**Comment by paukert** [comment]
Ahoj, něco jsem přeložil, ale nejsem si jistý, jestli by měly být některé z následujících stringů vůbec v překladových souborech (Classes/Classes.cs_CZ.ts)

![ClassDefWidget](https://user-images.githubusercontent.com/15065907/55641313-eac1ea80-57cd-11e9-9c15-545384acf462.png)

**Comment by fvacek** [comment]
diky moc, vsechny hesla typu neco.tamto **urcite ne**, je to moje chyba, ze jsem je zapomnel oznacit jako `neprekladat`

**Comment by frantisekpasek** [comment]
Omlouvám se, že nepomůžu s překladem (jak jsem psal výše), nejsem schopnej na svém starém počítači nainstalovat novou verzi. Překlad bez funkčního programu mi nepřijde jako dobrý nápad.

**Comment by fvacek** [comment]
Ja se take omlouvam, ale Qt uz pro win32 nevychazeji, asi je na case poohlednout se po novejsim pocitaci.

**Comment by paukert** [comment]
Ve scriptu `quickbox/devutils/lctools/lctool.sh` a možná i někde jinde (nezkoumal jsem přesně, jak generování překladových souborů probíhá) chybí cesty minimálně ke Speaker a Relays pluginům.

**Comment by paukert** [comment]
Nevím, jestli to už nebylo opraveno, ale nyní chybí na Weblate možnost překládat minimálně řetězce ze souboru `libquickevent/libquickeventgui/src/reportoptionsdialog.ui` (ale asi se to bude týkat celého `libquickevent/*`).

A poprosil bych o update TS souborů, abychom tu českou lokalizaci nějak už +- dokončili :-)

**Comment by fvacek** [comment]
prave jsem je updatnul, nevim, jak rychle se to tam objevi, deje se to nejak automaticky

**Comment by paukert** [comment]
Po pushnutí aktualizovaných TS souborů dojde k aktualizaci na Weblate během pár minut.

Narazil jsem ale na jeden problém. Ze začátku se aktualizované překlady nahrávaly z Weblate automaticky zase zpátky na GitHub, teď se to již ale neděje. Pokud tedy někdo něco na Weblate přeloží (nebo změní překlad) a dojde k aktualizaci TS souborů, tak ty se hned zase automaticky aktualizují i na Weblate, což ale přepíše změny, které tam někdo mezitím udělal. Proto by bylo potřeba vždy před aktualizací TS souborů (nebo před vydáním nové verze) odeslat změny z Weblate ručně na GitHub nebo (opět) povolit automatické odesílání. Viz https://docs.weblate.org/en/latest/admin/continuous.html#pushing-changes

Bude to asi stejný problém, na který již výše upozornil @jmacura

**Comment by fvacek** [comment]
Tohle by prave melo fungovat, podivam se, jestli se to nerozbilo

**Comment by fvacek** [comment]
Napsal jsem Michalu Ciharovi, pry se na to podiva

**Comment by paukert** [comment]
Zdá se, že nyní to již zase funguje :)

**Comment by fvacek** [comment]
tak se na to asi podival :))

**Comment by paukert** [comment]
Prosím ještě o přidání dvou nových komponent na Weblate: libquickeventcore a libquickeventgui

**Comment by paukert** [comment]
IMO je tato issue již vyřešená, česká lokalizace mi přijde už na poměrně dobré úrovni :)

**Comment by jmacura** [comment]
Česká lokalizace určitě, a to díky @paukert ;-) Poté, co se moje úvodní hodinová práce přemazala, jsem už nenašel sílu se k tomu vrátit, takže díky za překlady!

**Comment by fvacek** [comment]
> Česká lokalizace určitě, a to díky @paukert ;-) Poté, co se moje úvodní hodinová práce přemazala, jsem už nenašel sílu se k tomu vrátit, takže díky za překlady!

Bylo to zpusobeno spatnou konfiguraci WebLate a jeste ktomu ne na nasi strane, to se bohuzel stava.

**Comment by paukert** [comment]
Může se zavřít :-)
