### ISSUE TITLE
Enable QWidget based classes to be used in QML files

### ISSUE THREAD

**Issue by fvacek** [Quick-Event/quickbox#3]
QTBUG-39477

https://bugreports.qt-project.org/browse/QTBUG-39477

patch on review: https://codereview.qt-project.org/#change,73592

fortunately Q_ASSERT is wiped out in the release Qt build, one have use own Qt5 build for the QuickBox development, till this bug is not fixed.

**Comment by fvacek** [comment]
Fixed by commit 0f344e052adb8be887a23e575d48cd3669dc1fc5 to workaround QTBUG-39477

**Comment by fvacek** [comment]
reopenning since it is not working for Qt 4.5.1 again

**Comment by fvacek** [comment]
It seems that even debug build is working with Qt 5.4.1, at least on linux x64, more investigation needed.

**Comment by fvacek** [comment]
But it is not working with my own build from git.

**Comment by fvacek** [comment]
not needed for now, I'm not sure if QML is future of QE in UI, rather not

**Comment by dg0yt** [comment]
What's wrong with QML for QE, from your point of view?

**Comment by fvacek** [comment]
After one year of playing with QML, I've found that I'm (as a skilled C++ developer) more productive with Qt and C++. My original plan was to give a chance to contributors without c++ knowledge to implement features to QE. No one has attempted so far :(.  I'm not saying that QML is wrong, it is just wrong for me as a single developer. There are still some areas, like report templates which I plan to keep in QML.

Main weakness of QML from my point of view is:
1. you cannot call base class function implementation from derived one.
1. type erasure in JS => hard JS code refactoring. C++ compiler makes static type check during compilation which can find 90% of refactoring bugs.
1. QML UI is a mixture of declarative and procedural code. It can save some typing, but I'm not quite sure if it worth. Pure declarative UI might work IMHO better, but it will not be QML any more :)
1. Last but not least is rotten bug https://bugreports.qt.io/browse/QTBUG-39477, reported 5 years ago.

**Comment by otahirs** [comment]
Is it possible to close this issue after refactoring from QML to C++ in version 2.3.0?
