### ISSUE TITLE
Návrh na změnu uživatelského rozhraní

### ISSUE THREAD

**Issue by frantisekpasek** [Quick-Event/quickbox#304]
Trošku bych upravil uživatelské rozhraní (viz příklad na obrázku níže):

- vrchní blok s nadpisem bych dal úplně pryč
- řadek pod tím bych přesunul k Soubor, Nástroje, ...
- aktuálně vybranou agendu bych zvýraznil

![obrazek](https://user-images.githubusercontent.com/18633350/37245760-65f46bde-249d-11e8-8dfd-af6d9a955209.png)

**Comment by fvacek** [comment]
Neni to spatnej napad, soucasne rozlozeni je zpusobeno tim, ze jsem myslel, ze QE bude psat vic lidi, takze je to system plug-inu, ktere jsem bohuzel zatim napsal vsechny sam, prot ma kazdy plugin svoje zahlavi a svoje menu. I jako system pluginu by to melo jit predelat tak, jak navrhujes, minimalne zahlavi urcite. U menu to vidim problematicteji, protoze by se menilo podle toho, jaka agenda je vybrana, polozky by se objevovaly a mizely, pripadne by tam musely byt vsechny a povolovat/zakazovat se. Je to trochu narocnejsi na koordinaci pluginu, pridela mi to praci + dalsi mozny zdroj chyb, takze si nejsem jisty, jestli to stoji za to.

**Comment by otahirs** [comment]
může se zavřít
* aktuální modul je zvýrazněn
* rozdělení na globální a modul-specifické menu, jak je teď, dává smysl
