### ISSUE TITLE
Pocet kontrol kategorii v exportu startovek

### ISSUE THREAD

**Issue by Tomaqa** [Quick-Event/quickbox#308]
Ahoj, predem se omlouvam pokud chyba neni na vasi strane.

V exportu startovek z QE do IOF XML nejsou obsazeny pocty kontrol a po nahrani na ORIS tento udaj chybi. [Pouzite soubory](https://github.com/fvacek/quickbox/files/1903880/middle.zip), [ORIS](https://oris.orientacnisporty.cz/Startovka?id=4343).

Co mne vsak zarazi je ze tento udaj nebyl v [XML](https://github.com/fvacek/quickbox/files/1903898/OZ.Podhori.zip) pritomen ani drive (21.10. 2017, [ORIS](https://oris.orientacnisporty.cz/Startovka?id=3888)), presto vsak startovka na ORISu obsazen udaj s poctem kontrol ma.

V cem je prosim problem? Je to nejaka ORISovina?

**Comment by fvacek** [comment]
To vypada jako chyba v exportu nebo spis se po nich jeste nikdo neshanel :)

**Comment by Tomaqa** [comment]
Take nevim. Je mozne ze se tam tehdy ty pocty kontrol dostaly nejakou jinou cestou. Zkusim kontaktovat ORISare, jestli to ten CourseControl umi.

**Comment by otahirs** [comment]
zavřít
