### ISSUE TITLE
QE 1.1.18 na MO na kratke trati 14.4.2018

### ISSUE THREAD

**Issue by tsieger** [Quick-Event/quickbox#315]
Radi bychom kratce shrnuli pouziti QE 1.1.18 pri poradani zavodu MO na kratke trati 14.4.2018 (TAP).

Strucne: **QE fungovalo bez vetsich problemu a bylo prijemne s nim pracovat. Dekujeme za to!**

HW / SW: 3 PC s Win 10, databáze PSQL 10. 

Pocet zavodniku: 1040

Drobne problemy:

1) Prilis siroky tiskovy vystup v PDF - viz #314

2) Je prosim nekde **dokumentace k jednotlivym sloupcum statistiky zavodu?**
Napr. co znamena sloupec "Time to close"? Oznacuje, (a) kdy je mozne uzavrit start dane kategorie? Nebo odhaduje, zda (b) je mozne danou kategorii uzavrit, tj. zda uz zadny zavodnik nemuze zmenit poradi na N prvnich mistech?
Je prosim nejak mozne z programu vycist informaci (b)?

3) Je prosim mozne tridit ve vypisu zavodniku podle vice nez jednoho sloupce?
Use case: setridit si zavodniky podle ciloveho casu (tim se ti, co jeste nevycetli SI, ocitnou v seznamu nahore) a v ramci techto by pak bylo uzitecne tridit podle kategorie, startovniho casu apod. pro lepsi prehled, kdo je jeste na trati.

4) drobny problem - viz #313 

Jeste jednou diky za skvely nastroj!

**Comment by mezkov** [comment]
ad 3) Jestli si to dobře pamatuji, mělo by být řazení sloupců tzv. stabilní. Což znamená, že se při řazení nemění vzájemné pořadí řádků, které mají ve zvoleném sloupcí stejnou hodnotu. Jednorázové seřazení podle cílového času a u stejných časů podle kategorie se pak dá docílit tak, že to nejdřív seřadíš podle kategorie a pak podle času.

**Comment by fvacek** [comment]
> Je prosim nekde dokumentace k jednotlivym sloupcum statistiky zavodu?
Napr. co znamena sloupec "Time to close"? Oznacuje, (a) kdy je mozne uzavrit start dane kategorie? Nebo odhaduje, zda (b) je mozne danou kategorii uzavrit, tj. zda uz zadny zavodnik nemuze zmenit poradi na N prvnich mistech?

Zatim neni, budu rad, kdyz na WIKI nelaka vznikne. Time to close rika, ze kolik minut bude jiste, ze zadny dobehnuvsi zavodnik nezmeni poradi na prvnich 3 mistech v kategorii

> Je prosim mozne tridit ve vypisu zavodniku podle vice nez jednoho sloupce?
Use case: setridit si zavodniky podle ciloveho casu (tim se ti, co jeste nevycetli SI, ocitnou v seznamu nahore) a v ramci techto by pak bylo uzitecne tridit podle kategorie, startovniho casu apod. pro lepsi prehled, kdo je jeste na trati.

zatim ne

**Comment by otahirs** [comment]
změnit název issue na cca "řadit sloupce v tabulce stabilně"

**Comment by paukert** [comment]
tohle by už mělo IMO fungovat :)

**Comment by otahirs** [comment]
Ještě lepší, může se zavřít
