### ISSUE TITLE
QE v1.1.18 netiskla mezičasy -  sprint Slaný 21.4.

### ISSUE THREAD

**Issue by petrsv** [Quick-Event/quickbox#317]
Po výborných předchozích zkušenostech s verzemi 1.0.9 a 1.1.12 jsme tentokrát zažili nepěknou krizi, kterou promptně vyřešilo jen to, že staré instalace nechávám na disku.
Veškerá příprava, včetně testu tisku nepřiřazeného čipu proběhla ok, takže nic zlého netuše jsme rozjeli závod. Každopádně poučení pro příště - otestovat plně při nastavování SI sady předem i fiktivního závodníka na reálné trati a nespokojit se s návodem. 

1) Vyčítání závodníků bohužel vůbec netisklo lístečky a volba zobrazit mezičasy ukázala a ukazuje stále prázdnou stránku. Vyčtení dat bylo asi ok, zobrazit/vytisknout data z čipu také šlo, ovšem s tím že se jedná o nepřiřazený čip. Následné spuštění ve verzi 1.1.12 tento problém bez dalšího odstranilo.  Prosím o info co mohlo být špatně (nějaký parametr apod.) oproti postupu v návodu.   Konfigurace Win, single file. 
[zaloha slany pred zmenou casu simka h14.zip](https://github.com/fvacek/quickbox/files/1939575/zaloha.slany.pred.zmenou.casu.simka.h14.zip)

2) Problém  #314 jsme měli také (jak v 1.1.12. tak 1.1.18). Částečně vyřešen úpravou ovladače tiskárny na tisk v max šíři (216mm) a také použitím jednosloupcové startovky (děkujeme).  Naopak zmizela dobrá možnost tisknout zvlášť startovku pro koridor na volný start - minorita a jde (kdybych si to otestoval předem), kromě nůžek vyřešit i losováním startovky až od 01. 

3) Nový parametr v Kategorii - Use all maps - co to prosím v losování dělá? 

4) Řeší nějak QE situaci (kterou má samozřejmě odchytit rozhodčí v cíli), kdy se závodník po vynechání sběrky a oražení cíle pro ni vrátí a poté znovu orazí cíl? Myslel jsem (z vlastní zkušenosti z vícedeních závodů před x lety v Plzni), že to SI buď vůbec neumožňuje, nebo že to SW (tenkrát asi Kramer) odhalí. Praktický test mi ukázal že ne. Jediný jakýsi doklad takové situace v čipu se zdá být hodnota Finish reserve time, která zachová předchozí ražení cíle.

5) Při úpravě času závodníka (přišel pozdě na start a díky nepozornosti startéra orazil krabičku start) se mi podařilo obdržet chybovou hlášku z databáze, po které se tiskly prázdné výsledky - bohužel nedokážu zopakovat, možná to souviselo s jiným znakem pro oddělovač desetin. Podruhé ze zálohy to již zafungovalo dobře, jen - takto upravený závodník má pak v ORISu upravený čas přičtený v posledním mezičasu, místo v prvním - opět minorita - možná by v takovém případě spíše korektně pomohlo vymazat stime (kde?) 

Děkuju předem za odpovědi

**Comment by fvacek** [comment]
### Ad 1
ztahl jsem si zalohu, pustil si ji u sebe a vsechno mi funguje normalne. Samozremjme ze verim tomu, ze QE nefungoval, ale nedokazu opravit chybu, kterou nedokazu zreprodukovat, proto prosim o podrobnejsi postup, seznam kroku, jak chybu zreprodukovat.

**Comment by petrsv** [comment]
Ad 1) Instalace na 2 počítačích (W10) proběhla standardně. Co je jinak, i teď, že když dám nad stejným souborem v 1.1.12.  v úseky/etapy - libovolný závodník - pravá myš - zobrazit záznamy z čipu - otevře se okno mezičas kde je vyplněný lístek. Totéž v 1.1.18 zobrazí prázdný lístek (viz přiložené "printscreens")

ad 2) PDF už je ok, problém je zřejmě tisk přímo z menu. Viz prinscreen z náhled tisku. Napadá mě jestli příslušný "plug-in" není z US a nepočítá s formátem "letter" a větším odsazením zleva? 
 
Ano jde o startera, kde byla původně volba H+D a ostatní (volný start). To se hodilo, protože na krabičce míváme samostatného startéra, navíc se lidé do těchto kategorií zhusta dohlašují dlouho, takže se tiskne i později.  Nicméně formát startéra je teď lepší než byl, to každopádně.

ad 3) Ok vyzkouším, nicméně u nás to mít asi použití nebude. 
Spíš mě ještě napadá - vložím-li závodníka do vakantu po, pak se o něj počet vakantů sám nesníží, je to tak (indikovalo mi to potom v layoutu překryv po sobě jdoucích kategorií)?

Ad 4) Ok, minorita - u nás šlo o to, že se pár lidí vrátilo pro přehlédnutou sběrku. Prakticky by tak mohli učinit až na základě disku z vyčtení a pokud si potom přijdou vyčíst podruhé, asi na to není šance z programu přijít - nebo ano?

Ad 5) No právě v tomto případě bylo nutné to upravit, protože závodník zmeškal svůj start a ražením startu se započítání tohoto zmeškání elegantně vyhnul (a porušil vylosované pořadí). Samozřejmě, naše chyba - je třeba tu krabičku dát dál a nedovolit to, navíc ta funkcionalita je fajn (i pro lidi jdoucí třeba mimo soutěž po konci kategorie), akorát by se v tom prvním případě hodila možnost ten STIME vymazat - jde to někde?

Apropo a ještě:
 nebylo by možné zobrazovat ve vyčítání SI čipů všechny časy ve formátu HH:MM:SS nebo alespoň startu?  Hodilo by se to při vykopírování do excelu pro kontrolu jestli někdo neulil start (ctime < stime - 02:00) .

Díky
[quickevent 118.docx](https://github.com/fvacek/quickbox/files/1960533/quickevent.118.docx)

**Comment by fvacek** [comment]
> Ad 1) Instalace na 2 počítačích (W10) proběhla standardně. Co je jinak, i teď, že když dám nad stejným souborem v 1.1.12. v úseky/etapy - libovolný závodník - pravá myš - zobrazit záznamy z čipu - otevře se okno mezičas kde je vyplněný lístek. Totéž v 1.1.18 zobrazí prázdný lístek (viz přiložené "printscreens")

To byla moje chyba, jiz je opravena v 1.1.19. v predchozich verzich stacilo zarachtat s combem na vyber listecku, my jsme na to neprisli pri poradani vlastnich zavodu, protoze jsme s tim asi vzdycky pohnuli.

> ad 2) PDF už je ok, problém je zřejmě tisk přímo z menu. Viz prinscreen z náhled tisku. Napadá mě jestli příslušný "plug-in" není z US a nepočítá s formátem "letter" a větším odsazením zleva?

to je nastavenim okraje tisku v nastaveni tiskarny, na screen-shotu je videt vetsi okraj, nez je ten v PDF.

> Ano jde o startera, kde byla původně volba H+D a ostatní (volný start). To se hodilo, protože na krabičce míváme samostatného startéra, navíc se lidé do těchto kategorií zhusta dohlašují dlouho, takže se tiskne i později. Nicméně formát startéra je teď lepší než byl, to každopádně.

Ta funkcionalita mi nekde vypadla, bylo by dobry ji tam vratit :)

> ad 3) Ok vyzkouším, nicméně u nás to mít asi použití nebude.
Spíš mě ještě napadá - vložím-li závodníka do vakantu po, pak se o něj počet vakantů sám nesníží, je to tak (indikovalo mi to potom v layoutu překryv po sobě jdoucích kategorií)?

toto se v tuto chvili neindikuje nikde, pocita se proste pocet zavodniku a porovnava se s poctem map

> Ad 4) Ok, minorita - u nás šlo o to, že se pár lidí vrátilo pro přehlédnutou sběrku. Prakticky by tak mohli učinit až na základě disku z vyčtení a pokud si potom přijdou vyčíst podruhé, asi na to není šance z programu přijít - nebo ano?

jedine tak, ze uz existuje zaznam vycteni s jinym cilovym casem, ukladaji se vsechna vycteni

> Ad 5) No právě v tomto případě bylo nutné to upravit, protože závodník zmeškal svůj start a ražením startu se započítání tohoto zmeškání elegantně vyhnul (a porušil vylosované pořadí). Samozřejmě, naše chyba - je třeba tu krabičku dát dál a nedovolit to, navíc ta funkcionalita je fajn (i pro lidi jdoucí třeba mimo soutěž po konci kategorie), akorát by se v tom prvním případě hodila možnost ten STIME vymazat - jde to někde?

Uliti startu mu povolil vas starter ne QE. Nejsem si na 100% jistej, ale myslim, ze kdyz mu poeditujete startovni cas, cilovy se prepocita podle neho

> nebylo by možné zobrazovat ve vyčítání SI čipů všechny časy ve formátu HH:MM:SS nebo alespoň startu? Hodilo by se to při vykopírování do excelu pro kontrolu jestli někdo neulil start (ctime < stime - 02:00) .

ve ktere tabulce myslis?

**Comment by petrsv** [comment]
Ad 1) Ano - při "zařachání" respektive přepnutí na classiclottery a zpět se mi to rozběhlo.

Ad 2) Nerozumím. Okraje mám 4mm (v náhledu je určitě víc), a i když ten levý zmenším (v ovladači tiskárny nebo i v dialogu náhledu), nijak se to neprojeví (zkusil jsem 2 různé tiskárny). Proč je vlastně náhled tak posunutý a pdf ne?

Ad 5) Ano. Startovní čas (vylosovaný) editovat nechci, chtěl jsem chybu startéra napravit vymazáním stime (oražený z krabičky start), což v tabulce "Vyčítání SI čipů" bohužel nešlo. Tak jsem jen vypočítal výsledný čas jako:   "cíl - původní nalosovaný start ze startovky"    ručně a ten pak přepsal do sloupce čas což šlo. To opravilo výsledky dle požadavku hl. rozhodčího + ale způsobilo napoprvé chybu databáze (asi špatný oddělovač) a napodruhé (zřejmě logicky) navýšení posledního mezičasu, namísto prvního, kam by to správně patřilo) 

Myslím přímo v tabulce (respektive frontě) "Vyčítání SI čipů." Stačil by ve formátu HH:MM:SS čas ze startovky (jako je v exportu startovky do orisu). Hodně by to usnadnilo kopírování do excelu pro následné odhalení takových věcí jako ad4) pozdní start, nebo ad5) ulitý start, bez potřeby nějak to řešit v QE. Šlo by to?

**Comment by fvacek** [comment]
> Ad 2) Nerozumím. Okraje mám 4mm (v náhledu je určitě víc), a i když ten levý zmenším (v ovladači tiskárny nebo i v dialogu náhledu), nijak se to neprojeví (zkusil jsem 2 různé tiskárny). Proč je vlastně náhled tak posunutý a pdf ne?

Report ma 5 mm okraj z kazde strany, aby se maximalizovalo misto pro uzitecnou informaci, na PDF je to videt. V prilozenem docx souboru je okraj 10 mm, to zanamena, ze si tam tiskarna 5 mm pridala. QE s timhle nemuze nic udelat, musi to byt nekde v nastaveni tiskarny.

> Ad 5) Ano. Startovní čas (vylosovaný) editovat nechci, chtěl jsem chybu startéra napravit vymazáním stime (oražený z krabičky start), což v tabulce "Vyčítání SI čipů" bohužel nešlo. Tak jsem jen vypočítal výsledný čas jako: "cíl - původní nalosovaný start ze startovky" ručně a ten pak přepsal do sloupce čas což šlo. To opravilo výsledky dle požadavku hl. rozhodčího + ale způsobilo napoprvé chybu databáze (asi špatný oddělovač) a napodruhé (zřejmě logicky) navýšení posledního mezičasu, namísto prvního, kam by to správně patřilo)

Chyba databaze je urcite neco, co by melo byt opraveno, jinak si myslim, ze je chovani QE adekvatni. Btw, clovek je vic nez program, promluvte se starterem.

> Myslím přímo v tabulce (respektive frontě) "Vyčítání SI čipů." Stačil by ve formátu HH:MM:SS čas ze startovky (jako je v exportu startovky do orisu). Hodně by to usnadnilo kopírování do excelu pro následné odhalení takovýchto věcí jako pozdní start, nebo ulitý start, bez potřeby nějak to řešit přímo v QE. Šlo by to?

jako, ze misto casu mmm:ss relativne od startu by tam bylo absolutne HH:MM:SS? V cem by to pomohlo, je pro to nejaky use case?

**Comment by petrsv** [comment]
Ad 2) Nenašel jsem. "Workaround" je bohužel generovat tisk do pdf a tisknout až ten. Každopádně je divné, že se to děje jen tady.

User story je mít možnost opravit chybu a vydat správné výsledky podle požadavku hl. rozhodčího/jury, když se něco takového stane. Člověk je určitě víc než SW, ano, nicméně je také chybující. Uznávám, že usnadnění exportu do excelu je jen nápad na jeden spíše neelegantní "workaround."
Bylo by určitě lepší a čistší mít možnost na pravou myš opravit/vymazat stime (stejně jako to jde s jinými poli v té tabulce). 
Potom zabudovat kontrolu (napadá mě něco jako třeba oranžové podbarvení ve vyčítací frontě...) na ctime - 2min (asi spíš parametr) vs. start ze startovky. Myslím, že tenhle požadavek už tu kdysi i byl.

**Comment by fvacek** [comment]
> Ad 2) Nenašel jsem. "Workaround" je bohužel generovat tisk do pdf a tisknout až ten. Každopádně je divné, že se to děje jen tady.

s nastavenim tvoji tiskarny ti nepomohu, pokud si dobre vzpominam trapilo to i nekoho jineho. Mozna zmenit tiskarnu. Ja bych v QE mohl jedine zuzit potisknutou siri treba na 190 mm, tim by se to castecne vyresilo, ale stejne by ten tisk nebyl pekne uprostrd stranky. Mozna je ta tiskarna jenom moc chytra :)

> User story je mít možnost opravit chybu a vydat správné výsledky podle požadavku hl. rozhodčího/jury, když se něco takového stane. Člověk je určitě víc než SW, ano, nicméně je také chybující. Uznávám, že usnadnění exportu do excelu je jen nápad na jeden spíše neelegantní "workaround."
Bylo by určitě lepší a čistší mít možnost na pravou myš opravit/vymazat stime (stejně jako to jde s jinými poli v té tabulce).
Potom zabudovat kontrolu (napadá mě něco jako třeba oranžové podbarvení ve vyčítací frontě...) na ctime - 2min (asi spíš parametr) vs. start ze startovky. Myslím, že tenhle požadavek už tu kdysi i byl.

startovaci cas lze zmenit v tabulce Runs, cilovy se prepocita nasledne

**Comment by petrsv** [comment]
Ad 2) Zkusím ještě nějakou jinou (i když už jsem zkoušel se stejným výsledkem 3 :( ) a případně pak napíšu poznatky do #314, pokud to tam mezitím nevyřešíte...
 
Ad 5) Aha, díky! Nenapadlo mě (někde jsem tu četl, že stime má přednost), že postačí prostě "přepsat" (na stejný) startovací čas v runs a započítá ho to potom namísto chybně oraženého stime. OK.

Poslední věc - ta kontrola na ulité starty, už jsem to tu myslím našel #79

**Comment by fvacek** [comment]
> Ad 2) Zkusím ještě nějakou jinou (i když už jsem zkoušel se stejným výsledkem 3 :( ) a případně pak napíšu poznatky do #314, pokud to tam mezitím nevyřešíte...

je to opraveno v 6d5c7c201fcc1ca3a8d32f6bdfe8e7395236c2cb

**Comment by otahirs** [comment]
může se zavřít

**Comment by paukert** [comment]
Všechny věci jsou vyřešeny, může se zavřít.
