### ISSUE TITLE
Automatický tisk lístečků mezičasů nepřiřazených čipů

### ISSUE THREAD

**Issue by frantisekpasek** [Quick-Event/quickbox#331]
Ve chvíli, kdy mám nastaven "Automatický tisk" lístečků se tisknou i lístečky, které nebyly přiřazeny k závodníkům. Jaký to dává smysl? Přišlo by nám lepší takové lístečky netisknout a lístečky vytisknout až ve chvíli, kdy budou čipy k nějakým závodníkům přiřazeny.

**Comment by frantisekpasek** [comment]
Tak nevím, jestli se chápeme. 
Jde mi o to, aby se lísteček automaticky nevytisknul ve chvíli, když se čip nepřiřadí k závodníkovi.
Naopak, když je čip nepřiřazen a já ho ručně k nějakému závodníkovi přiřadím, tak aby se sám od sebe vytisknul.

**Comment by kamilpipek** [comment]
Pokud vyčte někdo s čipem, který není spárován v závodě se závodníkem, tak bych se přikláněl k tomu, aby se automaticky netisknula výčetka, byť s upozorněním, že jde o neznámého závodníka. Stalo se mi, že jsem zrovna nehlídal jako ostříž a dotyčná lístek sbalila a zmizela. Na konci závodu jsem ji měl pořád v lese  a musel dohledávat, kde se stala chyba. Kdyby ji lístek nevyjel, tak by to sama hned řešila.

**Comment by arnost00** [comment]
Hmm. V aktualni verzi SW uz je mozno nastavit ze se tiskne zavodnikovi jen kratky listecek ze neni prirazen cip. Ale neni to defaultni chovani.

**Comment by kamilpipek** [comment]
Aha, tak to si zkusím dohledat, jak to nastavit. Díky.

**Comment by fvacek** [comment]
<img width="589" alt="image" src="https://user-images.githubusercontent.com/4949019/76169293-f99be480-6176-11ea-9d3c-f4cc015fa6ba.png">

**Comment by otahirs** [comment]
Myslím, že by dávalo smysl nastavit `Error info` jako defaultní, jinak si ze zkušenosti závodníci ani nevšimnou že je něco špatně.

**Comment by fvacek** [comment]
:+1:

**Comment by otahirs** [comment]
Pak tedy bude zbývat pouze automaticky vytisknout lísteček po přiřazení závodníka (je li zapnut autoprint).

**Comment by fvacek** [comment]
:+1:  mozna na to uz je nekde issue

**Comment by otahirs** [comment]
toto bych mohl zvládnout :)
- [ ] `Error info` jako default
- [ ] automatický  tisk lístečeku po přiřazení závodníka (je li zapnut autoprint)

**Comment by arnost00** [comment]
@fvacek ANJ - Ja se to pokusil nejak pojmenovat, ale pokud to neni idealni, tak to upravte.

**Comment by otahirs** [comment]
@fvacek jaký je nejlepší způsob jak se dostat k `chkAutoPrint` z jiného pluginu?
pomocí pointeru na plugin a Q_PROPERTY, případně Q_INVOKABLE, se můžu dostat k informacím z xxxplugin.cpp
jak se však mohu dostat až k atributum/metodám např v xxxwidget.cpp?

**Comment by fvacek** [comment]
> @fvacek jaký je nejlepší způsob jak se dostat k `chkAutoPrint` z jiného pluginu?
> pomocí pointeru na plugin a Q_PROPERTY, případně Q_INVOKABLE, se můžu dostat k informacím z xxxplugin.cpp
> jak se však mohu dostat až k atributum/metodám např v xxxwidget.cpp?
> 
> edit: stejný případ/otázka např u volání `CompetitorsWidget::editCompetitorOnPunch` z jiného widgetu. Předpokládám, že po refaktorizaci již není potřeba používat `onDbEventNotify`, pokud nechci informovat o eventu vsechny pc připojené k databázi.

dokud to byly skutecne pluginy, tak asi nejlepsi zpusob je Q_PROPERTY toho pluginu. Ted je mozne volat jakoukoliv funkci pluginu treba `ReceiptsPlugin::isAutoPrint()`, je to lepsi, protoze tuto zmenu v API (na rozdil od Q_PROPERTY) kompilator odhali.

**Comment by otahirs** [comment]
může se zavřit

**Comment by arnost00** [comment]
Linuxu nevadi vzajemna dependency mezi pluginy ?

**Comment by otahirs** [comment]
Když jsem to psal, viděl jsem, že se jinde volají metody přes invoke. Ale říkal jsem si, že jde o relikt z doby, kdy byl QE rozdělen ještě na volitelné pluginy, tak jsem se asi spletl a mělo to svůj důvod.

**Comment by fvacek** [comment]
> Linuxu nevadi vzajemna dependency mezi pluginy ?

to snad nemuze vadit nikde, kdyz mam a.dll a b.dll, tak snad mohu volat z jedne funkce v druhe a naopak. Spis bych rekl, ze to vadi linkeru a je tam potreba uvest `-la -lb -la`
