### ISSUE TITLE
Štafety - Standings na lístečku nebere v potaz úsek (v. 2.2.2)

### ISSUE THREAD

**Issue by VoiToi** [Quick-Event/quickbox#375]
Ne mezičasu při štafetách je zobrazena hodnota standings za všechny úseky, což je hodnota, která nedává moc smysl a závodníci ji nepochopí správně.

Příklad:

Pokud v kategorii DH12 budu mít jen 2 štafety, na prvním úseku budou mít oba závodníci správnou hodnotu 1/2 a 2/2.
Na druhém úseku ale budou mít x/4 a y/4 podle toho, kolikátý mají čas ze všech závodníků na 1. i 2. úseku v dané kategorii.
Na 10. úseku by měli x/20 a y/20 ...

PS: Jinak se mi zdá, že vše pěkně chodí a jsem nadšen, že nemusím rozbíhat OB2000 v emulátoru a s QE je to prostě veselejší, můžu si jednoduše pravidelně zálohovat DB, hrabat se v ní atd.
O víkendu pořádám přebor štafet, ale todle si myslím, že závodníci v pohodě skousnou.
Prosím jen o opravu do podzimu, kdy chceme s QE pořádat MČR štafet a družstev. :-)

Díky, Vojta

**Comment by fvacek** [comment]
Co myslis tou opravou od podzimu?

**Comment by VoiToi** [comment]
Ahoj, 5. a 6. 10. 2019 pořádáme MČR štafet a družstev, tak jen že bych byl moc rád, kdyby se ti podařilo to opravit s nějakou rezervou do té doby.

**Comment by fvacek** [comment]
jasny, chtelo by to jeste nejaky stafety mezi tim na otestovani

**Comment by fvacek** [comment]
implemented in 2.3.3

**Comment by otahirs** [comment]
může se zavřít?

**Comment by fvacek** [comment]
tezko rict, nikdo rok neporadal stafety :)

**Comment by otahirs** [comment]
už ano, může se zavřít
