### ISSUE TITLE
Štafety - export výsledků s mezičasy

### ISSUE THREAD

**Issue by VoiToi** [Quick-Event/quickbox#382]
Při štafetách zatím asi nelze snadno vyrobit výsledky s mězičasy.
Přímo tisk mezičasů v programu není a export výsledků IOF nejspíše není správně, nebo ho nic neumí importovat, to jsem zatím nezjišťoval. ORIS import výsledků štafet nejspíše nepodporuje, takže jsem zkoušel importovat export výsledků do WinSplits, ale výsledkem bylo tam jen asi 7 závodníků v pár kategoriích.
Zatím by bylo dobrým řešením, kdyby si export rozuměl alespoň s WinSplits, kam lze výsledky snadno nahrát. Nebo jestli někoho napadá nějaké lepší řešení (zatím bez ORISu), tak raďte.
Díky, Vojta

**Comment by fvacek** [comment]
Ja bych doporucoval implementovat export do IOF XML, hold je to standard, asi by to nemel byt ani problem, jenom bych poteboval videt jak to vypada, delat to z XSD je docela sazka do loterie a jeste to da docela dost prace.

**Comment by VoiToi** [comment]
Nejspíš by toto měl být ten příklad IOF XML 3 pro štafety: [ResultList2.zip](https://github.com/fvacek/quickbox/files/3104573/ResultList2.zip) - viz odkaz ResultList2.xml na stránce https://orienteering.sport/iof/resources/it/data-standard-3-0/.

Vojta

**Comment by fvacek** [comment]
z toho by se to uz dalo vymyslet, dik

**Comment by VoiToi** [comment]
Ahoj, chtěl bych se zeptat, zda je šance, že toto bude do 4.10. zvládnuté?
Díky, Vojta

**Comment by paukert** [comment]
ORIS začal podporovat nahrání výsledků štafet ve formátu IOF XML 3.0

Příklad XML souboru lze nyní najít na IOF GitHubu (https://github.com/international-orienteering-federation/datastandard-v3/blob/master/examples/ResultList2.xml)

**Comment by fvacek** [comment]
daji se ty vysledky v iofxml 3.0 z Orisu i stahnout?

**Comment by paukert** [comment]
Možnost stáhnout výsledky v XML / XML 3.0 tam je, ale vypadá to, že nefunguje správně. Struktura vyexportovaného XML je jako u závodu jednotlivců.

**Comment by fvacek** [comment]
implemented in 2.3.3

XML exportuji, je validni vuci IOF XSD, ovsem jinak nemam jak to vyzkouset.

**Comment by Osin01** [comment]
Zkoušel jsem nahrát výsledky ze závodu loňských MČR štafet od @VoiToi na Oris a WinSpilts.
Exportoval jsem je z verze QE 2.3.3. V exportovaném souboru byly položky <time> s  třemi nulami navíc, které jsem musel oříznut, aby se čas importoval správně.
V [Orisu](https://oris.orientacnisporty.cz/resultrelays?id=5922) se nezobrazují ztráty na úsecích a celkové, protože to jen přebíra údaje jen z XML a QE neexportuje tyto položky: <TimeBehind type="Course">, <TimeBehind type="Leg"> a <TimeBehind>. Oris zřejmě neumí pracovat s mezičasy šafet, takže je nijak nezobrazuje.
[WinSplits](http://obasen.orientering.se/winsplits/online/en/default.asp?page=classes&databaseId=68658) výsledky zřejmě načetl správně, ztráty si dopočítává sám.
[Importované XML, odstraněné 000 z položky <time>](https://github.com/Quick-Event/quickbox/files/4325389/relays-results-iof-3.0.xml.zip)

**Comment by fvacek** [comment]
>V exportovaném souboru byly položky time s třemi nulami navíc, které jsem musel oříznut, aby se čas importoval správně.

jake jsou to polozky?

**Comment by Osin01** [comment]
Promiň, přikládám původní vyexportovaný soubor.
[relays-results-iof-3.0_old.xml.zip](https://github.com/Quick-Event/quickbox/files/4336898/relays-results-iof-3.0_old.xml.zip)
Nuly navíc byly vždy v elementech time, např.
> <time>2208000</time> namísto <time>2208</time> importované časy byly nesmyslně dlouhé.

**Comment by fvacek** [comment]
tim se to vysvetluje, ja mam cas v msec, ale ma byt v sec, dik

**Comment by fvacek** [comment]
fixed in 2.3.4

**Comment by otahirs** [comment]
možno zavřít?
