### ISSUE TITLE
Chyba při pokusu o vložení čipu do tabulky čipů, pokud se v ní daný čip už nachází

### ISSUE THREAD

**Issue by paukert** [Quick-Event/quickbox#391]
Pokud se do tabulky s půjčenými čipy pokusí někdo nějakým nedopatřením přidat číslo čipu, které se v něm už nachází, tak vyskočí ne moc user-friendly hláška. Není to nic strašného, ale třeba až se časem nějací vývojáři budou nudit, tak by se to také mohlo zlepšit.

![si](https://user-images.githubusercontent.com/15065907/57180572-3c6f9a80-6e8a-11e9-81f8-3dcb90d662fa.png)

**Comment by otahirs** [comment]
jsem zde :)

---
Ještě otázka - je třeba mít při vkládání checkbox `insert rows`? není tato funkcionalita žádaná vždy?
![Screenshot from 2020-03-11 20-22-57](https://user-images.githubusercontent.com/24588500/76455591-226de500-63d6-11ea-824b-0fadb8b43319.png)

**Comment by paukert** [comment]
Vždy to žádané není např. pokud máš v excelu počty map pro jednotlivé kategorie a nechceš to přepisovat ručně, tak je v excelu označíš, zkopíruješ, klikneš na políčko s počtem map první kategorie -> vložit, ale zde určitě nechceš nové řádky vkládat.

**Comment by otahirs** [comment]
@paukert a pokud se jedná pouze o vkládání čipů? 
(taky počítám s tím, že implementuji aby se vložily pouze čipy, které v tabulce ještě nejsou)

**Comment by paukert** [comment]
Možná jen kdybys chtěl přepsat čísla již zadaných čipů, ale je otázka, jak moc velký usecase to je..

**Comment by otahirs** [comment]
pak už dává větší smysl všechny smazat a vložit znovu

**Comment by fvacek** [comment]
Je to obecna funkcionalita vsech tabulek, nekdy je potreba prepsat, nekdy vlozit. U cipu to treba je casteji vlozeni, ale to ta tabulka nemuze vedet, dokud to tam nekdo nepriprogramuje. Dale ma tabulka pujcenych cipu unikatni klic na cislo, asi neni potreba resit pripad, kdy si nekdo pujce vickrat stejny cip. Tak to proste je. Kdyby e to melo v tomto partikularnim pripade chovat vice intuitivne, musi to nekdo dodelat. Za me je to takhle good enough, protoze mame spoustu jinych dulezitejsich issues.

**Comment by otahirs** [comment]
Právě si řikám, že bych se na to někdy možná podíval. Při práci s tabulkou čipů to háže errory kde může. Přitom je to podle mě měla být hlavní cesta správy půjčovaných čipů a až to nebude jen `good enough`, tak bych jiné možnosti (zaklikávátka) klidně nemilosrdně zrušil.

**Comment by fvacek** [comment]
pokud chces, tak pretiz pro tuhle tabulku funkci `void TableView::paste()` nebo naimplementuj primo funkci `Importovat cipy`

**Comment by paukert** [comment]
Minimálně AppImage mi nyní celý spadne, pokud se mi do tabulky pro půjčování čipů podaří zadat duplicitní SI.

> 2023-03-31T15:56:22[exception.cpp:73]|E| EXCEPTION!: Chyba při zpracování dotazu: INSERT INTO "lentcards" ("siId") VALUES (?)
 UNIQUE constraint failed: lentcards.siId Řádek se nepodařilo natáhnout at n../../../../libqf/libqfcore/src/model/sqltablemodel.cpp:262 virtual bool qf::core::model::SqlTableModel::postRow(int, bool)
/tmp/.mount_quickeTUh5m0/AppRun: line 11: 150676 Aborted                 (core dumped) $DIR/bin/quickevent

**Comment by fvacek** [comment]
Neni to idealne vyreseno, ale alespon jsem opravil ten pad aplikace. Ve verzi 2.6.16
