### ISSUE TITLE
QE 2.2.3 & 2.2.4 - Mistrovství na klasické trati P a StČ, Mnichovice 25.5.2019

### ISSUE THREAD

**Issue by lpechacek** [Quick-Event/quickbox#403]
ORIS: https://oris.orientacnisporty.cz/Zavod?id=4967
QE soubor: [qe-feedback-4967.zip](https://github.com/fvacek/quickbox/files/3236862/qe-feedback-4967.zip)
Sestava: 2x NTB s Windows 10 a QE 2.2.3-beta, 1x NTB s openSUSE Tumbleweed a QE 2.2.4-beta, databáze PostgreSQL 10.8. Propojeno drátovým ethernetem. K tomu laserové tiskárny na výsledky a dotisk map, vyčítací SI jednotky a termotiskárny.

Ahoj!

Nejdříve velké díky za super fungující program! QE fungoval spolehlivě a "padl nám do ruky", čehož si cením nejvíce.

Možná něco k opravám:
- Drobná chyba v losování po skupinách podle pravidel PSOB - závodníci bez licence (jednorázové přihlášky) nedostanou přidělený startovní čas.
- Losovaní po skupinách PSOB nalosuje stejné kluby za sebou. Snadno se ve startovce opraví ručně.
- libssl 1.0 není přibaleno v archivu, takže mi nefungovaly aktualizace z ORISu na openSUSE Tumbleweed, dokud jsem nedoinstaloval příslušný balík.
- Při vyčítání jednotek s kódy 12, 13, 41, 47, 48, 70, 95 a 104 se v záznamech objevila data z předchozích závodů, i když byla paměť před startem vymazaná pomocí SI Masteru v módu "Extended". Není jasné, za jakých okolností se nadbytečné záznamy dostaly do databáze, ale nejpravděpodobnější je, že tyto jednotky byly vyčteny QE verzí 2.2.4 na Linuxu, zatímco ostatní byly vyčtené v 2.2.3 na Windows. V přiloženém archivu jsou přibalena CSVčka z SI Config+ pro porovnání.

Všeobecné poznámky, pro inspiraci:
- Patchované Qt pro zobrazení barevných dekorací v tabulce bylo překvapení. Před časem jsem zíral do kódu, abych zjistil, proč mi nefunguje podbarvení řádku ve vlastním buildu a nic nevykoukal. Teď už vím, čím to je.
- V programu je spousta skryté funkčnosti při řazení podle startovního času. Nevěděl bych o ní, kdybych si onehdá nevšiml příslušných funkcí ve zdrojovém kódu.
- To že funguje D'n'D při změnách startovních časů jsem zjistil náhodou. To jsem pak ušetřil času při sestavování startovky!
- Možnost zadání čísla čipu pro etapu, beze změny čísla uvedeného v přihlášce, je prima.
- Rozlišení na modré a bílé sloupce je užitečné.
- Funkce vyčítání jednotek ušetřila hodně času po závodě. Zvlášť užitečné se ukázalo vyčtení "Check" jednotek.

Bonus: foto IT zátiší při závodech
![image](https://user-images.githubusercontent.com/5584406/58631487-0aafef00-82e3-11e9-80be-c950c75e60a9.png)

**Comment by fvacek** [comment]
Ahoj, nejdriv podekuji za feed-back a pak se pokusim odpovedet na otazky


> Drobná chyba v losování po skupinách podle pravidel PSOB - závodníci bez licence (jednorázové přihlášky) nedostanou přidělený startovní čas.
>    Losovaní po skupinách PSOB nalosuje stejné kluby za sebou. Snadno se ve startovce opraví ručně.

Tady bych asi potreboval dovysvetlit pravidla OB :)

> libssl 1.0 není přibaleno v archivu, takže mi nefungovaly aktualizace z ORISu na openSUSE Tumbleweed, dokud jsem nedoinstaloval příslušný balík.

O tomhle problemu na Suse vim, ale nejsem si jisty, ze by libssl z meho Debianu problem dobre vyresila. Uprimne receno nevim, co s tim, jedine vyrobit balik pro SUSE. Maji open build service https://build.opensuse.org/ mozna by to slo celkem snadno.

> Při vyčítání jednotek s kódy 12, 13, 41, 47, 48, 70, 95 a 104 se v záznamech objevila data z předchozích závodů, i když byla paměť před startem vymazaná pomocí SI Masteru v módu "Extended". Není jasné, za jakých okolností se nadbytečné záznamy dostaly do databáze, ale nejpravděpodobnější je, že tyto jednotky byly vyčteny QE verzí 2.2.4 na Linuxu, zatímco ostatní byly vyčtené v 2.2.3 na Windows. V přiloženém archivu jsou přibalena CSVčka z SI Config+ pro porovnání.

Uplne tomu nerozumim, jestli byly jednotky vymazany, nemohly v nich starsi data preci byt?

> Patchované Qt pro zobrazení barevných dekorací v tabulce bylo překvapení. Před časem jsem zíral do kódu, abych zjistil, proč mi nefunguje podbarvení řádku ve vlastním buildu a nic nevykoukal. Teď už vím, čím to je.

Qt nepatchuji uz leta. Podbarveni aktualniho radku delam delegatem a ten zavadejici komentar tam nejakym nedopatrenim zustal z obdobi, kdy jsem patchoval :)

> V programu je spousta skryté funkčnosti při řazení podle startovního času. Nevěděl bych o ní, kdybych si onehdá nevšiml příslušných funkcí ve zdrojovém kódu.
    To že funguje D'n'D při změnách startovních časů jsem zjistil náhodou. To jsem pak ušetřil času při sestavování startovky!

Zrovna DnD je vec, ktera se neda uzivateli aplikaci nejak napovedet, asi jedine dokumentace, pokud ji nekdo bude cist. Presun start. casu je velice sikovna funkce a docela casto se setkavam s tim, ze o ni poradatele nevedi :(

Fanda

**Comment by lpechacek** [comment]
Jen krátká poznámka při odchodu na schůzi. QuickEvent se už nějakou dobu snažím zabalit do RPM právě pro automatické kompilace v BuildService. Narážím však na chybějící pravidla pro instalaci zkompilovaných souborů a také Unixovým zvykům nepřirozené umístění sdílených knihoven.

V principu potřebuji doplnit do .pro souborů něco jako níže uvedený příklad. Pak už snáze udělám potřebné .spec soubory pro RPM, případně zabalím i pro další distribuce. Zatím však klopýtám o detaily instalace a lety zteřelé znalosti `qmake`. Pomohlo by možná vidět současné skripty pro výrobu vydání QE, abych mohl jejich funkčnost převést do pravidel `qmake`. HTH

```
diff --git a/libqf/libqfcore/libqfcore.pro b/libqf/libqfcore/libqfcore.pro
index c7fff572c966..5b89cece298b 100644
--- a/libqf/libqfcore/libqfcore.pro
+++ b/libqf/libqfcore/libqfcore.pro
@@ -36,3 +36,14 @@ RESOURCES += \
 TRANSLATIONS += \
        libqfcore.cs_CZ.ts \
        libqfcore.pl_PL.ts \
+
+unix {
+       contains(QMAKE_HOST.arch, x86_64|ppc64|aarch64):{
+               qfcore.path = /usr/lib64/quickevent
+       } else {
+               qfcore.path = /usr/lib/quickevent
+       }               
+       qfcore.files = $$QF_PROJECT_TOP_BUILDDIR/lib/*
+
+       INSTALLS += qfcore
+}
```

**Comment by fvacek** [comment]
myslim, ze toto si uz zaslouzi vlastni issue #407

**Comment by otahirs** [comment]
možno zavřít
