### ISSUE TITLE
Statistiky závodu - chybný formát výpisu údaje "Not printed time"

### ISSUE THREAD

**Issue by janpalas** [Quick-Event/quickbox#418]
V okně "Statistiky závodu" se chybně formátuje údaj "Not printed time" - viz obrázek:

![not-printed-time](https://user-images.githubusercontent.com/14836471/63289458-7771ce80-c2bf-11e9-9999-5db1d62a4705.PNG)

Nevím co vypisované číslo (např. 0,03 nebo 0,08) znamená, ale určitě to nejsou ani minuty, ani poměrná část hodiny (tzn. že 0,25 by bylo 15 minut). Když jsem to v průběhu závodu pozoroval, tak se číslo po setinách zvyšovalo jen velmi pomalu.

**Comment by otahirs** [comment]
k výpočtu _Time to close_ je třeba času 3. závodníka, je tedy třeba změnit podmínku aby **úspěšně** doběhli závodníci minimálně tři
https://github.com/Quick-Event/quickbox/blob/515f64d87bc02a2ded6e99e1e2cd5cb463078308/quickevent/app/plugins/Runs/src/eventstatisticswidget.cpp#L174

---


u _Not printed time_ se používají sloupce `resultsCount` a `resultsPrintTS`, ke kterým jsem nedokázal najít, kde dochází k jejich inicializaci
https://github.com/Quick-Event/quickbox/blob/515f64d87bc02a2ded6e99e1e2cd5cb463078308/quickevent/app/plugins/Runs/src/eventstatisticswidget.cpp#L191
https://github.com/Quick-Event/quickbox/blob/515f64d87bc02a2ded6e99e1e2cd5cb463078308/quickevent/app/plugins/Runs/src/eventstatisticswidget.cpp#L196
