### ISSUE TITLE
Změna fontu na diplomu

### ISSUE THREAD

**Issue by frostidllo** [Quick-Event/quickbox#423]
Definice fontu v .qml diplomu umí pouze 2 možnosti. Snažil jsem se nastavit stejný font, jako má zbytek textu na našem diplomu a podařilo se mi přepínat pouze mezi Times New Roman a Arial (nebo co to je za ten defaultní font).
Při nastavení family: "Times", tam byl Times New Roman a pokud jsem vyplnil cokoliv jiného, tak tam byl font default.
Nikde jsem nenašel nějaký seznam, co tam můžu vyplnit, takže jsem to dělal pokus omyl dle názvů fontů z definic z CSS.
![Image 761](https://user-images.githubusercontent.com/18715961/64543909-59c7e000-d326-11e9-8bbc-2b7a43c88332.png)
![Image 758](https://user-images.githubusercontent.com/18715961/64543910-59c7e000-d326-11e9-9daa-9ca4f2c1eeda.png)

**Comment by paukert** [comment]
Zkusil jsem asi pět různých fontů, které mám nainstalované v počítači a všechny se mi podařilo nastavit. Názvy jsem zadával takové, jako jsem našel v "Nastavení Windows -> Přizpůsobení -> Písma -> Rozkliknout dané písmo -> Sekce metadata -> Celý název" (platí asi jen ve Windows 10)

Impact
![Impact](https://user-images.githubusercontent.com/15065907/65378303-bfb54f80-dcb6-11e9-9e14-473a51db8fef.png)

Ubuntu Mono
![Ubuntu Mono](https://user-images.githubusercontent.com/15065907/65378304-c04de600-dcb6-11e9-8e93-960be712e93e.png)

Agency FB Extended
![Agency FB Extended](https://user-images.githubusercontent.com/15065907/65378306-c04de600-dcb6-11e9-98d8-ccdd8be34133.png)

akaFrivolity
![akaFrivolity](https://user-images.githubusercontent.com/15065907/65378307-c0e67c80-dcb6-11e9-8828-3b9d8827e6bb.png)

Gabriola
![Gabriola](https://user-images.githubusercontent.com/15065907/65378308-c0e67c80-dcb6-11e9-94ca-c0056fcca4c0.png)

**Comment by fvacek** [comment]
Lukasi dik, btw: mas tam poznamku k tvemu pull requestu

**Comment by paukert** [comment]
@fvacek nic tam nevidím :(

**Comment by fvacek** [comment]
@paukert  https://github.com/fvacek/quickbox/pull/435/files

**Comment by paukert** [comment]
Může se asi zavřít
