### ISSUE TITLE
Přiřazení čipu závodníkovi neupraví údaj SI v DB

### ISSUE THREAD

**Issue by frostidllo** [Quick-Event/quickbox#424]
verze QE 2.2.6
na dřívějších verzích (1.x.x) fungovalo, že když si vyčetl někdo se špatným čipem a já jsem dal přiřadit čip závodníkovi, tak mohl pak vyčíst znovu a už mu vyjel správný lísteček (předpokládám, že se upravil záznam o jeho čipu v DB). V této verzi, se ale ponechá původní záznam a musím mu lísteček vytisknout manuálně přes pravý klik.

**Comment by paukert** [comment]
Existuje tu feature request, aby se lísteček po přiřazení závodníkovi sám vytiskl viz #331

**Comment by frostidllo** [comment]
Jo, to by bylo super, kdyby to tak fungovalo. Každopádně neřeší to případ, že tam závodník strčí čip znova. Nerozpitvával bych to, kdyby to nebyla funkce, která dříve fungovala a teď ne

**Comment by fvacek** [comment]
> verze QE 2.2.6
na dřívějších verzích (1.x.x) fungovalo, že když si vyčetl někdo se špatným čipem a já jsem dal přiřadit čip závodníkovi, tak mohl pak vyčíst znovu a už mu vyjel správný lísteček (předpokládám, že se upravil záznam o jeho čipu v DB). V této verzi, se ale ponechá původní záznam a musím mu lísteček vytisknout manuálně přes pravý klik.

jeden z nas ma spatnou pamet, toto podle meho nazoru nikdy nefungovalo, nevzpominam si, ze bych to programoval.

**Comment by Pjootr** [comment]
> 
> 
> Jo, to by bylo super, kdyby to tak fungovalo. Každopádně neřeší to případ, že tam závodník strčí čip znova. Nerozpitvával bych to, kdyby to nebyla funkce, která dříve fungovala a teď ne

Aby vyjel závodníkovi se špatným čipem správný lísteček, musíš zeditovat závodníka ( v "Závodníci" nebo "Úseky/Etapy") a napsat správné číslo čipu do kolonky SI,  po opětovném vyčtení už vyjede správný lísteček.
![priradit_cip](https://user-images.githubusercontent.com/49484751/64942682-fd0a7f00-d869-11e9-9553-9b43b24e434c.png)

Ano, bylo by super kdyby se toto provedlo automaticky po kliknutí na "Přiřadit čip závodníkovi"

**Comment by fvacek** [comment]
prirazenim cipu zavodnikovi se to neprovede, ono by se to melo jmenovat spis prirazeni tohoto konkretniho vycteni tomuto behu konkretniho zavodnika

**Comment by paukert** [comment]
Teď mě úplně nenapadá situace, kdy by automatické přepsání čipu v runs u daného závodníka a etapy mohlo vadit. Není to samozřejmě věc, která by byla nějak nezbytná (po přiřazení čipu závodníkovi může lísteček nyní vytisknout přes kontextové menu obsluha a není tedy důvod, aby tam závodník strkal čip znovu), ale jako špatný nápad mi to nepřijde.

**Comment by viktorm2015** [comment]
Ahoj Kuky,
co treba duplicita čipu v zavode? Nevadilo by náhodou tomu? Jak by si to pak vyčetl?
V.
PS. nechce se mi hledat jak se prih. na Github ;)

Viktor Mutinský
Odesláno z iPhonu

16. 9. 2019 v 15:27, Lukáš Paukert <notifications@github.com<mailto:notifications@github.com>>:


Teď mě úplně nenapadá situace, kdy by automatické přepsání čipu v runs u daného závodníka a etapy mohlo vadit. Není to samozřejmě věc, která by byla nějak nezbytná (po přiřazení čipu závodníkovi může lísteček nyní vytisknout přes kontextové menu obsluha a není tedy důvod, aby tam závodník strkal čip znovu), ale jako špatný nápad mi to nepřijde.

**Comment by Pjootr** [comment]
Duplicita nevadí, to je obrovská výhoda QE, jeden čip může projet závodem několikrát. 
O víkendu jsem to řešil na MTBO, kdy chtěli použit jeden SIAC pro MW10 a pak dospělou kategorii.

**Comment by paukert** [comment]
Duplicita čipu je v QE už nějakou dobu povolena (tj. dva závodníci mohou mít nastavený stejný čip). Nevím jak přesně to má Fanda naprogramované, ale program se pokusí nějakým způsobem určit, kdo s tím čipem zrovna běžel, a pokud to nedokáže, tak to za něj musí při vyčtení čipu udělat obsluha.

**Comment by fvacek** [comment]
presne tak, pokud QE nacte cip a ten je duplicitni pak:
1. ten druhy jeste nemohl odstartovat => priradi ho tomu prvnimu
1. ten prvni uz je v cili => priradi ho druhemu
1. nepalti 1. ani 2. => musi vyresit obsluha
