### ISSUE TITLE
Štafety - při odebrání úseku se nepřepočítají čísla úseků za ním

### ISSUE THREAD

**Issue by VoiToi** [Quick-Event/quickbox#452]
Pokud při štafetách nebo družstvech odeberu nějaký úsek (např. 2.), pak u dalších úseků zůstanou čísla úseků 3, 4, 5 ... tedy výsledkem je družstvo s úseky 1, 3, 4, 5, 6, 7, 8 (místo 1 - 7).

Když si vyčte 2. závodník (v datech číslo úseku 3), tak program hlásí, že má nepřiřazený čip (a nejde ho přiřadit, dokud nenastavím, že je to 2. úsek. Je to logické, ale asi by se měly čísla následujících úseků při jakékoliv změně štafety přepočítat, aby ve štafetě nemohla vzniknout "díra", protože stejně takovou štafetu "s dírou" nelze nijak zpracovat.

**Comment by fvacek** [comment]
Zkousel jsem to a QE dohlasuje do der, takze pokud mas useky 1,3,4,5 a dohlasis zavodnika, ziskas 1,2,3,4,5. Asi bych mohl stafety sesypavat, ale pak to bude zlobit pri nekompletnich soupiskach, kdy nekdo prijde s tim, ze 2. usek dohlasi pozdeji, az bude vedet. Tak nevim.

Asi se to nedeje casto, spis si myslim, ze toto by mel odhalit #262  Fly-check, ktery take ceka na implementaci.

**Comment by xkenia** [comment]
Za mne urcite nesesypavat - program bude delat neco sam a pak se bude par lidi divit. Navic se obcas stane, ze stafetu chce bezet pouze 1. a 3. usek (napr. poradatele, 2. usek jit nechcou, protoze je nejkratsi a hanbastart jim nevadi) a tam by to pak delalo binec.

Navic tady mohou byt i nejake dalsi podminky pro startujici, napr. sudy usek zeny, lichy usek muzi, a sesypanim by se to porusilo.

**Comment by VoiToi** [comment]
Běžet 1. a 3. úsek je ale nesmysl. První úsek nesmí předat třetímu a třetímu nelze vypočítat čas a vytisknout mezičasy, dokud nevyčte 1. i 2.
Nicméně, přesto nesesypávat.

**Comment by xkenia** [comment]
Tretimu vypocitas cas z toho, ze bezi hanbastartem, ktery ma cas zadany presne.

**Comment by otahirs** [comment]
zavřít?! sesypávat nechceme. může se dopsat nako požadavek na kontrolu u Fly-Check
