### ISSUE TITLE
Question (Q): Pouziti QE na vikendovych zavodech

### ISSUE THREAD

**Issue by xkenia** [Quick-Event/quickbox#461]
Zdar, jen bych chtel zjistit, jak pouzivate QE na vikendovych zavodech - zda mate jeden zavod zalozen jako 2etapovy nebo 2 separatni zavody (2 qbe)?

**Comment by Pjootr** [comment]
Pokud nepotřebuju výsledky po N-etapách a nebudu potřebovat ani celkové výsledky jako součet jednotlivých etap, tak nevidím důvod dělat to jako etapový závod. Už jen kdyby se něco pokazilo tak mám ty závody oddělený.
- Rumcajsovy míle 16.-18.8.2019 - jako 1x - 3.etapový závod (1 soubor/DB)
- MTBO 14.-15.9.2019 - jako 3x - 1.etapový závody (3 soubory/DB)

**Comment by xkenia** [comment]
Pokud mas vse v jednom viceetapovem zavode, tak mi prijdou jednodussi dohlasky - udelas jednou a pak jen vybiras startovni casy. Dalsim plusem jsou i startovni cisla, ktera nemusis prenaset pres databazi.

**Comment by Pjootr** [comment]
Ano dohlášky tam se to určitě hodí, ale můžeš si spustit druhou instanci QE a měnit to tam. 
(Ale já tento způsob odmítl, přijde mi riskantní spouštět druhou instanci QE v době, kdy zrovna vyčítám ...) 

Já jsem trochu paranoidní, takže bych šel cestou více souborů a dohlášky až v daný den před závodem, ale každému vyhovuje něco jiného ... ;-)

**Comment by paukert** [comment]
Asi můžeme zavřít.
