### ISSUE TITLE
Nelze vytvořit nebo z orisu importovat nový event, pokud není připojena existující databáze

### ISSUE THREAD

**Issue by otahirs** [Quick-Event/quickbox#462]
Nelze vytvořit nebo z orisu importovat nový event, pokud není připojena existující databáze. Nabídka je zašedlá. 
![disabled](https://user-images.githubusercontent.com/24588500/66634410-4baefd00-ec0d-11e9-9005-0d2620333be9.png)

Pokud si však vytvořím databázi a vytvářím/importuji nový event, stejně jsem dotázán na nový název databáze.
![database name](https://user-images.githubusercontent.com/24588500/66634660-cd068f80-ec0d-11e9-97e9-7c3150658b19.png)

---

Z toho mi vychází, že se stejně již dá vytvořit při importu/vytváření databáze nová, tedy bych zpřístupnil Vytváření a Import eventu i pokud není připojena existující databáze.

**Comment by otahirs** [comment]
Teď mě napadá, že QE potřebuje mít vybraný pracovní adresář/SQL server, takže při prvním spuštění by ani nemělo být dovoleno první okno zrušit.

**Comment by fvacek** [comment]
ano, to dava smysl

**Comment by otahirs** [comment]
close #556
