### ISSUE TITLE
formát času ve startovce

### ISSUE THREAD

**Issue by otahirs** [Quick-Event/quickbox#471]
Momentálně se ve startovce ukazují časy ve formátu např  `9.00`, což je nejenom pro nováčky v orienťáku poněkud matoucí. 

Přimlouval bych ze za možnost, nebo dokonce výchozí stav, aby se statovní čas zobrazoval jakožto čas skutečný, např. 10:02, tedy formát `HH:MM` (pokud je startovní interval i mimo celé minuty, pak HH:MM:SS)

Je to jednoznačný, nedochází k omylům a nemusí se neustále přepočítávat, v kolik vlastně startuji.

**Comment by arnost00** [comment]
Mam takovy dojem ze vetsina startovacich hodin jede v minutach od casu 00. Cili by si pak vsichni potrenovali prevod casu na startu.
Me se libila varianta startovky kde jsou jak cas `9.00` tak `10:09:00` ... to je pak vhodne jak pro laika tak i orientaka a ty linejsi to nenuti vubec premyslet a neco prepocitavat.

**Comment by janzhanal** [comment]
Kazdopadne Oris aktualne prepocitava cas na HH:MM:SS, tudiz by asi bylo zahodno tenhle cas tisknout i na startovky.

**Comment by arnost00** [comment]
Muzu tam tuhle funkcnost zkusit dodelat. Nemel by to byt problem.
Akorat u startovek co maji 2 sloupce uz se nejspis oba casy vedle sebe nevejdou, tam by musel byt jenom jeden.
A jeste ke startovce pro startery - tam bych nechal jenom cas od 00.

**Comment by fvacek** [comment]
Dokud na startu nebudou hodiny ukazujici skutecny cas ve formatu HH:MM:SS, bude zavodnik nucen si cas prepocitat tak nebo tak. QE pouziva MM:SS, protoze jeto kratsi a setrime tak papir. Navrhovana zmena jenom donuti zavodnika misto prepoctu `MM:SS -> HH:MM:SS` provest prepocet `HH:MM:SS -> MM:SS`. Nevidim zadne zlepseni a je to delsi.

**Comment by otahirs** [comment]
Hodiny na startu nemohou ukazovat čas HH:MM:SS, dokud nemohu vytisknout startovky s tímto údajem.
Idea je možnost uspořádat závod v systému, kdy přepočet není nutný ani jeden, což nyní nejde.

**Comment by fvacek** [comment]
Pak zbyva jedina moznost, udelat dalsi option do print dialogu

**Comment by arnost00** [comment]
Prvni navrh jak by to nove option do print dialogu mohlo vypadat :
![startTimesType](https://user-images.githubusercontent.com/8378685/67338149-cbe83300-f528-11e9-8469-07d4fb1cd589.PNG)

**Comment by otahirs** [comment]
```
Start times format

start at 0 (mmm.ss)          
daytime (hh:mm:ss)         
both 
```
počet sloupců bych nezmiňoval, záleží např. na velikosti papíru, layout se může měnit 
(také by měl přibýt popis sloupců ve startovce)

**Comment by fvacek** [comment]
ja bych tam vubec nedaval moznost `both`. Implementace bude jednodussi a budeme setrit papir. Oba sloupce bych dal automaticky do HTML exportu.

**Comment by arnost00** [comment]
![2020-12-27_471_UI](https://user-images.githubusercontent.com/8378685/103180958-9c0a8d00-489b-11eb-957c-5c85cca162b8.png)

**Comment by arnost00** [comment]
Startlist by classes:
![2020-12-27 22_19_03-Start list by classes](https://user-images.githubusercontent.com/8378685/103180966-bcd2e280-489b-11eb-9306-93c355008b80.png)
Startlist by clubs:
![2020-12-27 22_22_43-Start list by clubs](https://user-images.githubusercontent.com/8378685/103180975-c65c4a80-489b-11eb-901d-70aaf7264ecf.png)

**Comment by arnost00** [comment]
4 stage event :
![2020-12-27 22_21_32-Start list by classes for 4 stage(s)](https://user-images.githubusercontent.com/8378685/103180978-e5f37300-489b-11eb-8d1c-4a70e2476908.png)
![2020-12-27 22_23_17-Start list by clubs for 4 stage(s)](https://user-images.githubusercontent.com/8378685/103180979-e68c0980-489b-11eb-93f2-a34597f1b7aa.png)

**Comment by arnost00** [comment]
Zkusil jsem udelat i HTML :
![2020-12-27 23_12_00-Start list by classes](https://user-images.githubusercontent.com/8378685/103180994-1509e480-489c-11eb-8e9a-87a82829387c.png)
![2020-12-27 23_19_55-Start list by clubs](https://user-images.githubusercontent.com/8378685/103180995-163b1180-489c-11eb-8f2b-b7d502021bb6.png)

**Comment by arnost00** [comment]
Teoreticky uz to mam nachystane.

**Comment by otahirs** [comment]
`How to print start times` -> `Start time format` ?

**Comment by arnost00** [comment]
Safra. To mi uniklo :(

**Comment by fvacek** [comment]
@arnost00 mas tam review Arnoste :)

**Comment by arnost00** [comment]
Jeste jsem tam objevil chybu, pokud startovni cas prekrocil pulnoc. Opraveno

**Comment by otahirs** [comment]
1.
- [ ] nyní je při tisku startovky možnost volby `start at 0 (mmm.ss)` nebo `daytime (hh:mm:ss)`
chybí mi stále třetí možnost `both`

2. 
- [ ] stejné volby je třeba přidat i ke startovce pro startéry, tam je stále natvrdo `start at 0 (mmm.ss)`

**Comment by arnost00** [comment]
ad 1) Both se pri navrhu zamitlo. Aspon ja to tak pochopil.

**Comment by arnost00** [comment]
ad 2) Startovku pro startery jsem asi neresil. Resp. nikoho v te dobe nenapadlo ze by se to melo tykat i ji. 
Otazka zni : Je o takovou startovku zajem ? Nebo starteri pozaduji jen startovku mmm.ss

**Comment by fvacek** [comment]
> ad 2) Startovku pro startery jsem asi neresil. Resp. nikoho v te dobe nenapadlo ze by se to melo tykat i ji.
> Otazka zni : Je o takovou startovku zajem ? Nebo starteri pozaduji jen startovku mmm.ss

ja myslim, ze to zalezi na hodinach na startu, pokud vim, tak se zatim vsude na startu pouzivaji hodiny `mmm:ss`, takze starter by to mel mit ve stejnem formatu

**Comment by arnost00** [comment]
![2021-07-12 22_44_20-Window](https://user-images.githubusercontent.com/8378685/125353390-c963e780-e362-11eb-832d-ea12021f1b82.png)

Otazka k diskuzi ...

**Comment by arnost00** [comment]
> 
> 
> > ad 2) Startovku pro startery jsem asi neresil. Resp. nikoho v te dobe nenapadlo ze by se to melo tykat i ji.
> > Otazka zni : Je o takovou startovku zajem ? Nebo starteri pozaduji jen startovku mmm.ss
> 
> ja myslim, ze to zalezi na hodinach na startu, pokud vim, tak se zatim vsude na startu pouzivaji hodiny `mmm:ss`, takze starter by to mel mit ve stejnem formatu

Letos jsem se uz setkal s pozadavkem aby na startovce bylo h:mm:ss 
Prikladam ukazku obou variant (neni to z QE) :
```
18
   09:18:00 (  30) 30    8645413 Zbinden Noah             MC         SUI 0014
   09:18:00 (  28) 28    8647208 Barauskas Rokas          MA         LTU 0004
   09:18:00 (  29) 29    8652218 Bonek Jannis             MB         AUT 0002
19
20
   09:20:00 (  31) 31    8645489 Perrin Mathieu           MA         FRA 0003
   09:20:00 (  32) 32    8651431 Hychko Vitalii           MB         UKR 0002
   09:20:00 (  33) 33    8653384 Pruzina Paul             MC         IRL 0005
```
```
18
      18.00 (  30) 30    8645413 Zbinden Noah             MC         SUI 0014
      18.00 (  28) 28    8647208 Barauskas Rokas          MA         LTU 0004
      18.00 (  29) 29    8652218 Bonek Jannis             MB         AUT 0002
19
20
      20.00 (  31) 31    8645489 Perrin Mathieu           MA         FRA 0003
      20.00 (  32) 32    8651431 Hychko Vitalii           MB         UKR 0002
      20.00 (  33) 33    8653384 Pruzina Paul             MC         IRL 0005
```

**Comment by paukert** [comment]
> Aktualni vzhled startovky. Pri prepnuti na hh:mm:ss prepnout zobrazeni jak u zavodnika tak i skupiny ?

Pokud bych si při tisku vybral možnost hh:mm:ss, tak bych to chtěl mít asi u skupiny a závodníků konzistentní tj. bych změnil zobrazení jak u závodníka, tak u skupiny.

**Comment by arnost00** [comment]
Takze neco na tento zpusob :
```
09:18:00
   09:18:00 (  30) 30    8645413 Zbinden Noah             MC         SUI 0014
   09:18:00 (  28) 28    8647208 Barauskas Rokas          MA         LTU 0004
   09:18:00 (  29) 29    8652218 Bonek Jannis             MB         AUT 0002
09:19:00
09:20:00
   09:20:00 (  31) 31    8645489 Perrin Mathieu           MA         FRA 0003
   09:20:00 (  32) 32    8651431 Hychko Vitalii           MB         UKR 0002
   09:20:00 (  33) 33    8653384 Pruzina Paul             MC         IRL 0005
```

**Comment by paukert** [comment]
> 
> 
> Takze neco na tento zpusob :
> 
> ```
> 09:18:00
>    09:18:00 (  30) 30    8645413 Zbinden Noah             MC         SUI 0014
>    09:18:00 (  28) 28    8647208 Barauskas Rokas          MA         LTU 0004
>    09:18:00 (  29) 29    8652218 Bonek Jannis             MB         AUT 0002
> 09:19:00
> 09:20:00
>    09:20:00 (  31) 31    8645489 Perrin Mathieu           MA         FRA 0003
>    09:20:00 (  32) 32    8651431 Hychko Vitalii           MB         UKR 0002
>    09:20:00 (  33) 33    8653384 Pruzina Paul             MC         IRL 0005
> ```

Já bych to tak udělal :)

**Comment by fvacek** [comment]
Ja bych to udelal takhle

![image](https://user-images.githubusercontent.com/4949019/125994551-04345dc9-8e83-4fb8-a7ba-3bb7115fb641.png)

**Comment by paukert** [comment]
> 
> 
> Ja bych to udelal takhle
> 
> ![image](https://user-images.githubusercontent.com/4949019/125994551-04345dc9-8e83-4fb8-a7ba-3bb7115fb641.png)

Takováhle implementace by měla určitě výhodu v tom, že by bylo pořád možné tisknout 2 sloupce na A4 i se startovními čísly, na druhou stranu, pokud by daná etapa byla s hendikepovým startem a startovní hodiny ukazovaly hh:mm:ss, tak by zobrazení mmm:ss pro jednotlivé běžce nemuselo být nepříjemnější (ale možná je to jen můj pocit).. Ale souhlasím s tím, že v "hlavičce" dané minuty by mohlo být uvedeno jak mmm:ss, tak hh:mm:ss

**Comment by arnost00** [comment]
Takze by se vlastne nemusely delat nejake varianty, ale stacilo by do stavajici startovky pro startery pridat do "skupiny" cas jak od 00 tak i cas h:mm:ss. 
A fungovalo by to dobre jak pro jeden tak i dva sloupce.

**Comment by arnost00** [comment]
![2021-07-19 23_29_57-Window](https://user-images.githubusercontent.com/8378685/126230071-3f87c174-9e4d-41e9-98d4-694386f34b54.png)

**Comment by jmacura** [comment]
> 
> 
> ![2021-07-19 23_29_57-Window](https://user-images.githubusercontent.com/8378685/126230071-3f87c174-9e4d-41e9-98d4-694386f34b54.png)

Moc pěkné, jen mě napadl ještě takový zlepšovák čitelnosti při hednikepu.. Co takhle udělat poslední dvě číslice v řádku tučně, pokud se liší od 00?

**Comment by paukert** [comment]
Je to drobnost, ale nebylo by to hezčí takhle?

![Výstřižek](https://user-images.githubusercontent.com/15065907/126543889-5a401f42-7a90-4eaa-ae7d-9a24e53e9c3e.PNG)

**Comment by arnost00** [comment]
![Start_2021-07-23_14-02-27](https://user-images.githubusercontent.com/8378685/126779188-57414686-d82a-4b3c-bd3a-a0cd677eb356.png)

**Comment by lukaskett** [comment]
Ahoj, aktuálně hodně pořadatelů využívá appku Go! - Start Clock v 24h módu. Plánujete vydat v blízké době verzi, kde by možnost startovek ve formátu času hh:mm:ss byla? Díky

**Comment by arnost00** [comment]
Ahoj. Mam za to ze uz je to od konce cervence mergnuto do hlavni vetve. Cili vsechny release z hlavni vetve od 31.7. uz to obsahuji.

**Comment by lukaskett** [comment]
Dík za info, použil jsem build z actions a vypadá to parádně. Dobrá práce kluci 👌.

**Comment by arnost00** [comment]
> Jen bych si dal maličko pozor - nevím, jak moc dobře jsou otestované verze 2.4.x (verze po zahrnutí #629) - byl tam poměrně velký refactoring.

Ale zase budeme radi kdyz nekdo tyto verze otestuje :)

**Comment by otahirs** [comment]
pořádal jsem na tom oblž, takže riziko vážných chyb by nemělo být tak zlé

**Comment by paukert** [comment]
@otahirs může se zavřít?
