### ISSUE TITLE
BUG? Vkládání závodníka

### ISSUE THREAD

**Issue by diskar** [Quick-Event/quickbox#478]
BUG? když otevřu okno v Závodníci / Vložit řádek, abych přidal závodníka, kliknu na E1, dám křížek (čili nic neudělám), ukončím vkládání Cancel (čili opět nic neudělám), vloží to prázdný řádek a ubere to jedno volné místo z kategorie. verze 2.2.9. Win10.
Má se to tak chovat? Čekal bych, že to nic nevloží.

**Comment by fvacek** [comment]
vlozi to zavodnika, ktery se nijak nejmenuje, nema zadne registracni cislo, cili prazdny radek. Skoro bych rekl z vyse popsane sekvence kliknuti, ze to uzivatel tak chtel :)

**Comment by diskar** [comment]
uzivatel to tak nechtel. Proto dal na konci cancel.

**Comment by fvacek** [comment]
a proc pred tim mackal E1?

Tim, ze mu chtel priradit startovni cas (stisknutim E1) se musi vytvorit v DB zaznam s odpovidajicim zavodnikem, sic bezejmenym. Asi by to slo nejak osetrrit navodnou hlaskou, ale ja bych spis rekl, ze se jedna o corner-case. Pokud se pouze splete a da hnedle `Cancel`, nic se nevytvori.

**Comment by martinkrivda** [comment]
Stalo se mi to už několikrát, třeba když jsem někoho zaškoloval s přidělováním časů (v testovacím závodu jsem neměl nalosované časy) nebo ve zmatku chtěl někoho přihlásit a sešlo z toho. V zásadě to tedy corner-case je, ale všiml jsem si toho až po několikáté události. A pak hledal a ručně všechny odhlašoval. Chápu, že se při kliku na E1 "musí" řádek založit, ale bylo by za mě fajn ho buď v případě kliku na` Cancel` zase odebrat. Nebo odebrat to tlačítko ` Cancel`.

**Comment by diskar** [comment]
vidim to stejne jako @martinkrivda. A pred zavodem na prezentaci - delame ji v klubu s lidmi, co maji znalost s ovladanim kanc. sw a tlacitko cancel obecne rusi akci a melo by to byt i tady. Cili za me pri Cancel by to melo zrusit zaznamy vytvorene tl. E1.

**Comment by fvacek** [comment]
Tak dobre, presvedcili jste me. Podivam se, jestli to pujde dat cele do transakce a tu pripadne rollback-nout na cancel

**Comment by fvacek** [comment]
implemented in 2.3.3

**Comment by paukert** [comment]
Ve verzi 2.3.3 pozoruji stejné chování jako u verzí 2.2.x. Tohle se objevuje v logu po kliknutí na tlačítko Uložit respektive Cancel.

![log](https://user-images.githubusercontent.com/15065907/72067392-e5f11080-32e2-11ea-91eb-df23bf1085fa.PNG)

**Comment by fvacek** [comment]
fixed in 2.3.4
