### ISSUE TITLE
Oris import: registrace na nový rok

### ISSUE THREAD

**Issue by janzhanal** [Quick-Event/quickbox#484]
Při stažení registrace z orisu je stažena pro aktuální rok.
To ale v lednu a únoru není úplně optimální, protože většinou ještě není zadaná/kompletní (měla by vždy být do konce února).

Tedy bych asi očekával import z registrrace loňské až do konce února.

**Comment by arnost00** [comment]
Otazka ... co ostatni o-sporty ? LOB a MTBO ?

**Comment by janzhanal** [comment]
Priznam se, ze nevim, kdy jsou rozhodne data pro LOB a MTBO?

**Comment by arnost00** [comment]
**LOB** 
Letos je zavodni sezona 1.12.2019 - 31.3.2020, a z pohledu ORISu je to registrace pro rok 2020.
Tam by to pocitani a posunovani do konce unora mohlo delat problemy. Tam by spis se mela registace 2020 vracet jiz od 1.12.2019

**MTBO**
Loni byl uzaviraci termin 15.4.2019, ale tam si nejsem jist nakolik je to pevny termin.

**Comment by janzhanal** [comment]
A jen pro info, jak to fungovalo s loby doted? To nebylo mozne do ledna qe pouzit s registraci?

Asi to teda bude chtit logiku per sport.

**Comment by arnost00** [comment]
Ja si myslim ze LOB vetsinou mel zavody az v lednu tak proto to ve stare verzi fungovalo bez problemu.

**Comment by janpalas** [comment]
LOBy v prosinci IMHO nejsou úplně obskurní záležitostí, teda aspoň v kalendáři (to že se kvůli sněhu pak jedou až po Novém roce nebo vůbec, je věc druhá 😀).

**Comment by fvacek** [comment]
asi by to chtelo dat uzivateli moznost zadat si pocet mesicu zpet s nejakou rozumnou predvyplnenou hodnotou. Zda se, ze uplne automaticky to na 100% vyresit nejde.

**Comment by arnost00** [comment]
Navrh - Neslo by to dat moznost vyberu rocniku registrace ktery se uzivateli stahne ? Predvyplnen by byl aktualni rok. Moznost prepsani jinym rocnikem.

**Comment by fvacek** [comment]
takhle nejak jsem to myslel

**Comment by paukert** [comment]
Implementováno v 2.3.9
