### ISSUE TITLE
Tlačítka "Cancel" bez vedlejších akcí

### ISSUE THREAD

**Issue by otahirs** [Quick-Event/quickbox#487]
Jak bylo nedávno zmíněno v #478, když se v jakékoliv aplikaci stiskne tlačítko _Cancel_ uživatel očekává, že se zavře dialog, neuloží se žádné změny, popřípadě jakékoliv neimplicitně provedené operace budou navráceny. 

V quickeventu má však často stisknutí _Cancel_ (nebo samotné otevření dialogu) za následek vedlejší akci. Na toto nepředvídatelné chování si asi poweruser zvykne, ale těžko se "běžným uživatelům" vysvětluje, že ten program funguje jak má, jen občas dělá nějakou magii.

**Navrhuji tedy úpravu všech dialogů, aby se program vždy po stisknutí tlačítka _Cancel_ vrátil do stavu před otevřením dialogu. Zatím vím o těchto případech, kdy se tak neděje:**

- [x] #478 
- [ ] Nedovolit uživateli při spuštění nezvolit databázi/pracovní adresář #462
- [ ] **File -> Open Event -> Cancel  => Nezrušit spojení s aktuálním závodem**

Jestli víte i o dalších výskytech, tak prosím sem s nimi.

**Comment by fvacek** [comment]
Dalsi moznost je tlacitko cancel vypustit v dialozich, kde nema moc smysl. Neulozeni zmen lze pomerne snadno implementovat pomoci transakci. Tato metoda, ale neni pouzitelna, pokud v prubehu prace s dialogem je treba udelat v transakci neco jineho. Obcas se to deje.

**Comment by otahirs** [comment]
Kde nemá vůbec smysl (připojit k databázi při otevření quickeventu?) se dá vynechat (musí se myslet i na křížek okna), ale jinak kde to lze bych se snažil jej zachovat a navrátit předchozí změny. Často se při proklikávání programu dá "omylem" otevřít nějaký dialog a je dobrý mít jistotu, že při jeho zavření se nic nezmění.
My asi budeme vědět co se zhruba děje, ale u člověka, kterého při pořádání posadíš za počítač nechceš řešit "neobvyklé" chování.

**Comment by paukert** [comment]
Při testování jsem narazil na pár věcí:

1. Pokud si po spuštění vyberu úložiště dat (SQL server / Single file), potom kliknu na cancel u následujícího dialogu, kde si můžu vybrat z dostupných závodů, tak následně volba File --> Event --> Open event není aktivní
2. Pokud si po spuštění vyberu úložiště dat (SQL server / Single file), potom kliknu na cancel u následujícího dialogu, kde si můžu vybrat z dostupných závodů, tak jsou následně povolené importy textových souborů (File --> Import --> Text file) + synchronizace přihlášek a stažení klubů a registrací, ale nic z toho bych asi neřešil, protože ve všech modulech jsou nabídky také aktivní a jedná se o edge case
3. Pokud jsem připojen k nějaké DB, potom dám File --> Connect to database --> Single file --> u dalšího dialogu cancel, tak podle captionu u okna QE to vypadá, že je původní závod stále aktivní, ale ve skutečnosti je spojení ztraceno

**Comment by fvacek** [comment]
Tlacitko `Cancel` budeme asi muset oddelat. Transakce jsem musel zase smazat, stalo se totiz to, ze kdyz nekdo editoval zavodnika, prestal napr fungovat tisk listecku, protoze kvuli otevrene transakci byly pozdrzeny ostatni SQL dotazy. Mozna se da nejak nastavit mira konkurence pri otevirani transakci, to nevim, ale defaultne to fungovalo takhle blbe.
