### ISSUE TITLE
Import Courses OCAD IOF XML 3.0

### ISSUE THREAD

**Issue by otahirs** [Quick-Event/quickbox#488]
import Courses ve formátu `OCAD IOF XML 3.0` skončí s chybou `Defined controls should contain code: S1`
xml S1 obsahuje, dodám po víkendu

import formátu OCAD v8 funguje

edit: xml nahráno (dodána přípona txt aby šlo nahrát na github)

**Comment by otahirs** [comment]
[ONOS2020.Courses.xml.txt](https://github.com/fvacek/quickbox/files/4053224/ONOS2020.Courses.xml.txt)

**Comment by otahirs** [comment]
výstup z debuggeru:

----
**OCAD V8**
```
defined_courses	<4 items>	QMap<QString, CourseDef>
[0] "D"	
	key	"D"	QString
	value	@0x15b3c40	CourseDef
	[QMap<QString, QVariant>]	<5 items>	QMap<QString, QVariant>
		[0] "classes"	<1 items>	
			key	"classes"	QString
			value	<1 items>	QVariant (QStringList)
		[1] "climb"	0	
			key	"climb"	QString
			value	0	QVariant (int)
		[2] "codes"	<16 items>	
			key	"codes"	QString
			value	<16 items>	QVariant (QVariantList)
		[3] "lenght"	2110	
			key	"lenght"	QString
			value	2110	QVariant (int)
		[4] "name"	"D"	
			key	"name"	QString
			value	"D"	QVariant (QString)
[1] "H"		
[2] "HDD"		
[3] "ZV"	
```
-----
**IOF 3 XML**
```
course_defs	<4 items>	QList<CourseDef> &
[0]	@0x6d35c0	CourseDef
	[QMap<QString, QVariant>]	<5 items>	QMap<QString, QVariant>
		[0] "classes"	<1 items>	
			key	"classes"	QString
			value	<1 items>	QVariant (QStringList)
		[1] "climb"	0	
			key	"climb"	QString
			value	0	QVariant (int)
		[2] "codes"	<16 items>	
			key	"codes"	QString
		[3] "lenght"	2110	
			key	"lenght"	QString
			value	2110	QVariant (int)
		[4] "name"	"D"	
			key	"name"	QString
			value	"D"	QVariant (QString)
[1]	@0x15c17e0	CourseDef
[2]	@0x16abfe0	CourseDef
[3]	@0x15517e0	CourseDef
```

**Comment by otahirs** [comment]
Problém nastává protože v programu probíhá kontrola zda se každý kód na trati nachází i v seznamu všech kódů. Zatímco však (v době kontrolování) v seznamu kódů na trati zůstalo označení pro start a cíl `S1` nebo `F1`, tak v seznamu všech kódů jsou start a cíl uloženy jako `F997` a `S999` 

Mimo tuto issue však musí dojít k diskuzi, zda by quickevent měl počítat s možností rozdílných startů (S1, S2,..), nebo stačí například převést start a cíl na jejich přislušné kódy.

ps: číselné kódy startu a cíle jsou prohozeny  https://github.com/fvacek/quickbox/pull/506

**Comment by fvacek** [comment]
jasny, chyba to je, issue ma label `bug`, jenom rikam, ze start a cil do seznamu patri

**Comment by fvacek** [comment]
ja bych i rad, aby se v te tabulce misto 998 objevilo `S` a misto 999 `F`

**Comment by fvacek** [comment]
nebo spis `S1` `S2` pokud bude vic startu

**Comment by otahirs** [comment]
co nejdříve po naštení ze souboru bych převedl vše na číselné kódy. 
Nechal bych zavedenou konstantu pro první start a cíl, modulem se snadno zjistí který je v pořadí. Při výpisu se to pak dá jednoduše upravit na S1, S2 (připadně jen S pokud je start jediný). Také bych nepočítal starty a cíle do počtu kódů/kontrol.

Pro starty a cíle bych volil příjemnější rozsahy, začánající např. 700 a 900 ?

**Comment by fvacek** [comment]
> Pro starty a cíle bych volil příjemnější rozsahy, začánající např. 700 a 900 ?

jsem pro

> Také bych nepočítal starty a cíle do počtu kódů/kontrol.

ty se tam nepocitaji, pokud ano, je to chyba

**Comment by otahirs** [comment]
700 a 900 mi přijdou opticky hned rozlišitelný, osmička a devítka jsou moc podobné -> čitelnost kódu

uvažoval jsem i něco z rozsahu 1-30, ale stovky jsou zase více odlišné

----
> ty se tam nepocitaji, pokud ano, je to chyba

celkově mi přijde že kdyz import iof v3 nefungoval a jako jediný obsahuje kódy kontrol zvlášt, tak se pohybujeme na neprozkoumané půdě :)

**Comment by otahirs** [comment]
Ještě mě napadá že jakékoliv kódy v rozsahu 31-999 mohou být použity v závodě jakožto kontroly..

**Comment by fvacek** [comment]
fixed in 2.3.4

**Comment by fvacek** [comment]
> Ještě mě napadá že jakékoliv kódy v rozsahu 31-999 mohou být použity v závodě jakožto kontroly..

nakonec jsem to udelala tak, ze starty `S1 - S30` maji kody `10 - 29` a cile `F1 - Fxx` maji kody `900 - 900+xx-1`

**Comment by kamilpipek** [comment]
Stejnou chybu to hlásí při importu tratí v IOF XML 3.0 exportovných z PurplePenu, protože ten starty a cíle ve výchozím nastavení pojmenovává STA1 a FIN1 a ne S1 a F1.

**Comment by otahirs** [comment]
Koukal jsem se na specifikaci IOF XML 3.0. Bohužel místo toho aby všichni používali v xml `optional` parametr `ControlType`, tak píší vše do `Id` kde má být dle specifikace kód kontroly...

Přidám podporu i pro STA1 a FIN1.

**Comment by fvacek** [comment]
@otahirs  ted jsem to napsal, tak prosim zadrz :)

**Comment by fvacek** [comment]
https://github.com/Quick-Event/quickbox/commit/e9ed526d902b58a00b220f386eb796344b39210b

**Comment by fvacek** [comment]
dal jsem tam podporu pro vsechno co zacina na S/F pak nejaky pismena a nakonec cislo

**Comment by otahirs** [comment]
1. 3753c8d3fee108acc629f85145d1bc820d48a86a pravděpodobně rozbil import - OCADv8 [ONOS2020.ClassesV8.txt](https://github.com/Quick-Event/quickbox/files/4322669/ONOS2020.ClassesV8.txt) `Cannot find id for code: 42`

2. v rozsahu 900-999 se stále mohou nacházet kontroly, radší bych jako future-proof řešení přesunul rozsahy na 10-19 a 20-29
3. stále nevyřešeno - courses započítává do počtu kontrol i start a cíl | zobrazení Sx, Fx místo kódů

**Comment by paukert** [comment]
Ve verzi QE 2.3.4 jsem otestoval všechny importy tratí. Všechny následující selhaly:
- OCAD TXT _(Nelze najít ID pro kontrolu: 41)_
- OCAD v8 _(Nelze najít ID pro kontrolu: 41)_
- OCAD IOF XML 2.0 _(Nelze najít ID pro kontrolu: 31)_

S tímto mi vyvstává otázka, jestli je potřeba podporovat 4 možnosti importu tratí (jestli se to v poměru náročnost na údržbu/využití vyplatí, i když na druhou stranu se tohle asi moc často nemění...)

**Comment by fvacek** [comment]
to urcite doladime, muzes prosim prilozit soubory, se kterymi jsi to testoval

**Comment by paukert** [comment]
Určitě, tady jsou :) 
[exported.zip](https://github.com/Quick-Event/quickbox/files/4427729/exported.zip)

Dal jsem tam pro potřeby testování i export IOF XML 3.0, který funguje.

**Comment by fvacek** [comment]
fixed in 2.3.5

opravil jsem import IofXml3.0 a rozbil ty ostatni :)

Lukasi, muzes to prosim jeste vyzkouset, soubory, co jsi poslal jsem zkousel, ty funguji. Dik :)

**Comment by paukert** [comment]
Vypadá to dobře, import proběhl v pořádku :)

Jinak ještě drobnosti, co popisoval už @otahirs:
> stále nevyřešeno - courses započítává do počtu kontrol i start a cíl | zobrazení Sx, Fx místo kódů

tj. při využití importu IOF XML 3.0 jsou v `Classes -> Edit -> Courses` ve sloupci `Cnt` počty o 2 větší, než by měly být a ve sloupci `Codes` se zobrazuje ve sledu kontrol 10 pro start a 900 pro cíl.

**Comment by fvacek** [comment]
to je samozrejme chyba

**Comment by fvacek** [comment]
musim se priznat, ze nevim, jestli je to opravdu chyba, trat je definovana vcetne startu a cile, takze pocet kontrol je spravne, i kdyz je to o 2 vice. Kdyz tam dam nejaky `if`, `cnt` pak nebude odpovidat poctu kodu ve vedlejsim sloupci.

**Comment by otahirs** [comment]
nechal bych počty i kódy kontrol bez startů a cíle.
Dodal bych zvlášť sloupec s označením startu

**Comment by fvacek** [comment]
pak by tam musel byt jeste sloupec pro cil, to se mi moc nelibi

**Comment by fvacek** [comment]
jedna moznost by byla psat v sloupci `cnt` napr. `13+2`

**Comment by otahirs** [comment]
Cnt musí odpovídat počtu kontrol v orisu a na popisech.

Možná bych se vrátil úplně k původní variantě, kdy se vypisuje vše, ale místo kódu S1, F1..

**Comment by paukert** [comment]
Jsem pro variantu zobrazovat počet kontrol bez startu a cíle, jak je to většinou asi zvykem. Hlavně by mi přišlo zvláštní, že by se počet kontrol odvíjel od toho, jaký import tratí bych vybral..

**Comment by fvacek** [comment]
To on se ale odviji :)

**Comment by fvacek** [comment]
Muzeme teda udelat oboji:
* specialni kody prepsat na `S1`, `S2`, `F1` ...
* ovadet pocet kontrol bez specialnich kodu
