### ISSUE TITLE
zjednodušení Reader mode | edit on punch

### ISSUE THREAD

**Issue by otahirs** [Quick-Event/quickbox#492]
Předpokládá, že reader mode _Entries_ je pouze pro funkcionalitu _edit on punch_.
V tomto připadě bych tedy checkbox _edit on punch_ úplně zrušil a reader mode by pak mohl mít dvě možnosti jako doteď:

-  _Readout_ 
-  _Edit runner on punch_ 

Samotný checkbox mi již přijde nadbytečný.

**Comment by fvacek** [comment]
dup #502

**Comment by otahirs** [comment]
1)
Reader mode má nyní dva stavy `Race` a `Entries`
předpokládám že mimo návrhu na zevedení stavů `entries | race | results` nemá tento přepínač žádnou funkci (prosím o opravu jestli se mýlím), až na to, že musí být přepnutý, aby v modulu competitors fungovala volba `edit on punch`.

vracím se tedy k původnímu návrhu z popisu issue, předělat stavy na `Readout` a `Edit runner on punch` a z modulu competitors vymazat checkbox. jednodušší rozhraní, méně kódu

---
2) 
zároveň bych rád vyřešil co dělat, když mám více připojených počítačů, případně krabiček
A) současný stav
* pokud se orazí krabička, na všech počítačích, kde je zapnuté `edit on punch` vyskočí dialog #502
* výhoda - dialog může vyskakovat na jiném počítači než ke kterému je krabička připojena

B) návrh
* dialog vyskočí pouze na počítači, ke kterému je krabička připojena (a má zapnutý edit on punch)
* výhoda - mohu mít dva počítače, ke každému připojenou jinou krabičku a každý může paralelně prezentovat/odbavovat jiného závodníka

výhoda stavu B mi přijde výraznější a snad je výsledkem i méně kódu

**Comment by fvacek** [comment]
souhlasim s 1 i 2.

Ad 1, ta duplicita nastaveni je tam z historickych duvodu a zda se, ze uz nastal cas ji zrusit.
Ad 2, `edit on punch` je experimentalni vlastnost, zajimalo by me, jestli to vubec nekde pouzivaji, je treba ne, protoze zavodnici si nejsou zvykli na prezentaci nosit cipy. Takze je tu jeste moznost 3, `edit on punch` odstranit uplne

**Comment by otahirs** [comment]
díky
Ad Ad 2, my jsme to na zimních ligách začali občas ze zvědavosti používat
největší výhoda je že nemusíš opisovat čip, takže když máš dohlášku, jen pípneš, rovnou vyskočí dialog a jenom dopíšeš, funguje to dobře

**Comment by fvacek** [comment]
oka, pokud mame uzivatele, zachovame to, takze plati tvuj puvodni plan
