### ISSUE TITLE
Uživatelsky zpříjemnit spouštění quickeventu

### ISSUE THREAD

**Issue by otahirs** [Quick-Event/quickbox#501]
Chápu-li správně, tak dnes funguje dialog pro připojení k databázi tak, že když do pole `Event ID` zadám validní ID, tak se mi po připojení k databázi otevře zmíněný event, pokud toto id není v databázi, tak se otevře dialog pro vybrání eventu z databáze k otevření.

Přijde mi matoucí že dialog pro vybrání eventu se někdy zobrazí a někdy ne. Matoucí je už to, že se musím ptát, jestli pole Event ID  při připojení k databázi funguje opravdu tak jak popisuju výše. Zároveň nevím, proč bych osobně vypisoval event id, pokud si ho mohu event daleko jednodušejí vybrat v následujícím kroku z nabídky.

----
Navrhuji tedy vypustit z dialogu pro připojení k databázi textové pole `Event ID` a vždy zobrazovat nabídku pro vybrání eventu. Díky tomu bude také více zřetelné, kdy vybírám adresář s databází - _Single file_ - a kdy už skutečně otvírám příslušný event.

**Comment by fvacek** [comment]
aktualni event se uklada do nastaveni, takze pri opakovanem otevreni toho sameho eventu, neni treba vybirat vubec nic.

**Comment by otahirs** [comment]
To však přímo nesouvísí s přítomností/absencí políčka `Event ID` u dialogu pro výběru databáze.

-----
Můžeme vést diskuzi jestli např. po zvolení databáze načíst aktuální event z nastavení nebo být konzistentní a i tak zobrazit dialog pro jeho výběr. Zde by se však z dostupných eventů v databázi mohl předvybrat ten dříve uložený - click na _OK_ navíc, ale mám jistotu, co je vybráno.

**Comment by fvacek** [comment]
Takhle mas taky jistotu, co je vybrano, presne to, co je v policku event id napsano. 

> Přijde mi matoucí že dialog pro vybrání eventu se někdy zobrazí a někdy ne. Matoucí je už to, že se musím ptát, jestli pole Event ID při připojení k databázi funguje opravdu tak jak popisuju výše. 

zobrazi se v pripade, ze nevyplnis event-id do policka event-id, pokud QE nevi, jaky zavod chces otevrit, zepta se. Co je na tom matouci? 

> Zároveň nevím, proč bych osobně vypisoval event id, pokud si ho mohu event daleko jednodušejí vybrat v následujícím kroku z nabídky.

prave, ze ho vypisovat nemusis, maximalne 1x si ho vyberes v nasl. dialogu

**Comment by otahirs** [comment]
Matoucí je několik věcí: 

1. mám zde políčko pro vyplnění event-id, které není určené primárně od toho aby se do něj zapisovalo. (můžu zapisovat jen existující id a ani nemám jejich seznam)
2. program se chová jinak, pokud políčko vyplním správně / vyplním špatně nebo nevyplním a jako běžný uživatel nevím proč. Proč se mi jednou zobrazí dialog na otevření a podruhé ne?

------
touto změnou se nikdy nepřidá práce navíc, buď se 1x podívám co mám vypsáno v event-id nebo se 1x podívám co mám vypsaný v dialogu open event. Zde se navíc mohu podívat, které všechny eventy jsou v databázi a zároveň mám vypsanou hlavičku `Open event`, takže vím co se děje.

-----
Osobně jsem do tohoto políčka dříve psal jméno eventu, který jsem chtěl později vytvořit (neměl jsem jak zjistit k čemu slouží). QE je fajn program, ale obsahuje několik nepředvídatelných chování nebo nejasných nastavení, tak se je snažím postupně vyhladit, aby byl použitelný pro každáho uživatele. :)

**Comment by fvacek** [comment]
>    mám zde políčko pro vyplnění event-id, které není určené primárně od toho aby se do něj zapisovalo. (můžu zapisovat jen existující id a ani nemám jejich seznam)

ano skutecne neni primarne urceno k tomu, aby se do neho zapisovalo a take se do neho nezapisuje

>    program se chová jinak, pokud políčko vyplním správně / vyplním špatně nebo nevyplním a jako běžný uživatel nevím proč. Proč se mi jednou zobrazí dialog na otevření a podruhé ne?

program se chova stale stejne:
1. vyplneno spravne, otevre se zavod
1. nevyplneno nebo vyplneno chybne, objevi se dialog, kde uzivatel dostane moznost to napravit

> touto změnou se nikdy nepřidá práce navíc, buď se 1x podívám co mám vypsáno v event-id nebo se 1x podívám co mám vypsaný v dialogu open event. Zde se navíc mohu podívat, které všechny eventy jsou v databázi a zároveň mám vypsanou hlavičku Open event, takže vím co se děje.

neni to pravda, prida se jeden dialog navic v 90% otevirani aplikace

> Osobně jsem do tohoto políčka dříve psal jméno eventu, který jsem chtěl později vytvořit (neměl jsem jak zjistit k čemu slouží). QE je fajn program, ale obsahuje několik nepředvídatelných chování nebo nejasných nastavení, tak se je snažím postupně vyhladit, aby byl použitelný pro každáho uživatele. :)

kazdemu i mne se casto stava, ze si mysli, ze to co by se libilo jemu, se bude libit vsem. QE je uz ted s hlediska event-id pouzitelny pro kazdeho, vlastne jsi prvni, kdo si stezuje. Ja si stojim za tim, ze pokud budu muset v 80% spusteni aplikace stale odklikavat ten samy dialog, reknu si, jestli to nahodou neni zbytecne.

**Comment by paukert** [comment]
Z mého pohledu je to nyní nastaveno dobře a není potřeba nic měnit :)

**Comment by otahirs** [comment]
Dostali jsme daleko od mého primární pointy, kde bojuji proti tomuto políčku:
![Screenshot from 2020-01-11 19-50-27](https://user-images.githubusercontent.com/24588500/72209163-c822d780-34ab-11ea-9e45-56ff4c880902.png)
> ano skutecne neni primarne urceno k tomu, aby se do neho zapisovalo a take se do neho nezapisuje

ale zapisuje :smile: 

---
Nejradši bych ho tam vůbec neviděl, automaticky otevřít poslední event po připojení k databázi se může tak jako tak.
Pokud se vám zdá informace o posledně otevřeném eventu nezbytná, nestačila by needitovatelná zmínka ve stylu `Last opened Event ID: XXXX`?

**Comment by fvacek** [comment]
**NEZAPISUJE**

po prve ho nechas prazdne a pri dalsim spusteni QE, je jiz predvyplneno. V zivote jsem do neho nezapisoval.

**Comment by otahirs** [comment]
to je to co se snažím vyzdvihnout, není jedinný důvod, aby toto pole bylo uživatelsky zapisovatelné

**Comment by fvacek** [comment]
> Nejradši bych ho tam vůbec neviděl, automaticky otevřít poslední event po připojení k databázi se může tak jako tak.
Pokud se vám zdá informace o posledně otevřeném eventu nezbytná, nestačila by needitovatelná zmínka ve stylu Last opened Event ID: XXXX?

v podstate se jedna o to, jak uzivatelsky privetive vyresit nekolik zpusobu spusteni QE
1. vytvoreni noveho zavodu
1. import noveho zavodu
1. otevreni stareho
1. otevreni jineho nez posledne

**Comment by fvacek** [comment]
> to je to co se snažím vyzdvihnout, není jedinný důvod, aby toto pole bylo uživatelsky zapisovatelné

to neni, ale nevim jak to udelat jednoduseji. V podstate by tam stacil checkbox open recent event, ale pride mi to stejne blby jako to policko. Vubec by nevadilo, kdyby bylo RO, pak ale nepujde vymazat :)

**Comment by fvacek** [comment]
> Z mého pohledu je to nyní nastaveno dobře a není potřeba nic měnit :)

tohle je prave to tezky, najit to, co se dobre pouziva nejvic lidem. Ja osobne s tim okynkem taky zadnej problem nemam, ale ja obecne nemam moc problemu, takze verim, ze to muze byt pro nekoho matouci. Proto razim metodu znatelnyho zlepsovani, pokud je zmena jenom jina, bez nejakeho WOW, tak si myslim, ze je lepsi to nechat tak, jak to je. Navic je potreba si uvedomit, ze mame jeste spoustu peknych issues cekajicich na implementaci. :)

**Comment by otahirs** [comment]
> 1. vytvoreni noveho zavodu
> 2. import noveho zavodu

Pokud jsem připojen k prázdné databázi bez eventu (pak neukazovat open event dialog), nebo kliknu v open event dialogu na Cancel. Tedy nastane stav, že jsem připojený k databázi, ale nemám zvolený event. 
=> 
Znepřístupnit vše kromě vytvoření/importu nového eventu. Možná zobrazit overlay, který by překryl většinu pracovní plochy se zprávou cca `1. step: Create or Import event`.

----
> 3. otevreni stareho
> 4. otevreni jineho nez posledne

Přiznávám, že současné políčko event-id funguje dobře, je však velmi neintuitivní. Teď nevím žádné wow řešení, ale přidal bych minimálně více vysvětlující popisek ve smyslu `Try to open recent event:`

----
Jako další problém vidím, že k funkci programu je třeba vynutit připojení k databázi. Nabízí se v Connect to database dialogu:

- odstranit Cancel a křízek
- kontrolovat validitu zadaných údajů (např. lze zadat i neexistující cestu) a kontrolovat úspěšné připojení k databázi 

ps: před připojením k SQL serveru bych provedl `ping` s kontrolou odpovědi nebo jinak zabránil dlouhému čekání na timeout.

**Comment by fvacek** [comment]
`ping` jeste vubec nic neznamena, vetsinou je problem `pg_hba.conf` (vlastne skoro vzdycky) a ten ping neodhali. Nekteri admini `ping` explicitne zakazuji a port `5432` muze fungovat. Takze pokud projde `ping` je to jiste dobre znameni, pokud neprojde, jeste to neznamena, ze se nepujde pripojit.

**Comment by otahirs** [comment]
Díky za rozšíření obzorů. Každopádně nějakou kontrolu že na síti je zadaná ip s otevřeným portem je třeba provést. Nyní čekám přes 2 minuty než dostanu error.

**Comment by janzhanal** [comment]
Myslim si, ze zajistit sitovou dostupnost neni to, co se od tehle aplikace ocekava. Nicmene se timeout da urcite snizit na par vterin...

Ze mas otevreny IP a port si prece muzes jednoduse pred spustenim overit treba DB clientem nebo telnetem.

**Comment by otahirs** [comment]
Můžu si to ověřit sám, ale pokud by to pár řádků kódu ověřili za mě a snížil se mi tím timeout na zlomek vteřiny že dvou minut, tak budu nadšený. Pokud lze délku timeout zmenšit i jiným způsobem, nebráním se, toto byl od začátku pouze návrh, jak dlouhému čekání předejít.

**Comment by fvacek** [comment]
zase trochu resime corner-case, normalni je, ze ping projde, protoze to nekdu uz zasitoval. Overovat sitovou konektivitu pomoci QE je nadstandardni funkce programu na poradani zavodu v OB :)

**Comment by otahirs** [comment]
ok, nebudu vás přemlouvat. 

Jen mě "naštvalo", když se mi qe freeznul s vyskočenými hláškami, jedna od systému, že neodpovídá a zda ho chci zabít, druhá od qe za 2min, že už nastal timeout, ale ani jednu hlášku nešlo odkliknout. A zabíjet přes řádku qe, kvůli špatnému nastavení ip serveru mi přišlo přespříliš.

**Comment by fvacek** [comment]
> Jen mě "naštvalo", když se mi qe freeznul s vyskočenými hláškami, jedna od systému, že neodpovídá a zda ho chci zabít, druhá od qe za 2min, že už nastal timeout, ale ani jednu hlášku nešlo odkliknout. A zabíjet přes řádku qe, kvůli špatnému nastavení ip serveru mi přišlo přespříliš.

Ping by bylo polovicate reseni, pomohlo by jen v nekterych pripadech. SQL connect je blokujici volani, takze spravne reseni by bylo otevirat spojeni v jinem threadu. To by bylo spravne reseni, protoze by fungovalo pro vsechny mozne potize pri SQL connectu.

Jediny radek kodu, ktery je dobre je ten, ktery se nenapise a kazdy, ktery je napsan, bude jednou pouzit proti programatorovi, proto mam radsi blbou chybu nez polovicni reseni. QE zacina byt projekt slusne velikosti, je cas zacit setrit radky. 

Ping znamena spoustet child proces, starat se o jeho vystup, v Linuxu je trochu jiny nez ve Windows. Nerikam, ze je to neco hroznyho, jen si myslim, ze to nestoji zato. Kdyz nekdo porada zavody, ktere si zaslouzi Postgres, mel by si nejdriv nastavit sit z mnoha ruznych duvodu.
