### ISSUE TITLE
dialog "Edit on punch" vyskakuje na všech připojených počítačích

### ISSUE THREAD

**Issue by otahirs** [Quick-Event/quickbox#502]
Mám více počítačů se zapnutým `edit on punch` připojených ke stejné databázi.
Po vložení čipu do krabičky vyskočí dialog pro editování závodníka na všech PC.

Nepřidával bych další nastavení, ale dialog bych otevřel jen na PC, ke kterému je připojena krabička. Nepředpokládám že by někdo pípal čip u jedné krabičky (jednoho PC) a přecházel editovat přihlášku k jinému PC.

edit: ukázkový scénář - dva počítače na prezentaci s edit on punch, každý má svoji krabičku, pokud se závodník pípne u jedné, okno vyskočí oboum

**Comment by janzhanal** [comment]
Testovali jsme se dvema krabickama, proto dva pocitace s `edit on punch`.

**Comment by fvacek** [comment]
A proc si na ostatnich pocitacich `edit on punch` nevypnes? Naopak si myslim, ze je to takhle lepsi, protoze pokud budes chtit presunout `edit on punch` na jiny pocitac, nebudes muset prepichovat krabicku a na windows zkoumat, ktery COM tentokrat dostala.

**Comment by otahirs** [comment]
Ano, to je jeden usecase a dává smysl, i když většinou počítač na edit bude
u připojené krabičky. Problém je více krabiček s edit on puch.

**Comment by fvacek** [comment]
Pokud by zavody byly tak velke, ze by se pouzivalo vic krabicek, jedna se o stejnou situaci jako u tisku, kde je zaskrtavatko `this printer only`. Ted je spis potreba rozhodnout, co je uzitecnejsi z nasledujicich moznosti:
1. vzdy editovat pouze jen na stroji, ke kteremu je pripjena krabicka, ktera by se musela prepichovat.
1. checkbox `edit on punch` predelat na listbox 
   * `edit on punch` 
   * `edit on punch, this machine only`
   * `pripadna dalsi volba`

kdyz jsem to tak pekne sepsal, rekl bych, ze asi bude jednodussi zacit tou jednodussi cesto :) cardreaderwidget:685

**Comment by fvacek** [comment]
Ona se otevira vec, ktera se tu diskutovala uz drive a to ze by se zavedlo combo, kde by si uzivatel vybral fazi poradani zavodu:
* entries
* race
* results

kazda faze by blokovala urcite volby, ke kterym muze omylem dojit, napr. ve fazi `race` by neslo losovat ani omylel.

Pokud bychom toto zavedli, pak ve fazi entries by se punch oznacil jako `MARK_ENTRIES` a checkbox `edit on punch` by mel stale smysl, naopak by zmizel ten `reader mode`. Zachoval bych navrh, ze `edit on punch` dialog by vyskakoval v QE ke kteremu je pripojena krabicka.

**Comment by otahirs** [comment]
> `edit on punch` dialog by vyskakoval v QE ke kteremu je pripojena krabicka

myslím že toto bude stejně v 99% usecase

----
blokování voleb mi nepřijde user-friendly, to bych se spíš snažil uklidit např. losování někam do danger zone, nebo jinak výrazně odlišit

#### Teď trochu offtopic celkově o QE:
Omlouvám že na chvíli zanedbám víceetapový model. Samotné rozdělení před/po závodě mi totiž dává smysl a sám jsem o něm přemýšlel. Spíš bych to však realizoval právě pomocí modulů. Nahrubo bych si predstavoval nadhodím např. neco jako:
`Courses` - kategorie, tratě
`Competitors` - jmeno, reg, cip
`Startlists` - pouze startovky (je potřeba)
`Readout` - vyčítání + tisk (kromě nastavení není třeba další modul)
`Results` - vysledky
`Stats` - lidi v lese, pocty map..

Rozdělení by bylo předpokládám věc dlouhé diskuze a teď není důležité, ale pointa je hlavně v tom aby každý _modul_ měl jen jednu funkci a byl přehledný, tedy měl jen nutně potřebné sloupce z databáze. Pokud dělám startovku nebo přižazuji start opravdu nepotřebuji vidět přes 20 různých atributů závodníka.

Víceetapové závody by se IMHO měly řešit stejně jako jednodenní, s centrálním přepínáním etapy někde na panelu + může být jeden modul navíc pro nějakou cetrálnější správu.
...
Ok, když jsem se vykecal. 
#### TLDR k vyjádření:
* stále si myslím, že přepínání fází je neprakticke, ať už kvůli blokovani nebo nutnosti navíc přeskakovat mnohokrát z jedné do druhé a z5
* přepínání etapy bych řešil centrálně -> větší důraz na jednoetapové závody 
* modul pro startovky - řešení přes runs je nešikovné 
* přidat do Readeru dialog pro nastavení tisku a zrušit modul Receipts
* modul Results pro snadné zobrazení výsledků

ps: pokud se přidá modul pro startovky a výsledky, tak pro jednoetapový závod bude runs nepotřebný (zůstaly by mu jen volby pro tisk/export za celý seriál)

**Comment by paukert** [comment]
Co se týče vyskakování okna pro přidání/upravení závodníka, tak podporuju názor s otevíráním okna pouze na počítači, ke kterému je krabička připojena.

Jinak asi při každém závodě řešíme nějaké dohlášky i v průběhu vyčítání, což QE výborně zvládá (na jednom počítači někoho dohlašuju a současně se na něm i vyčítá). Pokud by byla nutnost přepínat mezi jednotlivými fázemi závodu, tak by nějaké takovéto úkony asi nešlo dělat úplně současně a obsluze by to přidalo nějakou práci (samozřejmě má tento přístup i své kladné stránky, otázka je jestli převažují nad zápornými..)

**Comment by fvacek** [comment]
@otahirs v podstate navrhuje roztrhnout modul `runs` na `start` + `results`. Ja souhlasim s @paukert , neco by to prineslo, ale neco to zase odnese. Tak trochu se bojim, ze nakonec ziskame 2x modul `runs`, protoze se vzdycky ukaze, ze je treba ve vysledcich upravit startovni cas a podobne. Me jako uzivatele nejvic obdezuje prepinani modulu a opetovne vyhledavani zavodnika, hodne sloupcu mi moc nevadi, navic se daji skryt.

Spis mam nekdy chut naprogramovat treba v `competitors` kontextovou nabidku `open in runs` a naopak

**Comment by otahirs** [comment]
@fvacek  nevím jestli @paukert reagoal na mě nebo na přepínání mezi `entries | race | results`

rozdělení na `startlist` a `results` by dle mého výrazně posunulo uživatelskou přivětivost pro jednoetapové závody, modul `runs` by v nějaké podobě zůstal, ale čistě jako správa víceetapových závodů (něco jako teďka `relays`)

Nejvíce mě _trápí_ právě startovky, při jednoetapovém závodě v modulu `runs` nic jiného než startovky (a export) nedělám. Současná nutnost mít vybranou kategorii a seřazenost dle startu je pro powerusery ok, ale nějaké jednoduší prostředí by určitě prospělo.

Myslím si, že je to cesta posunout QE k přivětivosti i na jednoetapové závody, ale chápu že se ti to nechcou měnit věci na které jsi zvyklý.

---
`Card reader` a `Receipts` jsou až na nastavení prakticky totožně. Nestálo by za to je sjednotit? Tedy vhodně přesunout nastavení tisku do Card readru?

**Comment by paukert** [comment]
Reagoval jsem na přepínání mezi `entries | race | results`, nicméně podobný názor bych mohl použít i k rozdělí `runs` na `startlist` a `results`. Něco to přinese a něco zase odnese. Situaci u vícedenních závodů při rozdělení na `startlist` a `results` asi nedokážu úplně posoudit, u jednodenních např. obsluha přijde o zpětnou vaznu při upravení startovního času (nebo by musely být nějaké sloupce, když nepočítám ty se základními informacemi, zobrazené v obou modulech)
