### ISSUE TITLE
po zapnutí Autoprintu se vytiskne celá historie lístečků

### ISSUE THREAD

**Issue by otahirs** [Quick-Event/quickbox#503]
Po zapnutí autoprintu se zároveň s vyčtením prvního závodníka vytiskne nejen jeho lísteček, ale i všechny dosud nevytištěné lístečky. 

V mém připadě se vytiskl závodník a s ním i 8 lístečků z testování nastavení vyčítaní.
Předpokládám, že jde o chybu, pokud bych chtěl lístečky dostisknout, mohu je označit a vytisknout dodatečně sám.

**Comment by janzhanal** [comment]
To je s otaznikem, kdyz se ti sekne tiskarna asi chces aby ti potom vyjely nevytistene listecky...
Asi by melo byt zajimave, co si mysli @arnost00 i @fvacek, maji toho odporadaneho za pocitacem vic nez ja!

**Comment by fvacek** [comment]
je to tak, pokud je problem s tiskarnou, je treba vypnout autoprint, poladit tiskarnu, zapnout autoprint a chybejici listecky se dotisknou automaticky.

**Comment by otahirs** [comment]
To davá smysl. Jen se nyní chybějící lístečky začínají tisknout až poté, co krabičku orazí první závodník. Tedy on si třeba po několika minutách vyčte a z tiskárny se začínají valit lístečky.

Také není možnost nějak označit lístky, že už se tisknout nemají, popřípadě je smazat. Takže jsem nucen tisknout i lístky, např. testovací, které tisknout nechci.

**Comment by fvacek** [comment]
tady vidim reseni v tom, naimplementovat volbu `oznacit vybrane listecky za vytisknute`

**Comment by arnost00** [comment]
Kdyz se ti zasekne tisk listecku tak pak chces aby se ti dotisky zbyvajici (vetsinou ti dojde papir). Coz nejpozdeji poznas ze zamrzne QE.

**Comment by otahirs** [comment]
rekapitulace:

1. vyčtu několik čipů (bez lístečků, např. test)
2. *\* pauza 10min \**
3. zapnu autoprint
4. *\* pauza 10min \**
5. vyčte se další čip
6. *\* vytiskne se několik + 1 lístečků \**

možnosti řešení
A) nechat tak jak je
B) zapnutí autoprintu spustí tisk fronty (pořád mohu tisknout i lístečky co jsem nechtěl, ale nedostanu překvapení za 10min)
C) zapnutí autoprintu smaže dosavadní frontu, pokud chci vytisknout minulé lístečky, musím před zapnutím autoprintu explicitně kliknout na `print new`

preferuji za C

**Comment by fvacek** [comment]
ja taky C

**Comment by otahirs** [comment]
verze D)

momentě pracuji na verzi, že zapnutý autoprint vytiskne pouze lísteček pro aktuálně vyčítaný čip, přijde mi že je to přesně ta akce, kterou by uživatel čekal (a předchází se tím nečekaným událostem)

zůstává pouze situace že `print new` tiskne opravdu celou historii nevytištěných lístečků, což je sice přesně to co má dělat, ale asi by stálo za zvážení i nějaká ta volba `oznacit vybrane listecky za vytisknute`
