### ISSUE TITLE
Free order

### ISSUE THREAD

**Issue by xkenia** [Quick-Event/quickbox#508]
Pridat moznost typu zavodu Free order

**Comment by xkenia** [comment]
Uz na tom delam ...

**Comment by fvacek** [comment]
to si nemyslim, kde se ten card checker vybira v QE, v tom commitu jsem to nenasel :)

**Comment by xkenia** [comment]
Spatne popsano, pri vycitani je mozno si vybrat Free order misto Classic. Alespon teda doufam, ze jsem komitl vse, nic mi to tu nehlasi, ze by mi chybelo  komitnout.

**Comment by fvacek** [comment]
ajo, prehlidl jsem to :)
