### ISSUE TITLE
Import IOF v3 files

### ISSUE THREAD

**Issue by xkenia** [Quick-Event/quickbox#51]
Prepare import from v3 of IOF format.

**Comment by fvacek** [comment]
Import of what? Which kind of files do you mean?

**Comment by xkenia** [comment]
http://orienteering.org/resources/it/data-standard-3-0/

**Comment by otahirs** [comment]
import
- [x] courses/classes
- [ ] start list

export
- [x] start list
- [x] results

**Comment by xkenia** [comment]
Import start list not needed for now.
