### ISSUE TITLE
Komentator - jak by s nim chtel pracovat jeden koment (Klusy)

### ISSUE THREAD

**Issue by xkenia** [Quick-Event/quickbox#521]
- hlavní okno otevřené pořád - seznam vsech mezicasu, ktere prichazi - kategorie, kontrola, jmeno, poradi na kontrole
- z hlavniho okna rozkliky na jednotliva radia
- při malém počtu kategorií moznost si otevrit vsechny mezicasy rovnou
- barevne zvyrazeni poradi v hlavim okne (prvnich 5)
- zvýraznění čerstvé informace - hlavne DISQ
- moznost vyhledavat v hlavním okně
- u separatnich oken s mezicasy mit odkazy na predchozi/nasledujici mezicas
- u oddílu místo zkratky celý název (pro spíkry, co to nedělají tak často či se to nenaučí jako já ani za pár let) - nebo hodit do napovedy po najeti mysi

feature
- super by bylo mít dole v mezičasovém okně kategorie i závodníky, kteří mezičasem ještě neproběhli, ideálně s běžícím časem od jejich startu, tak jako to bývá na online výsledcích
- tady jsem už předpokládám za hranicí přínosnosti x ojebu to programovat - přidat sloupec "Okomentováno", kde bude označitelný toggle box - což se bude propisovat do oken s mezičasy kategorií a úplně ideálně i k druhému speakerovi (což by ale bylo, dle odhadu, jak program funguje, na velké kopání:-)

**Comment by fvacek** [comment]
V prvni rade diky za podnety. Body z prvni skupiny mi davaji smysl a mely by byt skoro naimplementovany, takze by melo stacit stavajici modul `speaker` jen trochu poladit.

K druhe skupine:

> super by bylo mít dole v mezičasovém okně kategorie i závodníky, kteří mezičasem ještě neproběhli, ideálně s běžícím časem od jejich startu, tak jako to bývá na online výsledcích

tohle by melo jit relativne snadno

>    tady jsem už předpokládám za hranicí přínosnosti x ojebu to programovat - přidat sloupec "Okomentováno", kde bude označitelný toggle box - což se bude propisovat do oken s mezičasy kategorií a úplně ideálně i k druhému speakerovi (což by ale bylo, dle odhadu, jak program funguje, na velké kopání:-)

vubec to neni na nejake velke kopani, QE umi posilat eventy mezi instancemi, spis bych pred tim, nez se to zacne implementovat rad slysel jeste nazor ostatnich speakeru, aby se vyjadrili:
* jestli je to opravdu killing feature
* jestli neexistuje jiny/lepsi zpusob jak dosahnou kyzeneho efektu
Ja se spikrovanim nemam zadne zkusenosti, takze toto nedokazu rozhodnout.

**Comment by xkenia** [comment]
> tady jsem už předpokládám za hranicí přínosnosti x ojebu to programovat - přidat sloupec "Okomentováno", kde bude označitelný toggle box - což se bude propisovat do oken s mezičasy kategorií a úplně ideálně i k druhému speakerovi (což by ale bylo, dle odhadu, jak program funguje, na velké kopání:-)

Tohle bych aktualne neresil, napsal jsem to sem, abych tu mel vse, co jsem zatim zjistil. Mohlo by se to hodit v pripade, ze by byli 2 komenti, kteri sedi daleko od sebe, coz se za dobu me sluzby nestalo.

**Comment by xkenia** [comment]
> u oddílu místo zkratky celý název (pro spíkry, co to nedělají tak často či se to nenaučí jako já ani za pár let) - nebo hodit do napovedy po najeti mysi
Kdyz nad tim premyslim, tak bych sel cestou tooltipu - bude mensi tabulka.

U toho me ale napada, zda by slo nejak jednoduse udelat, aby ten tooltip byl spojen s kazdou vypsanou registrackou. Proste udelat obecne, ze jakmile vypisu registracku, tak tam mam tooltip s nazvem oddilu.

**Comment by fvacek** [comment]
> U toho me ale napada, zda by slo nejak jednoduse udelat, aby ten tooltip byl spojen s kazdou vypsanou registrackou. Proste udelat obecne, ze jakmile vypisu registracku, tak tam mam tooltip s nazvem oddilu.

znamenalo by to projit vsechny tabulky a prisat u nich jeden SQL join a pak nejaky boiler-plate kod

**Comment by janpalas** [comment]
> Tohle bych aktualne neresil, napsal jsem to sem, abych tu mel vse, co jsem zatim zjistil. Mohlo by se to hodit v pripade, ze by byli 2 komenti, kteri sedi daleko od sebe, coz se za dobu me sluzby nestalo.

To nemusí komentátoři sedět daleko od sebe, abys to využil. Mohou sedět i vedle sebe. Prostě jeden mluví a druhý si něco připravuje/hledá a zrovna se úplně nesoustředí na toho druhého co říká.

> Ja se spikrovanim nemam zadne zkusenosti, takze toto nedokazu rozhodnout.

Jinak k ostatním požadavkům Klusyho (se kterým jsem několikrát spolukomentoval) - ano, všechno mi dává smysl a je využitelné. 

> super by bylo mít dole v mezičasovém okně kategorie i závodníky, kteří mezičasem ještě neproběhli, ideálně s běžícím časem od jejich startu, tak jako to bývá na online výsledcích

Toto by bylo fakt skvělé.

**Comment by fvacek** [comment]
> Tohle bych aktualne neresil, napsal jsem to sem, abych tu mel vse, co jsem zatim zjistil. Mohlo by se to hodit v pripade, ze by byli 2 komenti, kteri sedi daleko od sebe, coz se za dobu me sluzby nestalo.

> To nemusí komentátoři sedět daleko od sebe, abys to využil. Mohou sedět i vedle sebe. Prostě jeden mluví a druhý si něco připravuje/hledá a zrovna se úplně nesoustředí na toho druhého co říká.

pokud sedi daleko od sebe a kazdy si pripravuje neco jineh, nac potrebuji checkbox `odkomentovano`? Ja mam opravdu rad, kdyz kazda feature, kterou mame implementovat, ma jasny konkretni use-case

**Comment by janpalas** [comment]
> pokud sedi daleko od sebe a kazdy si pripravuje neco jineh, nac potrebuji checkbox `odkomentovano`? Ja mam opravdu rad, kdyz kazda feature, kterou mame implementovat, ma jasny konkretni use-case

Asi si nerozumíme. Use case: Komentátoři sedí vedle sebe, první mluví, druhý zatím kontroluje nějaké mezičasy/chystá si něco (=úplně neposlouchá prvního). Druhý pohlédne na monitor a vidí zajímavý mezičas a začne o tom vyprávět, přestože to první již odkomentoval (a druhý ho neslyšel). 

Ano, když to je takhle napsáno, tak to může přijít jako blbost a že jsme asi úplní dementi, ale stává se to :-)

**Comment by fvacek** [comment]
zaviram issue, protoze je rozepsana do 3 separatnich #549 #550 #551
