### ISSUE TITLE
Otázky k dialogu Edit Competitor

### ISSUE THREAD

**Issue by otahirs** [Quick-Event/quickbox#529]
1. Jakou fci má checkbox vlevo nahoře?
2. Jaké využití/usecase má spinbox u zadávání čísla čipu?
3. Not competing | Miss punch | Disqulified - předpokládám, že jde jen o různé možnosti jak být disk? pak by asi měla tato část fungovat jako _radio button_, tedy lze mít vybranou jen jednu z možností. Rovnou bych to této množiny nějak zařadil i `Running` jehož negací je  `Did not start`  

![Screenshot from 2020-03-08 20-20-20](https://user-images.githubusercontent.com/24588500/76171852-1395f100-6190-11ea-952c-f440c4578463.png)

**Comment by jmacura** [comment]
Ad 3) Přemýšlím nad corner-case případy. Nemůže se stát, že je někdo MP a zároveň D, např. protože blbě razil a ještě při tom přelezl nepřekonatelnou zeď? Může být někdo D ještě před tím, než nastoupí do závodu, a tedy být zároveň DNS, např. protože šel dopoledne do závodního lesa "na houby"? Stejně tak se asi někdo může přihlásit jako NC (předpokládám tedy, že "not competing" = mimo soutěž..) a pak být klidně MP, D nebo DNS...

K zamyšlení.

**Comment by otahirs** [comment]
dívám se na to z pohledu, že ta hlavní informace co mě jako pořadatele zajímá je, zde je závodník OK, či nikoliv.
Pokud není OK, tak mu vyberu důvod, pro je diskvalifikován:
* MP - miss punch, chybí kontrola
* DNS - nenastoupil
* NC - mimo soutěž
* DISK - jiný důvod

důvod diskvalifikace mě zajímá vpodstatě jen když tisknu výsledky, může jich být teoreticky více, ale to už není z hlediska OK vs DISK podstatné, tak by mi přišlo vhodné UI zjednodušit např na jeden select box s výše zmíněnými možnostmi

**Comment by xkenia** [comment]
Do vysledku se ale stejne musi vybrat jen jeden priznak. Marne vzpominam, zda ma IOF definovano "poradi" priznaku.
Jinak za mne, pokud je NC (mimo soutez), tak se vlastne nikam do vysledku nepocita, takze by to melo byt nadrazeno cemukoli dalsimu.

**Comment by xkenia** [comment]
MP - melo by skakat samo po vycteni, pokud nema zavodnik orazeny vsechny sve kontroly ve stanovenem poradi; muze zmenit HR/Jury
NC - melo by byt nastaveno jiz pred startem; podle meho nikdo zmenit nemuze; chce se to podivat do pravidel na definovani prace s NC.
ostatni - asi souhlas, ze by mohl byt select box;

**Comment by fvacek** [comment]
`1` uz nevim, asi by tam nemusel byt, zrejme nejaky pozustatek predchoziho vyvoje

`2` spinbox je std editor pro integer, co je na nem divnyho, nerozumim?

`3` NC muze a nemusi byt DISK, MP nemusi byt DISK, pokud jurry urci jinak. ty flagy jsou ortogonalni, nemuze je nahradit lisbox. Asi nemuzou nastat uplne vsechny jejich permutace, ale stejene ne.

**Comment by otahirs** [comment]
> 1 uz nevim, asi by tam nemusel byt, zrejme nejaky pozustatek predchoziho vyvoje

ptal jsem se proto, abych ho mohl případně odstranit

---
> 2 spinbox je std editor pro integer, co je na nem divnyho, nerozumim?

Přijde mi zbytečný. Navíc se kolečkem myši nebo šipkama číslo mění, což u čipu asi nebude usecase a může to vést jen ke zbytečným chybám. 

Taky jsem si pohrával s myšlenkou dát checkbox na půjčený čip přímo vedle čipu a vizuálně nechci mít vedle checkboxu ještě spin.

---
> 3 NC muze a nemusi byt DISK, MP nemusi byt DISK, pokud jurry urci jinak. ty flagy jsou ortogonalni, nemuze je nahradit lisbox. Asi nemuzou nastat uplne vsechny jejich permutace, ale stejene ne.

tady to, přiznávám se, není tak jednoznačný, držet všechny možnosti dává smysl, je pravda že NC u jednoho závodu vs u víceetapováho závodu je něco jiného
přemýšlel jsem jak zjednodušit UI

**Comment by fvacek** [comment]
> Přijde mi zbytečný. Navíc se kolečkem myši nebo šipkama číslo mění, což u čipu asi nebude usecase a může to vést jen ke zbytečným chybám.

je to nejjednodussi zpusob, jak zabranit uzivateli psat tam text

> Taky jsem si pohrával s myšlenkou dát checkbox na půjčený čip přímo vedle čipu a vizuálně nechci mít vedle checkboxu ještě spin.

cip muze byt pujcovan v ruznych etapach ruzne.

**Comment by otahirs** [comment]
byl by to spíš checkbox na způsob `add this card to rent table` 

dle mého přijemná fce pro pořadatele, na vícedeních závodech se buďto může taky použít, nebo se dá v klidu ignorovat :innocent:

**Comment by fvacek** [comment]
> byl by to spíš checkbox na způsob `add this card to rent table`
> 
> dle mého přijemná fce pro pořadatele, na vícedeních závodech se buďto může taky použít, nebo se dá v klidu ignorovat innocent

vsechny tyhle fancy veci musi nekdo naprogramovat a udrzovat. Ja jsem si jistej, ze pokud QE bude feature-rich, nebudu schopnej ho udrzovat. Rozhodl jsem se naprogramovat 20% kodu, ktery udela 80% poradani zavodu, nikdy jsem nemel ambice to dotahnout do techto koncu, nemam na to cas ani me to extra nebavi :)

**Comment by otahirs** [comment]
já hlavně sonduju jaká je nálada, abych se desítky hodin netrápil s fancy věcičkou a pak ztrávený čas v C++ a pochopením kódu který jsem nepsal nepřišel vniveč při zamítnutí merge requestu.

Takto si to můžu odškrtat:
* checkbox `find competitors` zrušit
* spinbox zrušit, povolena jen čísla
* checbox `add to rent table` si můžu zkusit lajznout
* na disky nešahat

...a časem třeba něco upravit

**Comment by fvacek** [comment]
ten seznam je v poho.

Nalada se vetsinou zjistuje tim, ze se zalozi issue a kdyz projde diskuzi a ukaze se, ze je to fakt uzitecny nebo fakt potreba, prichazi implementace. Zacinat merge requestem je vzdycky risky.
