### ISSUE TITLE
QE 2.3.2 won't import old .qbe

### ISSUE THREAD

**Issue by jmacura** [Quick-Event/quickbox#534]
### Steps to reproduce
1. open QuickEvent 2.3.2
2. in "Choose database" dialog, choose .qbe file created in QE 2.2.4
3. first error occurs
![image](https://user-images.githubusercontent.com/5598693/76558050-e81b4b00-649c-11ea-87b7-ee2895a2772b.png)
4. go to "File->Import->Event (.qbe)" as described in the error message
5. choose the very same file
6. accept proposed ID of the imported event
7. accept "Open imported event 'pokus123_2'
8. here the error message comes again
![image](https://user-images.githubusercontent.com/5598693/76558229-3597b800-649d-11ea-8f2d-a2d767b39da8.png)

### Configuration
QE Version: 2.3.3-testing
Operating System: Win10 Pro 1903

### Attachments

[pokus123.zip](https://github.com/Quick-Event/quickbox/files/4326008/pokus123.zip)
[quickevent.log](https://github.com/Quick-Event/quickbox/files/4326026/quickevent.log)

**Comment by otahirs** [comment]
I tried to reproduce it on windows with versions 2.3.2 and attached file. From step 1 to 7 everything ok. No other error afterwards.

Cannot reproduce.

**Comment by paukert** [comment]
Tohle mi připomíná issue #518, podle logu to opět nenačetlo pluginy. Nehledá to náhodou knihovny někde jinde?

**Comment by fvacek** [comment]
v mym pripade to udela toto:

<img width="287" alt="image" src="https://user-images.githubusercontent.com/4949019/76708414-e9e04b00-66f6-11ea-9d07-c0ff040c86ea.png">

takze si myslim, ze @paukert ma pravdu, neni to problem s importem, jeste se podivam do logu.

**Comment by fvacek** [comment]
> 2020-03-12T20:01:13.221[pluginloader.cpp:40]|E|  "file:///C:/Program Files (x86)/QuickEvent/qml/quickevent/CardReader/qmldir:-1 plugin cannot be loaded for module \"CardReader\": Cannot load library C:\\Program Files (x86)\\QuickEvent\\qml\\quickevent\\CardReaderplugin.dll: Uvedená procedura nebyla nalezena.\n"

jasny, vubec se nenahraly pluginy, ted je potreba zjistit proc. Jako prvni pokus bych zkusil nainstalovat QE do adresare bez mezer, napr. `C:\\qe`, nerikam ze to pomuze, ale zkusil bych to. Pokud QE nebezi z `Program Files`, je to chyba.

**Comment by jmacura** [comment]
Chyba byla někde jinde, nejspíš při upgrade na vyšší verzi QE.
Jako první jsem zkusil QE odinstalovat a znovu nainstalovat do stejné složky.
Po spuštění a otevření stejného souboru stále vyskočí hláška ad 3), ale po kroku 7) se vše naimportuje správně.
Takže se omlouvám za falešné hlášení a issue zavírám.
