### ISSUE TITLE
 edit competitor dialog - "COMMIT transaction error"

### ISSUE THREAD

**Issue by otahirs** [Quick-Event/quickbox#537]
commit 74fae9d45a1c194714433ec52baf5df6c1fdf597 způsobuje Error při uložení dialogu `edit competitor`

`
transaction.cpp:33]|E|  COMMIT transaction error - "cannot commit - no transaction is active Unable to commit transaction"
`

---
Před ním je vše vpořádku, po něm se začne vypisovat error. 
ps: při testování od kdy se vyskytuje byl potřeba clean build

**Comment by paukert** [comment]
viz https://github.com/Quick-Event/quickbox/issues/478#issuecomment-572538132
