### ISSUE TITLE
import rankingu z orisu

### ISSUE THREAD

**Issue by otahirs** [Quick-Event/quickbox#540]
Současně je možné importovat ranking jen pomocí csv souboru, přitom lze stáhnout nejnovější ranking z orisu přímo pomocí odkazu: 
`https://oris.orientacnisporty.cz/ranking_export?sport=1&csv=1&gender=M`

**1. je problém, že se stahuje jen ranking nejnovější nebo je někdy potřeba i ranking ze staršího data?**
**2. nebylo by lepší ukládat ranking v registracích, případně v samostatné tabulce?** nyní je ranking uložen v competitors, tedy pokud přidám nového závodníka, tak ranking mít nebude
2.a a ukládat tedy nejen pořadí ale i hodnotu rankingu
**3. má vůbec cenu ranking více řešit, nebo se při pořádání nevyužívá?** :)  dokážu si představit, že by ovlivňoval tvorbu startovky, ale nevím jak se dle pravidel může sahat do "náhodného losování"

---
nejnovější ranking jde stáhnout i v xml `https://oris.orientacnisporty.cz/ExportIOF30?agenda=ranking&sport=1&gender=M`. pak je tam i datum, ale formát trochu hapruje (viz dvakrát `<ValidFromDate>`) a  import na csv už je napsany

```xml
<?xml version="1.0" encoding="utf-8"?>
<RankList>
	<IOFVersion version="2.0.3"/>
	<Name>Czech ranking list</Name>
	<Competitor>
		<Person sex="M">
			<PersonName>
				<Family>Nykodým</Family>
				<Given sequence="1">Miloš</Given>
			</PersonName>
			<PersonId type="nat">7019</PersonId>
		</Person>
		<Club>
			<ClubId type="nat">205</ClubId>
			<ShortName>SK Žabovřesky Brno</ShortName>
			<CountryId value="CZE"/>
		</Club>
		<Rank>
			<Name>Czech ranking list</Name>
			<RankPosition>1</RankPosition>
			<RankValue>10000</RankValue>
			<ValidFromDate>
				<ValidFromDate dateFormat="YYYY-MM-DD">2020-03-31</ValidFromDate>
			</ValidFromDate>
		</Rank>
	</Competitor>
        ...
        <Competitor>
       ...
        </Competitor>
<RankList>
```

**Comment by arnost00** [comment]
Mam poznamku pouze k bodu 1 - Pro poradani MCR se vyuzije 2x ranking. Jeden pro prihlasovani, druhy pro losovani semifinale. Oba jsou definovany k nejakemu datu. Ani jednou nepouzijes ten posledni.

**Comment by otahirs** [comment]
`blocked` dokud oris API neumožní získat seznam, pro která data je k dispozici ranking

**Comment by fvacek** [comment]
Dale se pouziva na zavodech, kde je omezen pocet prihlasenych v kategoriich, pak se umisteni v rankingu pouziva jako klic.

**Comment by fvacek** [comment]
samozrejme, ze by ranking mohl mit samostatnou tabulku, ale take nemusel, neprinese nam to zadnou vyraznou vyhodu, protoze se pouziva pri losovani, takze si ho staci stahnout v den losovani.
