### ISSUE TITLE
Popletené časy (o 12 hodin) při zobrazení mezičasy

### ISSUE THREAD

**Issue by OndrejSpanel** [Quick-Event/quickbox#543]
Verze 2.3.4:

Testuji tu vyčítání čipů v rámci přípravy tréninku. Když si dám ukázat data čipu, vypadá to rozumně:

![image](https://user-images.githubusercontent.com/6927223/84246410-e34f4d00-ab06-11ea-8b9b-35bb5b8033c1.png)

Když ovšem nechám ukázat mezičasy, najednou jsou časy 22:00 místo 10:00:

![image](https://user-images.githubusercontent.com/6927223/84246611-25788e80-ab07-11ea-9780-6d60fc5d8e2f.png)

Časy přímo v QE vidím takto:

![image](https://user-images.githubusercontent.com/6927223/84247001-bd767800-ab07-11ea-842f-1038443c30d9.png)

Tedy cíl 240.38 odpovídá 18:00 + 240 min. = 22:00.

Nejspíš to bude souviset s tím, že jako čas startu závodu jsem zadal 18:00 a testování jsem dělal v 10:00 předtím. Jakmile jsem čas startu etapy přestavil na 10:00 a nechal řádek přepočítat, už tam bylo 10:00.

**Comment by fvacek** [comment]
SI maji 12-ti hodinovy cas, QE to do 24 hodin doplnuje podle casu startu. Ukazka dat cipu pouziva 12-ti hodinovy cas z cipu, takze je to podle me v poradku.
