### ISSUE TITLE
Přepočítat časy ve vybraných řádcích - COMMIT transaction error 

### ISSUE THREAD

**Issue by OndrejSpanel** [Quick-Event/quickbox#545]
Verze 2.3.4:

Když dám "Přepočítat časy ve vybraných řádcích", dostávám reprodukovatelně následující chybu:

```text
Error	default	COMMIT transaction error - "cannot commit - no transaction is active Unable to commit transaction"	2020-06-10T11:09:37	transaction.cpp	33	void qf::core::sql::Transaction::commit()	
```

**Comment by fvacek** [comment]
muzes to prosim otestovat i ve 2.3.5, myslim, ze jsem to tam opravoval

**Comment by OndrejSpanel** [comment]
2.3.5 v Releases nevidím.

**Comment by paukert** [comment]
Udělal jsem si dev build z masteru a zdá se, že to opravené ještě není.

**Comment by fvacek** [comment]
ja jsem to take zkousel a nepodarilo se mi to zreprodukovat, co jsi presne udelal?

**Comment by paukert** [comment]
jen Card reader -> Pravým tlačítkem na nějaké vyčtení -> Recalculate times in selected rows

**Comment by fvacek** [comment]
fixed in 2.3.6
