### ISSUE TITLE
Kapacita SIAC čipu při vyčtení

### ISSUE THREAD

**Issue by MirekKalina** [Quick-Event/quickbox#546]
Z návodu SPORTIDENT jsem pochopil, že kapacita SIAC čipu je jedním z údajů, který lze získat při vyčtení čipu po závodě a tento údaj tedy může být vytištěn na papírku s mezičasy - bylo by možné tuto funkci v QUICKEVENT umožnit?

**Comment by paukert** [comment]
V současné době si QE informaci o stavu baterie již načítá a zobrazuje ji minimálně v logu. Nicméně v době implementace nebylo úplně jasné, jak to všechno funguje (viz #363), a proto se tato informace pravděpodobně neobjevila také na mezičasech.

**Comment by MirekKalina** [comment]
Byla by tedy nějaká možnost dostat to na tištěné mezičasy? Nejsem programátor, jen uživatel, tak si nedokážu představit, jak moc to je složité ...

**Comment by fvacek** [comment]
Problem je, ze nevime, ktery udaj v datech znamena zbyvajici kapacitu baterie. SportIdent nechce tyto informace uz poskytovat a preferuje pouziti jejich knihovny, ktera je ale napsana v C#, coz ji cini pro C++ aplikaci nepouzitelnou. Pokud by toto dokazal nekdo zjistit, neni problem to tisknout na vycetku.

**Comment by paukert** [comment]
Zkusil jsem poslat dotaz, uvidíme, jestli nám něco prozradí.

Může se zavřít, dořešíme případně v #363.

**Comment by paukert** [comment]
Můžeme zavřít, duplicitní issue k #363
