### ISSUE TITLE
Zobrazit čas uplynulý od uzavření kategorie

### ISSUE THREAD

**Issue by janpalas** [Quick-Event/quickbox#552]
Ve statistikách závodu se nyní zobrazuje čas do uzavření kategorie. Jakmile vyprší, vidím už jen `0.00` a nepoznám, jestli se kategorie uzavřela před minutou nebo před hodinou. Pokud mám cíl vzdálen od vyčítání, není tento údaj úplně relevantní - potřebuju si k tomu času připočíst nějakou dobu, kterou jdou závodníci z cíle.

Z toho důvodu by se hodilo, aby bylo vidět, před jakou dobou se kategorie uzavřela (aby se např. mohly začít psát diplomy, spustit vyhlášení, atp.).

Nepřidával bych pro to další sloupec do okna Statistiky závodu, ale v současném sloupci Čas do uzavření bych zobrazoval záporné hodnoty. Tzn. `10.00` = kategorie se uzavře za 10 minut, `-15.00` = kategorie se uzavřela před 15 minutami.

**Comment by otahirs** [comment]
pokud by se zobrazovaly záporné hodnoty, pole bych možná podbarvil aby bylo ihned zřejmé, že je už doběhnuto
