### ISSUE TITLE
Verze 2.3.7 - Windows 10

### ISSUE THREAD

**Issue by ikanakova** [Quick-Event/quickbox#553]
Quick Event ver. 2.3.7 úspěšně nainstalována ve Windows 10. Zkoušeli jsme testovací závod štafet a nevyskytl se problém.

**Comment by fvacek** [comment]
> Ahoj, v instalačce mi chybí možnost zvolit si vlastní umístění, kam program nainstalovat (nainstaluje se do stejného adresáře, kde byla minulá instalovaná verze).
> (v 2.3.7, Windows 10)

tohle je vlastnost InnoSetupu, nevim, jak se tohle dela, asi je potreba nejdriv odinstalovat starou verzi, jinak to bere jako update

**Comment by fvacek** [comment]
> Quick Event ver. 2.3.7 úspěšně nainstalována ve Windows 10. Zkoušeli jsme testovací závod štafet a nevyskytl se problém.

diky za testovani :+1:  :)

**Comment by ikanakova** [comment]
> tohle je vlastnost InnoSetupu, nevim, jak se tohle dela, asi je potreba nejdriv odinstalovat starou verzi, jinak to bere jako update

Potvrzuji - nejprve jsem odinstalovala starou verzi a při instalaci nové verze jsem mohla vybrat vlastní umístění.

**Comment by paukert** [comment]
Jak je psáno výše - tohle bude způsobeno defaultní hodnotou parametru `DisableDirPage=auto` ([link](https://jrsoftware.org/ishelp/index.php?topic=setup_disabledirpage))

> If this is set to auto, at startup Setup will look in the registry to see if the same application is already installed, and if so, it will not show the Select Destination Location wizard page.

**Comment by fvacek** [comment]
jestli je to matouci, muzeme ho dat na `no`

**Comment by paukert** [comment]
Pokud by případné dvě instalace na jednom zařízení fungovaly obě korektně (registry?, něco dalšího?), tak by se to mohlo změnit. V opačném případě bych to nechal na `auto`.

Má ale nějaký důvod mít dvě různé instalace QE na jednom počítači? Mě napadá asi jen situace, kdy člověk pořádá závody na nové verzi QE a v záloze by chtěl mít rovnou nainstalovanou nějakou odzkoušenou verzi.

**Comment by fvacek** [comment]
pokud bude na jednom pocitaci vice instalaci QE, budou mit ulozene stejne nastaveni, coz povetsinou nevadi, nenapada me, kdy by to vadit mohlo. Priklanim se k `no`, sice to bude znamenat jeden klik navic, ale zase se nikdo nebude divit.

**Comment by zvondic** [comment]
U mne problém.

![image](https://user-images.githubusercontent.com/5123917/91712405-f44caf00-eb87-11ea-9edb-a12a54b7731e.png)

![image](https://user-images.githubusercontent.com/5123917/91712485-1e9e6c80-eb88-11ea-8de0-9d8968d13493.png)

**Comment by Pjootr** [comment]
řešení je -> https://github.com/Quick-Event/quickbox/issues/456
stáhnout a nakopírovat knihovny do adresáře QuickEventu viz. https://github.com/Quick-Event/quickbox/issues/456#issuecomment-540132840

**Comment by zvondic** [comment]
dík. Začalo fungovat.
