### ISSUE TITLE
cannot build on windows

### ISSUE THREAD

**Issue by otahirs** [Quick-Event/quickbox#564]
https://github.com/Quick-Event/quickbox/blob/d72c877407466371852be7058ceffa97218efb1f/datafiles.pri#L19-L28

this recent edit breaks the build process for me on windows
the `-p` argument and `cp` command are not supported in windows, at least by default

on the other hand the commented `xcopy` works for me on W10, mingw

---
edit:
>  I simply uncommented line 26 and commented line 27, xcopy works fine for me

same

**Comment by paukert** [comment]
I faced same issue, I simply uncommented line 26 and commented line 27, xcopy works fine for me

W10, version 2004, compiler MinGW

**Comment by fvacek** [comment]
we need to keep both
* windows QTC build is using `cmd` with `xcopy`
* gitlab CI runner is using `bash` where `xcopy` also exists but with very different behavior. 

I suggest to introduce `windows_build_shell_bash` config variable to enable using of `bash` even in windows builds

**Comment by otahirs** [comment]
I would suggest `(xcopy command) || (bash commands)`
If first ends with an error, the second is executed.

**Comment by otahirs** [comment]
Are we talking about `Github actions` or `gitlab runner`?
[In github actions you can specify to run the command with `cmd`](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#example-running-a-script-using-windows-cmd)

**Comment by fvacek** [comment]
we are talking about `gitlab runner`, if you can move QE builds to `github actions`, then we can close this issue :)
