### ISSUE TITLE
Při testování jsem narazil na pár věcí:

### ISSUE THREAD

**Issue by fvacek** [Quick-Event/quickbox#566]
Při testování jsem narazil na pár věcí:

1. Pokud si po spuštění vyberu úložiště dat (SQL server / Single file), potom kliknu na cancel u následujícího dialogu, kde si můžu vybrat z dostupných závodů, tak následně volba File --> Event --> Open event není aktivní
2. Pokud si po spuštění vyberu úložiště dat (SQL server / Single file), potom kliknu na cancel u následujícího dialogu, kde si můžu vybrat z dostupných závodů, tak jsou následně povolené importy textových souborů (File --> Import --> Text file) + synchronizace přihlášek a stažení klubů a registrací, ale nic z toho bych asi neřešil, protože ve všech modulech jsou nabídky také aktivní a jedná se o edge case
3. Pokud jsem připojen k nějaké DB, potom dám File --> Connect to database --> Single file --> u dalšího dialogu cancel, tak podle captionu u okna QE to vypadá, že je původní závod stále aktivní, ale ve skutečnosti je spojení ztraceno

_Originally posted by @paukert in https://github.com/Quick-Event/quickbox/issues/487#issuecomment-685561581_

**Comment by otahirs** [comment]
>   - [x]    Pokud si po spuštění vyberu úložiště dat (SQL server / Single file), potom kliknu na cancel u následujícího dialogu, kde si můžu vybrat z dostupných závodů, tak následně volba File --> Event --> Open event není aktivní

> - [ ]     Pokud si po spuštění vyberu úložiště dat (SQL server / Single file), potom kliknu na cancel u následujícího dialogu, kde si můžu vybrat z dostupných závodů, tak jsou následně povolené importy textových souborů (File --> Import --> Text file) + synchronizace přihlášek a stažení klubů a registrací, ale nic z toho bych asi neřešil, protože ve všech modulech jsou nabídky také aktivní a jedná se o edge case

> - [x]     Pokud jsem připojen k nějaké DB, potom dám File --> Connect to database --> Single file --> u dalšího dialogu cancel, tak podle captionu u okna QE to vypadá, že je původní závod stále aktivní, ale ve skutečnosti je spojení ztraceno

#566
