### ISSUE TITLE
Nemělo by být možné přiřadit čip závodníkovi, který má nastaveno `running==false`

### ISSUE THREAD

**Issue by fvacek** [Quick-Event/quickbox#574]
> Zajímavé je, jak se pak QE choval: Po vyčtení příslušného závodníka to řvalo, že takový čip v závodě není. Logicky jsme kontrolovali číslo čipu v "Závodníci" a to kupodivu sedělo. Zajímavé, že funkce "Přiřadit čip závodníkovi" tisk správných mezičasů vyvolala. Když jsme pak ale v klidu vyvěsili výsledky závodů na ORIS, volal nám dotyčný, že tam prostě chybí. Doma jsem zjistil, že příslušnému závodníkovi "chybí" záznam v "Úseky / Etapy" (nenapadlo mě, že jsme si ho sami "vypnuli"). Proto tam nešel ani standardně znovu přidat a musel jsem situaci řešit tak, že jsem celého závodníka smazal a následně znovu vložil, zadal mu do etapy stejný startovací čas jako měl předtím. znovu na příslušném vyčítacím záznamu aktivoval funkci "Přiřadit čip závodníkovi" a znovu exportoval výstup pro ORIS z QE.

Tady mě napadá, že by možná nemělo být možné přiřadit čip závodníkovi, který má nastaveno `running==false`

_Originally posted by @paukert in https://github.com/Quick-Event/quickbox/issues/571#issuecomment-688399623_

**Comment by otahirs** [comment]
Dnes jsme u oblže narazili na stejný problém.
Na prezentaci jsme odhlasili závodnici (offrace). 
Nakonec však běžela.
U vyčítání nebyl přiřazen čip, tak jsem ho klasicky přes dialog assignul.
Ve výsledcích nebyla a hledali jsme co se stalo.

**Comment by fvacek** [comment]
Co kdybychom prirazenim cipu vymazali priznak `off-race`, pripadne s nejakym dialogem, ktery vysvetli poradateli, co se to vlastne stalo?
