### ISSUE TITLE
Přiřadit čip - použít SI i v dalších etapách

### ISSUE THREAD

**Issue by vojky** [Quick-Event/quickbox#576]
I přesto, že je závod jednoetapový je umožněno zaškrtnout možnost Použít tento SI i v následujících etapách (Use this SI card in next stages). Pokud se toto zaškrtne, dojde k pádu celého programu.

QE 2.3.7, Windows 10

**Comment by paukert** [comment]
Ve verzi 2.3.7 je chyba v syntaxy SQL dotazu, už je opravena díky #570. Na dev buildu mi to už nepadá.

Je pravda, že by při jednoetapovém závodě možnost `Use this SI card in next stages` asi nemusela být vůbec viditelná.

**Comment by fvacek** [comment]
Vydal jsem 2.3.8, tam je to opraveno
