### ISSUE TITLE
Chyba pri vytvareni databaze: Parametr count mismatch

### ISSUE THREAD

**Issue by lme6300** [Quick-Event/quickbox#582]
Nainstaloval jsem si novou verzi 2.3.8, posleze pak i 2.3.7. Ani v jedne se mi nepodarilo vytvorit novy zavod importem z Orisu. Po zadani ID zavodu v Orisu a naslednem doplneni ID zavodu v dialogu "Formular" se po OK objevi chybova hlaska "Chyba pri vytvareni databaze: Parametr count mismatch". Co delam spatne? Zalozi se v urcenem adresari soubor pozadovaneho jmena, ale je velikosti 0.

**Comment by lme6300** [comment]
Pokus o rucni zalozeni zavodu konci (ncekane :-) ) stejnou chybou.

**Comment by otahirs** [comment]
Windows?
Doporučil bych zkusit čistou instalaci 
   => odinstalovat současnou verzi quickeventu => pokud něco zbylo ve složce QuickEvent, tak zmazat => nainstalovat znovu

**Comment by lme6300** [comment]
Ano, Windows. Odinstalovat a znovu nainstalovat pomohlo. Ach jo ..... Dekuji za radu.

**Comment by fvacek** [comment]
Stejne by se to dit nemelo, nahodou se screen-shot te chyby nebo aplikacni log nezachoval?

**Comment by lme6300** [comment]
Nemelo, to je pravda :-) Log nemam. Muzu zkusit upgrade na posledni verzi, co to udela...
