### ISSUE TITLE
Export výsledků XML Družstva

### ISSUE THREAD

**Issue by yettisoft** [Quick-Event/quickbox#588]
O víkendu 26.-28.9.  jsme pořádali MTBO závody. (Long, Sprint, Middle, Družstva) Celé jsme to jeli v QE. Až na pár nějakých drobností to bylo super.

Mám trochu trable s nahrání výsledků Družstev na ORIS.
Resp. XML má chybku 😊
V tagu OverallResult /Time je místo času je tam zapsané jméno.

Výsledky jsou na ORISU nahrané bez celkových časů a pořád někdo doráží, abych to opravil.
Nechce se mi celé XML editovat ručně.

Díky Jirka Žucha

**Comment by arnost00** [comment]
Jestli si buildujes QE tak : 
quickevent\app\plugins\Relays\src\relayswidget.cpp
Ln. 750 nahrad nasledujicim radkem :
append_list(overall_result, QVariantList{"Time", tt_leg_row.value(QStringLiteral("stime")).toInt() / 1000});

Je tam chyba v zavorkach (nedeli se tisicem cas, ale index pole)

Opravu zkusim commitnout jeste dnes.

**Comment by paukert** [comment]
@yettisoft můžeš si zkusit stáhnout instalační soubor, který se vytváří automaticky tady na GitHubu. Pokud vše funguje správně, tak to v něm bude už opravené :)

https://github.com/Quick-Event/quickbox/actions/runs/291335975

**Comment by fvacek** [comment]
@arnost00 diky za promptni opravu :+1:

**Comment by yettisoft** [comment]
Díky moc
