### ISSUE TITLE
French localisation

### ISSUE THREAD

**Issue by fvacek** [Quick-Event/quickbox#597]
nejak se s tim roztrhl pytel :)

**Comment by fvacek** [comment]
https://hosted.weblate.org/projects/quickbox/translations/fr/

**Comment by paukert** [comment]
IMO to budou asi nějací nadšenci, kteří pomáhají překládat projekty na weblate, PR #598

**Comment by arnost00** [comment]
@fvacek Mas nejake informace o tom ze by QE nekdo mimo CR aktivne pouzival ? Ze by treba mohli mit nejake zajimave podnety zvenci.

**Comment by fvacek** [comment]
Nemam, jenom cas od casu se nekdo prihlasi, ze by to chtel zlokalizovat. zatim mame tyto jazyky https://hosted.weblate.org/projects/quickbox/translations/
