### ISSUE TITLE
Jako neprihlaseny do githubu si nemuzu stahovat posledni buildy

### ISSUE THREAD

**Issue by xkenia** [Quick-Event/quickbox#607]
Pokud se pokusim si stahnout posledni build a nejsem na githubu prihlaseny, tak mi to hodi 404.

Napr. QuickBox -> Actions -> Build -> quickevent-2.3.9-win64-setup.exe = https://github.com/Quick-Event/quickbox/suites/2010919198/artifacts/40246423

**Comment by fvacek** [comment]
S tímhle asi nic neuděláme. Ale jsou to dev build, takže je ta nutnost loginu spíš v pořádku, jinak hrozí, že někdo uspořádá závody na nefunkční SW. Spíš to chce asi dělat release častěji.

**Comment by janzhanal** [comment]
Tez mi to neprijde uplne zasadni, stejne kdyz reportujes chybu, ke ktere ocekavas co nejrychlejsi opravu, tak uz ten login mas...
