### ISSUE TITLE
Nelze instalovat nové verze programu z Actions

### ISSUE THREAD

**Issue by ikanakova** [Quick-Event/quickbox#609]
Nové verze Quickevent (quickevent-2.3.9-win64-setup.exe) stažené z Actions (např. [#743919716](https://github.com/Quick-Event/quickbox/actions/runs/743919716)) nelze spustit - vyskakuje chyba: Kód nelze spustit, protože se nenašel necrolog.dll:
![necrolog](https://user-images.githubusercontent.com/38765251/116816639-12c5d880-ab63-11eb-98a3-0faba5dd47b2.png)
Verze z Releases funguje zcela normálně.

**Comment by arnost00** [comment]
Je mozny ze chybi necrolog.dll v quickevent.iss ?
V Releases to vypada ze je jeste verze pred pridanim necrolog

**Comment by arnost00** [comment]
V testovacim buildu uz to je ([#804837145](https://github.com/arnost00/quickbox/actions/runs/804837145))

**Comment by fvacek** [comment]
Diky Arnoste :+1:
