### ISSUE TITLE
Add validator for event ID

### ISSUE THREAD

**Issue by fvacek** [Quick-Event/quickbox#613]
Postgres schema must match following regex `[a-z][a-z0-9_]*`
@Nechanicky

**Comment by fvacek** [comment]
done already d65910468761afbe3f1ed4672b3bdb3c5d9c70d2

**Comment by Nechanicky** [comment]
Super, díky.

Jinak mi Kenia ukázal, jak se z QE dají data rychle posílat na LiveResultat. 

Je to fakt na 5 minut i s vytvořením závodu. 

Ještě jednou díky za pomoc.

Měj se

Pavel

 

 

From: Fanda Vacek ***@***.***> 
Sent: Sunday, June 6, 2021 7:16 PM
To: Quick-Event/quickbox ***@***.***>
Cc: Nechanicky ***@***.***>; Mention ***@***.***>
Subject: [Quick-Event/quickbox] Add validator for event ID (#613)

 

Postgres schema must match following regex [a-z][a-z0-9_]*
@Nechanicky <https://github.com/Nechanicky>
