### ISSUE TITLE
Invalid control code S

### ISSUE THREAD

**Issue by OndrejSpanel** [Quick-Event/quickbox#615]
Při importu z OCAD IOF XML 3.0 jsem dostal chybu:

> Invalid control code 'S'

V xml souboru je kontrola popsána takto:

```xml
    <Control>
      <Id>S</Id>
      <Position lng="14.262938" lat="49.861691" />
      <MapPosition x="3.2" y="5.1" unit="mm" />
    </Control>
```

a

```xml
      <CourseControl type="Start">
        <Control>S</Control>
      </CourseControl>
```

Ve zdrojácích jsem našel odpovídající regex:

```c++
const static QRegularExpression rx_start(R"RX(S[A-Za-z]*([1-9][0-9]*))RX");
```

Timto regexem opravdu S neprojde, chybí část `[1-9]`. Když jsem v XML nahradil všechny výskyty slova `S` za `S1`, prošlo to bez potíží.

Možná, že se z OCADu dá při exportu nějak nastavit, aby byl start označen jako S1, ale S taky nevypadá nesmyslně. Zdá se, že by neměl být problém S chápat jako S1?

**Comment by otahirs** [comment]
@OndrejSpanel nahraješ sem prosím oba xml soubory, jak ten co háže chybu, tak ten co chodí normálně, ať je při opravě co testovat
