### ISSUE TITLE
wrong equality operator in SQL querry

### ISSUE THREAD

**Issue by otahirs** [Quick-Event/quickbox#632]
`==` > `=`

got through SQLite, PostreSQL throws error

https://github.com/Quick-Event/quickbox/blob/34f17c3f1994c99ce2d30909a0093386cd8e0a2f/quickevent/app/plugins/Runs/src/eventstatisticswidget.cpp#L137

**Comment by paukert** [comment]
Is there some problem with single `=` in QE?

According to PostgreSQL and SQLite docs, it should be sufficient `CASE WHEN COUNT(timeMs) = 3 THEN MAX(timeMs) ELSE NULL END`

**Comment by otahirs** [comment]
There should be a single =, this is the issue

Dne so 26. 6. 2021 11:02 uživatel Lukáš Paukert ***@***.***>
napsal:

**Comment by paukert** [comment]
> There should be a single =, this is the issue

I get it now, sorry
