### ISSUE TITLE
Přepisování výsledků při několikanásobném vyčtení

### ISSUE THREAD

**Issue by horakmar** [Quick-Event/quickbox#636]
Není to chyba, spíš ne zcela bezpečná vlastnost.
Při následném vyčtení stejného čipu se přepíšou dříve vyčtená data. Problém se z toho stane v případě víceetapového závodu, kdy obsluha programu zapomene přepnout aktuální etapu. Čip s daty z druhé etapy pak tiše přepíše původní výsledky.

Návrh na vylepšení (feature request):
  - Volitelná možnost upozorňovat na přepsání již vyčtených dat.

**Comment by fvacek** [comment]
bojim se, ze z toho bude pekna otrava pri jednoetapovych zavodech, zajimal by me nazor @otahirs a @paukert

**Comment by fvacek** [comment]
jinak souhlasim s tim, ze pri poradani viceetapovych zavodu toto nebezpeci hrozi, ale upozorneni by melo prijit driv, omylem se daji poskodit i startovni casy, proto jsem prepinani aktualni etapy udelal tak pitome, aby to neslo omylem prepnout jako treba kategorii.

Ja bych se spis priklanel k tomu, ze by QE mel nekde **vyrazne cervene** psat, ze nesouhlasi datum v pocitaci a v etape

**Comment by horakmar** [comment]
V našem případě by porovnání datumu nepomohlo - pořádali jsme dvě etapy v jednom dnu.
Nápady jak zajistit, aby upozornění na přepis neobtěžovalo:
  - možnost upozornění zapnout/vypnout na úrovni voleb celé aplikace
  - porovnat zda přepisem dojde ke změně, pokud jsou časy v čipu stejné, jako ty už uložené (když si někdo dojde pro nový lístek), tak nic nehlásit

**Comment by paukert** [comment]
> Ja bych se spis priklanel k tomu, ze by QE mel nekde vyrazne cervene psat, ze nesouhlasi datum v pocitaci a v etape

Nějaké upozornění v tomhle stylu mi přijde jako dobrý nápad, ale samozřejmě to neodchytí případné problémy se 2 závody v jednom dni, jak už tu bylo zmíněno.

Pokud by se nějaké další upozornění implementovalo způsobem, jaký zde zmiňuje @horakmar, tak by to IMO bylo asi také bez problému :)

**Comment by otahirs** [comment]
možnost vypnout/zapnout bych vynechal, snažil bych se najít implementaci kdy nebude potřeba.

změnil bych návrh kontroly na:
* již běží další etapa (dle startu), ale na vyčátání je vybraná některá předchozí 
* porovnat zda přepisem dojde ke změně

---
ps: nepořádal jsem víceetapové závody, takže nevím jaký je pořadatelský flow, ale nebylo by přecijenom lepší mít jeden globální přepínač vybrané etapy, aby jsem si např. v runs nepřepnul již na aktuální, ale u vyčítání se zapomněl u předchozí? globální vždy viditelný přepínač by takovéto přešlapy vyřešil.

**Comment by fvacek** [comment]
* globalni prepinac tam prave je, ale to nestaci, pokud si ho nekdo spatne nastavi, nebo pokud se poradaji 2 etapy soucasne
* kontrola, ze doslo ke zmene je na nic, protoze prave proto se znovu vycita, takze to bude nicit poradatele jednoetapovych zavodu
* konfigurovatelna kontrola by mohla fungovat, pokud by o tom poradatele vedeli. Reseni nechat ji defaultne zapnutou s checkboxem `do not show again` nebude fungovat, protoze neni kam bezrozporne ulozit ten bit informace `do not show again`
  * ulozime-li ho do databaze, budou si uzivatele navzajem prepisovat toto nastaveni pri pouziti vice klientu
  * ulozime-li ho do local settings, ulozi se pro vsechny budouci zavody
* zda se mi, ze vsechno za nas pocitace nevyresi

**Comment by horakmar** [comment]
Mně, jako pořadateli většinou jednoetapových a výjimečně víceetapových závodů by úplně stačil globální přepínač v local settings.
Je možné pořádat dvě etapy **současně**? Tedy mít nastaveno na dvou instancích Quickeventu na každé jinou aktuální etapu? Myslel jsem, že ID aktuální etapy je uložené v config tabulce DB závodu a ta je jen jedna.

Možná by to chtělo rozebrat otázku proč se znova vyčítá již vyčtený čip:
1) Závodník chce aktuální lísteček
2) Omylem, třeba hromadně jiným členem oddílu
3) Závodník přiběhl z následující etapy
4) Se stejným čipem běžel jiný závodník

Nenapadá mě další důvod.
Všechny případy podle mě pěkně řeší kontrola, zda vyčtením dochází ke změně dat.

**Comment by fvacek** [comment]
socasne jsem myslel v jeden den :)

> Závodník chce aktuální lísteček

tak to neni zadny problem a zadn varovani neni potreba

>    Omylem, třeba hromadně jiným členem oddílu

tak to neni zadny problem a zadn varovani neni potreba
  
>  Závodník přiběhl z následující etapy

poradatel ma nastvenou aktualni etapu spatne, kontrolovat to zde mi prijde uz trocho pozde, protoze pred tim mohl bez jakohokoliv varovani prepsat nekomu startovni cas nebo nekoho dohlasit na jinou etapu

>    Se stejným čipem běžel jiný závodník

vetsina poradatelo toto nepodporuje, i kdyz QE ano. Kdyz se toto stane pokusi se QE podle aktualniho casu vymyslet, ktery zavodnik to je, coz se skoro vzdy podari, protoze, aby 2. zavodnik mohl se stejnym cipem vystartovat, musi 1. dorazit do cile a pokud si i vycte, je omyl vyloucen. Pokud QE nedokaze vymyslet, kdo by to mohl byt, zobrazi dialog uz v soucasne implementaci.

Takze porad resime stejny problem, jak zamezit tomu, aby si nekdo nenastavil jine cislo etapy nez kterou porada a znovu musim rict, ze resit toto pri vycitani je uz trochu pozde. Uznavam ze lepsi pozde nez vubec, ja lae porad verim, ze se podari vymyslet, jak kontrolovat chybnou etapu nez prepisovani karty, ktere v pripadech 1,2,3 skonci jenom bezduchym mackanim OK a v pripade 3 je problem jinde.

**Comment by horakmar** [comment]
> 
> 
> socasne jsem myslel v jeden den :)
> 
> > Závodník chce aktuální lísteček
> 
> tak to neni zadny problem a zadne varovani neni potreba

Ano

> 
> > Omylem, třeba hromadně jiným členem oddílu
> 
> tak to neni zadny problem a zadne varovani neni potreba

Ano

> 
> > Závodník přiběhl z následující etapy
> 
> poradatel ma nastvenou aktualni etapu spatne, kontrolovat to zde mi prijde uz trocho pozde, protoze pred tim mohl bez jakohokoliv varovani prepsat nekomu startovni cas nebo nekoho dohlasit na jinou etapu

Muze to byt i tak (nas pripad), ze do druhe etapy uz neprobiha zadna prezentace a nic se neprepisuje (jen ten vysledek :-)).
Varovani by se tu hodilo.

> 
> > Se stejným čipem běžel jiný závodník
> 
> vetsina poradatelo toto nepodporuje, i kdyz QE ano. Kdyz se toto stane pokusi se QE podle aktualniho casu vymyslet, ktery zavodnik to je, coz se skoro vzdy podari, protoze, aby 2. zavodnik mohl se stejnym cipem vystartovat, musi 1. dorazit do cile a pokud si i vycte, je omyl vyloucen. Pokud QE nedokaze vymyslet, kdo by to mohl byt, zobrazi dialog uz v soucasne implementaci.
> 

I zde by se varovani hodilo i v pripade, ze to QE sam vymysli. :-) Ale techto pripadu je minimum.

> Takze porad resime stejny problem, jak zamezit tomu, aby si nekdo nenastavil jine cislo etapy nez kterou porada a znovu musim rict, ze resit toto pri vycitani je uz trochu pozde. Uznavam ze lepsi pozde nez vubec, ja lae porad verim, ze se podari vymyslet, jak kontrolovat chybnou etapu nez prepisovani karty, ktere v pripadech 1,2,3 skonci jenom bezduchym mackanim OK a v pripade 3 je problem jinde.

Pokud by QE varoval pouze pokud dojde novym vyctenim ke zmene jiz ulozenych dat, pokryje to podle me krasne prvni tri pripady.

**Comment by arnost00** [comment]
Otazka : Pokud mam spusteny 2 instance QE nad jednou databazi, a jedna prepne etapu. Co se stane na druhe instanci ?

**Comment by fvacek** [comment]
> Otazka : Pokud mam spusteny 2 instance QE nad jednou databazi, a jedna prepne etapu. Co se stane na druhe instanci ?
> Zmeni se tam etapa taky ? 1. instance to zapise do DB.
> A projevi se to nejak vizualne ?
> Protoze je pak otazka kam vlastne druha instance pri pripadnem vycitani zapisuje.
> 
>     1. instance muze byt treba prezentace / tisk vysledku a 2. instance treba vycitani .
>        Muze to nekdo potvrdit/vyvratit/vyjasnit ?

Pokud na jednom QE prepnes etapu napr. 2->3:
1. do DB se jako current stage ulozi 3
2. ostatni QE nejsou notifikovani o teto zmene, takze pouzivaji dale etapu 2
3. nove spustene instance QE uz najedou s etapou 3

Takze pokud v nejakem QE docasne zmenis etapu, rychle udelas co potrebujes a pak to zase vratis a nikdo mezi tim nespusti dalsi QE, nic se nestane

**Comment by fvacek** [comment]
> Pokud by QE varoval pouze pokud dojde novym vyctenim ke zmene jiz ulozenych dat, pokryje to podle me krasne prvni tri pripady.
Nenapada me totiz pripad, kdy bychom CHTELI novym vyctenim zmenit ulozena data a VADILO by nam upozorneni (= nebyl by to jen ojedinely stav).

Ja k tomu muzi rict porad to same. Toto by urcite QE jako aplikaci prospelo, ale neni to kompletni reseni spatne nastavene aktualni etapy a ja bych rad nasel reseni, ktere varuje i pri editaci startovky nebo vysledku. Kdyz ho najdeme, vyresi se tim i vycitani.

**Comment by Tomaqa** [comment]
Mně se stala nepříjemnost, která se může stát i na jednoetapovém závodě.
Synek se šel z legrace s máminým čipem proběhnout do lesa (jak se dostal přes start nevím) a pak si ještě i vyčetl, čímž pochopitelně přepsal výsledek na DISK. Když si vyčítá víc lidí současně, tak vás skutečnost že je někdo DISK nijak nevytrhne, a když přijde překvapená máma po vyhlášení jaktože nebyla vyhlášená, tak se to zpětně nedohlává snadno :)
Byla to sice chyba závodnice, ale o to nejde.
Dle mého je vícenásobné vyčtení čipu s různými daty (bez ohledu na datum apod.) natolik nestandardní záležitostí (s jednou jedinou výjimkou, viz. níže), že by měla být buď úplně zablokována, nebo explicitně zvýrazněna. Diskuze o chování programu na víceetapových závodech mi proto připadá irelevantní.

> > Se stejným čipem běžel jiný závodník
> 
> vetsina poradatelo toto nepodporuje, i kdyz QE ano. Kdyz se toto stane pokusi se QE podle aktualniho casu vymyslet, ktery zavodnik to je, coz se skoro vzdy podari, protoze, aby 2. zavodnik mohl se stejnym cipem vystartovat, musi 1. dorazit do cile a pokud si i vycte, je omyl vyloucen. Pokud QE nedokaze vymyslet, kdo by to mohl byt, zobrazi dialog uz v soucasne implementaci.
Myslím si že to je jediná výjimka, kdy připadá v úvahu vícenásobné vyčtení čipu s různými daty. Nicméně považoval bych to za výjimečnou situaci, tj. defaultní chování je nepovolit vícenásobné vyčtení, a pouze je-li čip předem nahlášen pro více závodníků, vyčtení povolit. Dialog neřeší situaci, kterou jsem popsal v úvodu.

Dle mého názoru by bylo žádoucí umožnit nastavit mód max. 1 závodníka na čip, zvlášť když >90% domácích závodů takto funguje - to se pak hodí i při prezentaci, kdy může program zařvat při pokusu přiřadit již přiřazený čip.

**Comment by fvacek** [comment]
> Dle mého je vícenásobné vyčtení čipu s různými daty (bez ohledu na datum apod.) natolik nestandardní záležitostí (s jednou jedinou výjimkou, viz. níže), že by měla být buď úplně zablokována, nebo explicitně zvýrazněna. A nejlépe vytisknout lísteček podobný tomu, když není čip znám, protože samotná diskvalifikace nemusí závodníkovi nijak naznačit v čem je problém.
Připadá mi to jako obecný problém, proto mi diskuze o chování programu na víceetapových závodech v tomto kontextu připadá irelevantní.

QE umoznuje bezet vice zavodnikum se stejnym cipem, to zase pouzivaji skoly, ktere maji malo cipu, takze ta diskuze irelevantni neni.

**Comment by Tomaqa** [comment]
> QE umoznuje bezet vice zavodnikum se stejnym cipem, to zase pouzivaji skoly, ktere maji malo cipu, takze ta diskuze irelevantni neni.
Myslím to tak, že jde jen o to, zda jsou různá data (a datum+čas), a to jestli je to závod jednoetapový/víceetapový už by na chování programu nemělo mít vliv.

Když někdo nemá nahlášen čip, při vyčtení automaticky vyjede chyba. Podobné chování bych očekával u vícenásobného vyčtení čipu s různými daty, kdy mám k tomu čipu ve startovce jen jednoho závodníka. Prostě "ten druhý" (zatím nevíme kdo to je), který jde s tím stejným čipem, není nahlášený -> chyba. Pokud je předem nahlášený (tj. v DB je více lidí na jeden čip), pak vše proběhne OK (tj. to co asi děje už teď).

**Comment by Tomaqa** [comment]
Můj problém by to vyřešilo, to je fajn, ale mám pár nejasností:

- co se bude dít, když u toho zrovna nebudu sedět, dohledám pak závodníka snadno? (potřebuju ho ve vyčítání dohledávat?) (pokud ano, zvýraznit ho v seznamu vyčtených nějakou barvou, a-la červená u nepřiřazeného čipu ?)
- co se bude dít, když si takhle vyčte několik lidí po sobě, než stihnu vyřešit toho prvního?
- co se vytiskne závodníkovi, dokud problém nevyřeším?
- existuje vůbec nějaký scénář, kdy by to za těch vypsaných předpokladů *nebyl omyl*? tj. není lepší to na férovku označit jako chybu?

**Comment by fvacek** [comment]
Mozna je na case tento corner-case povysit na neco, co by mohlo prospet aplikaci i jinde. 

Co kdybychom zavedli krome okna s logem jeste dalsi okno, mohlo by se jmenovat treba Alarms nebo Alerts, kam by QE zapisoval vsechny podivnosti, tedy nejen prepsani jiz jednou nactene karty. Na rozdil od aplikacniho logu by se toto ukladalo do databaze a u kazdeho radku by se dalo zaskrtnout, jestli to poradatej uz poresil nebo ne.

**Comment by Tomaqa** [comment]
> Co kdybychom zavedli krome okna s logem jeste dalsi okno ...
+1, jen si nejsem jist zda radeji nezvolit misto okna novou kartu. Sice to neumozni se divat soucasne i na jinou kartu, ale zatim me nenapada k cemu by to bylo potreba. Pripadne by mohl dobre fungovat i widget (~log, statistiky, ...), tam by tento problem odpadl.

**Comment by fvacek** [comment]
> Pripadne by mohl dobre fungovat i widget (~log, statistiky, ...), tam by tento problem odpadl.

to jsem myslel, ze by to byl dalsi docking-widget

**Comment by otahirs** [comment]
> > Oka, pokusim se to shrnout, pokud QE vycte cip,
> > ```
> > 1. pokusi se ho priradit zavodnikovi
> > 
> > 2. pokud zavodnik cip jiz prirazen ma
> > 
> > 3. a prirazovany cip, ma sice stejne cislo, ale jina data
> > 
> > 4. QE zobrazi message box s otazkou, jestli to neni nahodou nejaky omyl
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > co vy na to, muze to tak fungovat?
> 
> Myslím si, že tohle by bylo dobré řešení, jen místo 4. kroku bych jednoduše dané vyčtení označil za "chybu" (stejně jako když je vyčten neznámý čip) - tj. řádek se podbarví červeně, závodníkovi by vyjel lísteček s chybou, vyčítání běží dál, ale obsluha musí dané vyčtení někomu ručně přiřadit = situaci vyřešit (přiřazením "chybného" vyčtení k určitému závodníkovi je vyřešeno --> řádek přichází o červené podbarvení, jako se děje již v současné implementaci).
> 
> Tohle by fungovalo dobře pro případy, kdy je v závodě zadán pouze jeden člověk s daným SI čipem (tj. běží s ním pravděpodobně nějaký druhý závodník a vyčtením by se přepsala data tomu prvnímu), ale i pro případy, kdy je s daným SI nahlášeno více závodníků, logika QE si spočítala, že by toto vyčtení mělo patřit x-tému závodníkovi, ale zároveň by mělo dojít k přepsání dat (x-tý závodník si již vyčetl s jinými daty).

souhlasím s:
1. pokusi se ho priradit zavodnikovi
2. pokud zavodnik cip jiz prirazen ma
3. a prirazovany cip, ma sice stejne cislo, ale jina data 
4. **error, vypsat chybu**

dnes mi na BZL běhalo pár závodníků se stejným čipem, jedinný "problém" nastal když jeden z nich nebyl zároveň příhlášen, tedy vyčtení přepsalo původní záznam, kdyby se kontrolovala změna dat, proběhlo by vše bez jediného problému (build z master větve)
