### ISSUE TITLE
Weblate

### ISSUE THREAD

**Issue by paukert** [Quick-Event/quickbox#637]
Spolu se zahrnutim #629 je potreba na Weblate:

- [x] upravit masku u hlavnich prekladu `quickevent.*.ts --> quickevent-*.ts`
- [x] pridat libquickeventcore
- [x] pridat libquickeventgui
- [x] pridat libsiut
- [x] pridat quickshow

**Comment by fvacek** [comment]
ja se bojim ze #629 neco pokazil, protoze weblate ted vypada takto:

<img width="1420" alt="image" src="https://user-images.githubusercontent.com/4949019/125347988-f06aeb00-e35b-11eb-9429-a9d70f450c96.png">

**Comment by paukert** [comment]
v #629 se preklady ze vsech jednotlivych pluginu presunuly to jednoho souboru, z Weblate se pravdepodobne automaticky odstranily, kdyz prekladove soubory nebyly podle zadane masky nalezeny.. jako maintainer projektu bys snad mel byt schopny upravit masku u komponenty `Translations`, ktera nyni reprezentuje vsechny pluginy a pridat dalsi komponenty, ktere by reprezentovaly dalsi soucasti QuickBoxu (jejich soupis je vyse)

**Comment by fvacek** [comment]
asi se mi to podarilo

<img width="1332" alt="image" src="https://user-images.githubusercontent.com/4949019/125350073-8dc71e80-e35e-11eb-8153-d901e8013ac2.png">

**Comment by fvacek** [comment]
stejne porad moc nerozumim, ce se stalo se soubory `Event.cs_CZ.ts` a podobne, ty jsou ted uz soucasti `quickevent-cs_CZ.ts`? Pokud ano, jak se do nej presunuly ty prelozene fraze?

**Comment by paukert** [comment]
jo, uz to vypada dobre :)

jedina vec, ktera tam vypada jeste podivne je komponenta `Translations`, ktera drive byla napojena na soubor `quickevent/app/quickevent/quickevent.*.ts` a na kterou jsou ocividne nejakym zpusobem na Weblate navazany vsechny ostatni komponenty (proto jsem si myslel, ze by nejjednodussim zpusobem bylo zmenit masku u teto komponenty z `quickevent.*.ts` na `quickevent-*.ts` misto vytvareni dalsi komponenty)

> stejne porad moc nerozumim, ce se stalo se soubory Event.cs_CZ.ts a podobne, ty jsou ted uz soucasti quickevent-cs_CZ.ts? Pokud ano, jak se do nej presunuly ty prelozene fraze?

Ano, @otahirs pomoci nejakeho Qt nastroje vsechny preklady z jednotlivych pluginu zmergoval do souboru `quickevent-xx_XX.ts`, co jsem na to v rychlosti koukal, tak to vypadalo dobre :)

**Comment by fvacek** [comment]
> Ano, @otahirs pomoci nejakeho Qt nastroje vsechny preklady z jednotlivych pluginu zmergoval do souboru quickevent-xx_XX.ts, co jsem na to v rychlosti koukal, tak to vypadalo dobre :)

tak to cumim, myslel jsem, ze to budeme muset naprogramovat, to znamena, ze tyto TS soubory se uz mohou vymazat

**Comment by paukert** [comment]
> tak to cumim, myslel jsem, ze to budeme muset naprogramovat, to znamena, ze tyto TS soubory se uz mohou vymazat

myslim, ze byly uz dokonce v #629 smazane

**Comment by fvacek** [comment]
`Translation` asi uz muzeme vymazat, protoze jestli jsem to dobre pochopil, tak `quickevent.*.ts` bylo nahrazeno pomoci `quickevent-*.ts`

**Comment by paukert** [comment]
> 
> 
> `Translation` asi uz muzeme vymazat, protoze jestli jsem to dobre pochopil, tak `quickevent.*.ts` bylo nahrazeno pomoci `quickevent-*.ts`

jo, komponenta `Translations` uz neni potreba, jen nevim, jestli pujde smazat, protoze ostatni komponenty jsou na ni mozna nejak navazane

**Comment by paukert** [comment]
![Bez názvu](https://user-images.githubusercontent.com/15065907/125352248-4db56b00-e361-11eb-8c60-1edac9e7ab5e.png)

**Comment by fvacek** [comment]
> > tak to cumim, myslel jsem, ze to budeme muset naprogramovat, to znamena, ze tyto TS soubory se uz mohou vymazat
> 
> myslim, ze byly uz dokonce v #629 smazane

jj, zapomnel jsem si pullnout :)

**Comment by paukert** [comment]
> To same `QuickBox`

To by mel byt jen glossary, ten tam klidne muzeme asi nechat :)

**Comment by fvacek** [comment]
Tak to vypada, ze 
* `Translations` je umbrela projekt, ktery je potreba pro ostatni komponenty
* `QuickBox` je `glossary` coz je noco, co zase potrebuje weblate https://docs.weblate.org/en/latest/user/glossary.html

tak je tam necham oba

**Comment by paukert** [comment]
> `Translations` je umbrela projekt, ktery je potreba pro ostatni komponenty

resenim by bylo smazat komponentu `quickevent` a v komponente `Translations` prepsat masku, aby se to namapovalo na nove soubory (prejmenovani z `quickevent.*.ts` na `quickevent-*.ts` bylo myslim udelano kvuli automatickemu pribalovani prekladu k binarce)

**Comment by fvacek** [comment]
pak se ale lokalizace `quickevent` bude jmenovat `Translations` ne?

**Comment by paukert** [comment]
ano, komponenta na Weblate by se tak pravděpodobně jmenovala (pokud nejde přejmenovat)

potom je také otázkou, jestli by to případně něčemu vadilo (do teď se vlastně část překladů takto jmenovala)

**Comment by fvacek** [comment]
a bude necemu vadit, kdyz to nechame, jak to je?

**Comment by paukert** [comment]
vypadá to, že všechno funguje (včetně pushování překladů na GitHub), takže to určitě můžeme takhle nechat :)
