### ISSUE TITLE
Generátor HTML výsledků

### ISSUE THREAD

**Issue by horakmar** [Quick-Event/quickbox#639]
Pro potřeby našich víceetapových závodů jsem si napsal generátor HTML reportů z DB QuickEventu.
U výsledků a startovek prakticky kopíruje funkcionalitu QuickHttp, jen bez WWW serveru (a zatím bez filtru kategorií).
Navíc jsou celkové výsledky víceetapových závodů.
Napsáno v Pythonu, zkoušeno pouze na Linuxu.

Dávám k dispozici, kdyby měl někdo zájem:
https://github.com/horakmar/quickhtml

**Comment by paukert** [comment]
Služba pro export výsledků v HTML formátu pro aktuální etapu je přímo i v QE – Zobrazit --> Služby --> ResultsExporter (lze nastavit různé formáty výstupu včetně HTML, frekvenci exportu atd.)

Export celkových výsledků víceetapových závodů v HTML asi zatím opravdu přímo v QE napsaný není.

**Comment by horakmar** [comment]
Ano, vím o tom, dokonce jsem to úspěšně zkoušel (ResultsExporter -> SCP -> NGiNX). QuickHttp mi přišlo lepší, ale v obou mi chyběla možnost změny šablony a celkové výsledky.

**Comment by fvacek** [comment]
nechces to pridat do projektu QuickBox, tam to lide spis najdou?

**Comment by horakmar** [comment]
Rád, jen nevím jak. :-)

**Comment by fvacek** [comment]
Nejlepší by bylo, kdybys udělal pull request, jestli s tím nemáš zkušenosti, začal bych to já a společně bychom to doladili.

**Comment by horakmar** [comment]
Jasně, PR udělat umím. 
Mám QuickHTML adresář dát jako submodule z mého repozitáře, nebo čistě jako nový adresář v repu QuickBoxu?

**Comment by fvacek** [comment]
Přidal bych to jako podadresar do `tools`

**Comment by horakmar** [comment]
Je to tam.

**Comment by fvacek** [comment]
https://github.com/Quick-Event/quickbox/pull/641

**Comment by fvacek** [comment]
done https://github.com/Quick-Event/quickbox/pull/641/commits/6076d8a83152adbcadc36b660150f7bb7f952ca9
