### ISSUE TITLE
Přiřazení čipu závodníkovi na síťované verzi

### ISSUE THREAD

**Issue by kubarans11** [Quick-Event/quickbox#642]
Ahoj,
mám zasíťované 2 PC s QE - **PC1**, **PC2**.

1. Provedu přidání závodníka na **PC2** (na kterém neběží Postgres).
2. Chci po vyčítání na **PC1** použít funkci "Přiřadit čip závodníkovi", ale to bohužel nelze, přitom nový závodník se z **PC2** na **PC1** normálně propíše. Na přiřazení se mi nabídnou všichni závodníci kromě těch přidaných na **PC2**.

Funkce začne fungovat po restartu QE na **PC1** (což jsou 3 vteřiny manuální práce), ale při použití u labyrintu OF v Praze to není ideální...

Nevíte, čím by to mohlo být?

Díky moc a velké díky za QE!

**Comment by fvacek** [comment]
To musí být jediné nějaká chyba v refresh tabulky, protože pokud obě instance QE sdílí stejnou databázi, nemohou zobrazovat různá data. I to, že restart pomůže tomu napovídá, protože po restartu se na hrají všechna data z databáze znovu. Mohl bys přiložit screenshot toho, jak to tam není a číslo verze QE?

**Comment by kubarans11** [comment]
Verze QE jsem postupně obě aktualizoval (z 2.3.7 na **PC2** a z 2.3.8 z **PC1**) na 2.3.9 a chyba stále přetrvala.

Screenshoty situace na zápisu:
![PC2-1(1)](https://user-images.githubusercontent.com/63287718/127741381-7ff234fb-35ab-4f44-94ea-19eefcf77e88.png)
![PC2-2(1)](https://user-images.githubusercontent.com/63287718/127741383-50278fba-df40-4738-ab97-20e2257a93da.png)
![PC2-3(1)](https://user-images.githubusercontent.com/63287718/127741385-3c4ecce1-da4f-44ef-99b3-14f2db55ee50.png)
![PC2-4(1)](https://user-images.githubusercontent.com/63287718/127741387-446243f9-02ed-46bd-b753-6f17f42f9f19.png)

Screenshoty následné situace na vyčítání:
![PC1](https://user-images.githubusercontent.com/63287718/127741352-c164dfe3-fd61-4e5c-a392-95ea96cfe01a.png)
![PC1-2](https://user-images.githubusercontent.com/63287718/127741356-b71e7468-7db7-4254-b541-97a8b394d5d0.png)

**Comment by fvacek** [comment]
Diky za vycerpavajici vysvetleni, ted uz je to jasny, chyba je v implementaci tridy `FindRunnerEdit`, ktera bere zavodniky z tabulky Useky instance QE, ze ktere je volana, tam `Test Test` jeste neni. Namisto restartu QE by pomohl reload tabulky `Useky`. Samozrejme, ze toto neni uspokojivy workaround, opravime to. Jeste jednou diky za perfektni report. :+1:

**Comment by fvacek** [comment]
Tak je to jeste trochu jinak, FindRunnerEdit si cachuje zavodniky a pokud dojde k editaci v jine instanci QE, tato cache se nesmaze.

**Comment by fvacek** [comment]
will be fixed in 2.4.0
