### ISSUE TITLE
"Chybný import" počtu závodníků jednotlivých etap

### ISSUE THREAD

**Issue by Tomaqa** [Quick-Event/quickbox#645]
Verze 2.3.9.
Při importu víceetapového závodu z ORISu jsou v záložce "Kategorie" ve všech etapách počty závodníků stejné, tj. počet závodníků přihlášených na alespoň jednu libovolnou etapu, nikoli tu aktuální.
To činí potíže např. při rozvrhování startovních časů kategorií, protože rámečky jsou větší než ve skutečnosti mají být.
(V záložce Úseky/etapy je vše v pořádku, závodníci se objevují jen na těch etapách, kde jsou reálně přihlášeni.)

**Comment by Tomaqa** [comment]
Ještě k tomu mám dodatek. Možná nejde jen o problém s importem, ale i o vnitřní reprezentaci údaje o počtu závodníků.

Po nalosování jednotlivých etap se vakanti ukazují zelenými čarami a jsou dopočítáváni. Na konci každé kategorie mám nastaveného jednoho vakanta. Při následných úpravách startovky to, že je závodník umístěn na konci bloku z layouts, poznávám tak, že už za ním není žádný vakant.
Můj odhad je ten, že se zde opět nepoužívá počet závodníků na etapu přihlášených - v kategoriích, kde jsou nějací nestartující ("Zobrazit nestartující závodníky" by ukázalo někoho navíc), se to může tvářit, že na konci už žádný vakant není, přestože za posledním závodníkem je stále prostor.
Tedy může vzniknout dojem, že mám pokryty i ty nejzazší startovní časy, ačkoli tomu tak není. Musím pak provést ruční kontrolu s znovu se podívat do layout, kam až rámeček sahá.

**Comment by fvacek** [comment]
> Při importu víceetapového závodu z ORISu jsou v záložce "Kategorie" ve všech etapách počty závodníků stejné, tj. počet závodníků přihlášených na alespoň jednu libovolnou etapu, nikoli tu aktuální.

pokud si dobre vzpominam, oris import by mel importovat prihlasky do etap spravne, co to bylo na zavod, podivam se.

**Comment by Tomaqa** [comment]
> pokud si dobre vzpominam, oris import by mel importovat prihlasky do etap spravne, co to bylo na zavod, podivam se.

[Tento](https://oris.orientacnisporty.cz/Zavod?id=5711)

**Comment by fvacek** [comment]
fixed in 2.4.2
