### ISSUE TITLE
Nefunkční výběr lístečku ve verzi 2.4.2

### ISSUE THREAD

**Issue by lukaskett** [Quick-Event/quickbox#652]
Ahoj, zistili jsme, že ve verzi 2.4.2, kterou jsme používali pro generování startovek v 24h formátu, nefunguje výběr jiného typu lístečku (receip) než default. Už standardně používáme vlastní upravené qml a tak jsem musel přeskakovat mezi verzemi. @otahirs
![vyberListecku_v2 4 2](https://user-images.githubusercontent.com/29544822/134247737-86b95611-3c37-4b44-b508-4b06d01f0d3e.jpg)
![vyberListecku_v2 3 9](https://user-images.githubusercontent.com/29544822/134247741-316f98df-d4fb-4e51-aaf4-84486551acb4.jpg)

Díky
Lukáš

**Comment by paukert** [comment]
Hádám, že tohle bude způsobené tím, že od verze 2.4.x jsou qml soubory součástí QE binárky (Qt recources), takže už se nehledají ve složce, jako tomu bylo u předchozích verzí.

Stálo by určitě za zvážení, jestli minimálně u lístečků nezachovat i načítání z určité složky.

**Comment by otahirs** [comment]
> pokud k němu tedy nedochází  

nedochází, načítají se pouze Qt resources.

otázkou je jestli chceme načítat ze složky jako dříve, nebo nějaké víc nápomocné, např. `./assests`, `./custom/reciepts/`,..   
případně to zařídit tak aby se daly vlastní resources použít i u AppImage verze

**Comment by paukert** [comment]
> otázkou je jestli chceme načítat ze složky jako dříve, nebo nějaké víc nápomocné, např. `./assests`, `./custom/reciepts/`,..
> případně to zařídit tak aby se daly vlastní resources použít i u AppImage verze

nevím, jaké možnosti jsou u AppImage, ale líbilo by se mi načítání třeba z `./custom/reciepts/` , jak zmiňuješ výše :)

**Comment by lukaskett** [comment]
jsem taky pro nápomocnější složku

**Comment by jmacura** [comment]
> 
> 
> > otázkou je jestli chceme načítat ze složky jako dříve, nebo nějaké víc nápomocné, např. `./assests`, `./custom/reciepts/`,..
> > případně to zařídit tak aby se daly vlastní resources použít i u AppImage verze
> 
> nevím, jaké možnosti jsou u AppImage, ale líbilo by se mi načítání třeba z `./custom/reciepts/` , jak zmiňuješ výše :)

`./custom/receipts/`

**Comment by fvacek** [comment]
asi bych radsi `./quickevent/custom/receipts`, jinak jsem pro

**Comment by otahirs** [comment]
vzhledem k tomu, že cesta je stejně jen pro potřeby uživatelů, mimo součást quickeventu, tak jsem zvolil jednoduše název složky `/receipts`
tato složka se hledá vedle spustitelné quickevent binárky, a také v pracovním adresáří (cwd), aby šlo použít i s AppImage.
(také se složka již se neprohledává rekurzivně)
viz log
![Screenshot from 2021-09-28 11-03-59](https://user-images.githubusercontent.com/24588500/135057667-9a03fb8d-f02a-4da9-b2f3-1f379332548f.png)

**Comment by fvacek** [comment]
na toto uz mame `quickevent-data`, napsal jsem to do review

**Comment by otahirs** [comment]
na Windows by mělo stačit vložit qml soubory listecku do slozky `/quickevent-data/receipts` ve slozce s instalaci
některé importy se změnily, ty současné u Classic.qml vypadají takto
```
import QtQml 2.0
import qf.core 1.0
import qf.qmlreports 1.0
import shared.qml 1.0
import "qrc:/qf/core/qml/js/timeext.js" as TimeExt
import "qrc:/quickevent/core/js/ogtime.js" as OGTime
```
