### ISSUE TITLE
Přiřazování startovních čísel z dané sekvence

### ISSUE THREAD

**Issue by lukaskett** [Quick-Event/quickbox#653]
Ahoj,

vkládání startovních čísel je možné pouze v záložce Závodníci, v záložce Úseky / Etapy je vložení deaktivované (sloupec modře podbarven). Je to blbé, protože záložka Závodníci neobsahuje sloupec se startovním časem a tak není podle čeho závodníky v kategorii seřadit před přiřazením startovních čísel - vložením hodnot z požadované sekvence do sloupce. Museli jsme řešit přes řazení dle importované poznámky, do které jsme si ukládali startovní pořadí.

**Comment by fvacek** [comment]
neni problem ten sloupec udelat RW

**Comment by lukaskett** [comment]
Ok, to by stačilo. RW je předpokládám rewrite.

**Comment by otahirs** [comment]
RW je read-write neboli jak pro čtení, tak pro zápis.
> neni problem ten sloupec udelat RW

jen bych upozornil na to, že dnes je startovní číslo uloženo u závodníka a tedy na každou etapu musí být stejné.
bojím se že se časem objeví někdo kdo (např. usporada semifilále/finále jako viceetapovy zavod a) v Úseky / Etapy změní u další etapy startovní čísla a bude překvapen, že se mu něco rozsypalo u etapy jiné

**Comment by fvacek** [comment]
> jen bych upozornil na to, že dnes je startovní číslo uloženo u závodníka a tedy na každou etapu musí být stejné.
bojím se že se časem objeví někdo kdo (např. usporada semifilále/finále jako viceetapovy zavod a) v Úseky / Etapy změní u další etapy startovní čísla a bude překvapen, že se mu něco rozsypalo u etapy jiné

vyzkousel bych to, ja osobne souhlasim s tim, ze je to trochu na palici, kdyz musim prepnout tab a vyhledat zavodnia jenom proto, ze chci prepsat policko, ktere vidim v aktualni tabulce.

Poradani semifinale/finale jako viceetapovy zavod je docela QE golf, ktery neznam a nevim, jestli je to vubec validni case nebo jenom corner-case.

**Comment by Tomaqa** [comment]
Ještě bych k tomu dodal požadavek od Radka Vintra:
Přidělování startovních číse by mělo jít tak, že si udělám seznam v Excelu a jen nakopíruju buňky. Ale nepodařilo se mi to nakopírovat do QE. Vždy to tam přidávalo řádky, ale nepřepsalo data ve sloupci startovní číslo.

**Comment by fvacek** [comment]
![image](https://user-images.githubusercontent.com/4949019/192112004-bdca5d77-1c59-423c-b30a-bece60ff80a2.png)

a nemel jsi zaskrtnuty insert rows?

**Comment by lukaskett** [comment]
Dle popisu určitě, stejná věc se mi stala při vkládání startovních intervalů a měl jsem `Insert rows` zašktrnuté.

**Comment by fvacek** [comment]
to je zvlastni, zkousel jsem to a fungovalo mi to, to je videt na screen-shotu

**Comment by lukaskett** [comment]
dle mého je to ok, vkládání funguje správně, jen je potřeba odškrtnout `Insert rows`. Špatně jsem se vyjádřil, reagoval jsem na tvojí domněnku. Upravil jsem svůj předchozí komentář.

**Comment by Tomaqa** [comment]
Přeposílám od Rádi:
vkládání z Excelu funguje, pochopil jsem to trochu jinak, než to ve skutečnosti funguje a dělal jsem to špatně. Chyba byla u mě.

**Comment by paukert** [comment]
Pravděpodobně bylo uzavřeno omylem, původní požadavek IMO není zapracovaný.

**Comment by fvacek** [comment]
copy/paste to neresi?

**Comment by lukaskett** [comment]
To určitě ne, řešíme tady vkládání startovních čísel a hlavně seřazení závodníků, než jim číslo přiřadíš (přes copy/paste). Ideální by bylo seřazení dle startovního času (startovní čísla mu odpovídají).

Koukám, že ve verzi 2.6.5 sloupec se startovním číslem v záložce Úseky/Etapy úplně zmizel. navrhoval jsi tento sloupec udělat taky RW.

**Comment by fvacek** [comment]
v 2.6.7 je, nemas ho jenom skryty?
![image](https://user-images.githubusercontent.com/4949019/193473649-53e02c4e-abfc-46ac-ad52-0f664d720f75.png)
 kazdopadne je porad RO

**Comment by lukaskett** [comment]
ok, sry měl jsem ho skrytý, resp je pravděpodobně skrytý v defaultu. Přijde mi nepraktický v každém okně klikat na 'Zobrazit všechny sekce', abych si ověřil co všechno tam je a není.

Ano stále RO, potvrzuju.

**Comment by fvacek** [comment]
v defaultu ten sloupec skryty neni, to si muzes snadno overit, kdyz si smazes config a pustis QE.

**Comment by paukert** [comment]
Issue bych zase otevřel, aby nám nezapadla mezi vyřešené.

**Comment by fvacek** [comment]
A proc neni vyresena, kdy jde startovni cisla vlozit ze schranly?

**Comment by lukaskett** [comment]
Stále nejde vložit startovní čísla do dle startovního času seřazeného startovního pole. Protože v záložce Závodníci není sloupec startovní čas, ale jde tam vkládat nové řádky. Zatímco v záložce Úseky/Etapy je sice sloupec se startovním časem, ale startovni číslo je pouze RO. Viz můj prvotní popis.

**Comment by fvacek** [comment]
Jsem natvrdlej, uz tomu rozumim :)

**Comment by fvacek** [comment]
fixed in 2.6.9
