### ISSUE TITLE
XML export startovek neobsahuje startovní číslo

### ISSUE THREAD

**Issue by lukaskett** [Quick-Event/quickbox#654]
Ahoj,

ačkoliv jsme hlavním kategoriím přiřadili startovní čísla, tak je XML export startovek z QE neobsahoval a tak se nemohla nenahrát do Orisu. Museli jsme řešit přiložením extra pdf se startovku, kde už čísla byla vidět.

Exportované xml pro demonstraci klidně doplním.

**Comment by paukert** [comment]
Ideální by byl qbe soubor, aby to šlo následně jednoduše otestovat :)

**Comment by paukert** [comment]
Mělo by stačit přidat sem:
https://github.com/Quick-Event/quickbox/blob/e695f9b090fd448b9059f0bf9ba1426c39939620/quickevent/app/quickevent/plugins/Runs/src/runsplugin.cpp#L2130
něco jako:
```
auto bib_number = tt2_row.value(QStringLiteral("competitors.startNumber"));
if(!bib_number.isNull())
	append_list(xml_start, QVariantList{"BibNumber", bib_number});
```

připravím PR. Jinak co jsem koukal, tak ve všech jiných exportech startovek by měla být startovní čísla obsažena nebo jsem to někde přehlédl?

**Comment by lukaskett** [comment]
Přikládám data na vyzkoušení, dík.
[210919_mcr_klasika.zip](https://github.com/Quick-Event/quickbox/files/7221025/210919_mcr_klasika.zip)

**Comment by fvacek** [comment]
nemelo by to byt spis:
```c++
auto bib_number = tt2_row.value(QStringLiteral("competitors.startNumber"));
if(!bib_number.isNull())
	append_list(person, QVariantList{"BibNumber", bib_number});
```

**Comment by paukert** [comment]
Podle tohoto bych řekl, že to má být ve `<Start>`
https://github.com/international-orienteering-federation/datastandard-v3/blob/24eb108e4c6b5e2904e5f8f0e49142e45e2c5230/examples/StartList1.xml#L51

**Comment by fvacek** [comment]
mas pravdu :)
