### ISSUE TITLE
Liveresultat nechtějí vzít oražení cílovky

### ISSUE THREAD

**Issue by fvacek** [Quick-Event/quickbox#656]
Ahoj,

mám problém s propojením QE a Liveresultat, že se mi nechtějí vzít oražení cílovky. Tak bych se chtěl zeptat, jestli jsi něco podobného neřešil. V Radio Controls finish není, ale to je asi ok (dle ostatních závodů). Když ho tam totiž přidám, tak docílím jen dalšího sloupce.

Ve zkratce mi Liveresultat úplně přehlíží oražení cíle. Aktuálně tak musím počkat než si závodník vyčte a dostanu záznam do .finish, který pak nahraju přes Emma Clienta.

![image](https://user-images.githubusercontent.com/4949019/134739196-51798bdc-8cd7-4391-815f-edf8965ccfba.png)

Díky moc

Cáš

**Comment by lukaskett** [comment]
Ahoj, vyřešeno, nebyla chyba QE. Cíl se nechová jako radiokontrola a čas je potřeba zapisovat do cílového souboru .finish.txt, což jsem nevěděl.

Můžeš zavřít, dík.
