### ISSUE TITLE
Disk časový limit - overtime

### ISSUE THREAD

**Issue by lukaskett** [Quick-Event/quickbox#658]
Ahoj,

dle diskuze u #655 QE aktuálně tento typ diskvalifikace nepodporuje. Zaznamenávám požadavek na přidání typu diskvalifikace závodníka při překročení časového limitu - overtime. Otevřeme tak možnost používat QE i na mezinárodních akcích. 

Díky
Cáš

**Comment by martinkrivda** [comment]
myslím, že feature request existuje #69

**Comment by lukaskett** [comment]
aha, jsem si nevšiml, dík. Nechal bych issue kvůli vyhledávání. Heslo overtime ani časový limit mi v souvislosti se statusem závodníka vyhledávání v issues nenašlo.

**Comment by fvacek** [comment]
dup #69
