### ISSUE TITLE
Numbers only edit boxes support

### ISSUE THREAD

**Issue by Amaroun** [Quick-Event/quickbox#66]
It's a feature request.
If qe is used on ntb without numerical keyboard, switching between CZ/EN keyboards or using shift to enter numbers is very time consuming.
Allowing to configure sort of 'virtual numeric keyboard' for editboxes for numbers edit only, to translate czech characters to coresponding numbers on english keyboard would be of a big help (si number is most common case).

**Comment by fvacek** [comment]
How we will localize such a feature?

**Comment by otahirs** [comment]
Localization is not a problem. Every key on the keyboard has also a static numerical key code.
https://www.w3.org/2002/09/tests/keys.html

**Comment by fvacek** [comment]
Just to be 100% sure. This feature will cause that when one enters `+ěščřžýáíé` in SI number edit box, then entered value will be `1234567890`. Correct?

**Comment by otahirs** [comment]
I tried to implement this. I have not found a way to get to right key code in Qt. None of the methods of [QKeyEvent](https://doc.qt.io/qt-5/qkeyevent.html) shows the original pressed key for Czech keyboard. So localization is a problem after all.

**Comment by fvacek** [comment]
You can use https://doc.qt.io/qt-5/qkeyevent.html#nativeScanCode, for example key `1` has always `native scan code == 10` regardless of keyboard layout used.

**Comment by otahirs** [comment]
I thought so, however `native scan code` in my system for key 1 showed as up to be `32767`

**Comment by fvacek** [comment]
> I thought so, however `native scan code` in my system for key 1 showed up to be `32767`

can you double check this? What is your system? My is Debian 10 x64

**Comment by otahirs** [comment]
I just did that to write the "actual" code on my system. Fedora 32 x64
keydown/keyapp in this webapp works https://www.w3.org/2002/09/tests/keys.html for me, but I had no luck finding anything similar while playing with the `keyPressEvent` event and corresponding `QKeyEvent` class

**Comment by fvacek** [comment]
please try this, I do not see any reason, why it should work differently on Debian. 
[keycodetest.tar.gz](https://github.com/Quick-Event/quickbox/files/5147252/keycodetest.tar.gz)

**Comment by otahirs** [comment]
ok, you minimal working example works great, the native key code is correct (e.g. `10` for key 1)
I might have made a mistake while using the debugger. On the third check, the native scan code is correct even in QE. 
...
Is there a list of constants for native scan codes?
the [constants I found in Qt](https://doc.qt.io/qt-5/qt.html#Key-enum) for key codes do not correspond to `native scan codes`
e.g.  `Qt::Key_1` is `0x31` which is `49` in decimal

**Comment by paukert** [comment]
Can be closed, implemented in 2.3.8
