### ISSUE TITLE
Nelze přidat neregistrovaného závodníka do štafety

### ISSUE THREAD

**Issue by janpalas** [Quick-Event/quickbox#665]
Nepodařilo se mi zadat závodníka, který není registrován, na soupisku libovolné štafety - program vždy spadnul. Závodníka jsem chtěl nejdříve přidat v sekci "Závodníci" - vyplnil jsem údaje, dal uložit a konec běhu programu. 

- Toto chování jsme pozorovali na ČPŠ 25.-26.9.2021
- Přikládám zálohu [20210926-1500.zip](https://github.com/Quick-Event/quickbox/files/7250320/20210926-1500.zip)

**Comment by arnost00** [comment]
Dialog na priadavani useku do stafety je rozsiren o pridani neregistrovaneho zavodnika
![2021-10-31 14_17_25-Add leg](https://user-images.githubusercontent.com/8378685/139585711-7dce6781-2ecf-4209-8afe-9365e3b4ee47.png)

**Comment by fvacek** [comment]
zda se mi, ze je to naimplementovano v jinem pull requestu https://github.com/Quick-Event/quickbox/pull/673

**Comment by arnost00** [comment]
> zda se mi, ze je to naimplementovano v jinem pull requestu #673

Ano. Je to v ramci toho pull requestu.

**Comment by arnost00** [comment]
Normalne si myslim ze tuto zalozku ve stafetach ani nemusis otevrit. Ale je pravda ze padat by to nemelo.
Protoze otevrit a pouzit ji muzes.

**Comment by arnost00** [comment]
Moje veskere pokusy s opravou vedly maximalne k tomu ze ve stafetech to pridalo zaznam jak do competitors tak i runs.
Coz je vec kterou si myslim ze nechceme, do runs by to nemelo nic pridavat.
Cim dal vic si myslim ze by toto tlacitko pri stafetach nemelo zobrazit dialog vyberu zavodnika, ale pouze info, aby jsi zavodnika pridal ve stafetach.

**Comment by paukert** [comment]
> Cim dal vic si myslim, ze by toto tlacitko pri stafetach nemelo zobrazit dialog vyberu zavodnika, ale pouze info, aby jsi zavodnika pridal ve casti stafety.

To by podle mě bylo také validní řešení, ale o štafetách toho opravdu moc nevím, takže bych asi ještě počkal na vyjádření někoho dalšího.

**Comment by fvacek** [comment]
zacal bych tim padanim ,co musim udelat aby to spadlo?

**Comment by paukert** [comment]
> zacal bych tim padanim ,co musim udelat aby to spadlo?

Otevřít si nějaký závod štafet (třeba ten z této issue) a ze záložky competitors zkusit přidat nového závodníka (při kliknutí na `Save` / `Save and next` program spadne).

**Comment by arnost00** [comment]
> zacal bych tim padanim ,co musim udelat aby to spadlo?
Presne jak pise @paukert .
A spadne to proto ze ve stafetach nema zavodnik kategorii. Registrovany kvuli tomu v Save projde (protoze se mu tipne nejaka kategorie do disabloveneho comboboxu). 
V nekterych castech dialogu se kontroluje ze jsou to stafety a neni potreba mit vypnenu kategorii, ale pri Save vnitrni model nejak narazi na to ze neni.

**Comment by fvacek** [comment]
> V tomto ohledu by se melo zvazit zda ma cenu vyhazovat v kodu vyjimky, ktere nechytame. A zacit je chytat, nebo prestat pouzivat. Ale prehled pres cele QE nemam, abych dokazal rict ktera cesta by byla vhodnejsi.

QE pouziva neodchycene vyjimky jako fatal error, ve srovnani s `qFatal()` to ma tu vyhodu, ze pokud to neni fatalni chyba, ale neco, co se da zachranit, lze tu vyjjimku odchytnout. Pravdepodobne to bude i tento pripad.

**Comment by paukert** [comment]
Když už se začalo více řešit logování (https://github.com/Quick-Event/quickbox/issues/672) – možná bychom mohli pro snadnější identifikaci problému, chytat všechny výjimky na nejvyšší úrovni, vytvořit log a vyhodit ji znovu.

**Comment by fvacek** [comment]
> Když už se začalo více řešit logování (#672) – možná bychom mohli pro snadnější identifikaci problému, chytat všechny výjimky na nejvyšší úrovni, vytvořit log a vyhazovat je znovu.

tohle se presne deje: https://github.com/Quick-Event/quickbox/blob/eb547d1c21895e2034d2656f877a47daf834f989/libqf/libqfcore/src/core/exception.cpp#L38

**Comment by arnost00** [comment]
@fvacek dostanes se na to padani ? Nebo to vyresime zablokovanim spousteni tohoto dialogu pri stafetach ? 
Vycistil bych z toho dialogu handlovani stafet a nechal ho pouze pro jednotlivce.

**Comment by fvacek** [comment]
jj ,mrknu na to

**Comment by fvacek** [comment]
fixed in 2.4.5
