### ISSUE TITLE
Force isRunning flag to be not null

### ISSUE THREAD

**Issue by paukert** [Quick-Event/quickbox#668]
> During tests I faced strange behaviour:
> 
> ```sql
> SELECT * FROM runs WHERE NOT isRunning
> SELECT * FROM runs WHERE isRunning IS NULL
> ```
> 
> results were different accross events, mostly only one option worked.
> 
> Maybe we should force notNull in DbSchema
> 
> https://github.com/Quick-Event/quickbox/blob/551548ad5e3791f2d398d45511ed13b70a3f2b13/quickevent/app/quickevent/plugins/Event/qml/DbSchema.qml#L208

- change to notNull in DbSchema
- edit import event as qbe (replace null with false)
- check queries if they deal with isRunning as a bool

**Comment by fvacek** [comment]
fixed in 2.4.8

**Comment by paukert** [comment]
I think we should improve importing event from previous version with isRunning flag set to null. In current version import fails:

![import](https://user-images.githubusercontent.com/15065907/149237872-16c6d77c-e7b7-4485-bd28-d360355dc003.png)

**Comment by paukert** [comment]
This check is not needed anymore, could be removed in future versions

https://github.com/Quick-Event/quickbox/blob/d4fb1d27e8b6f75b9c0f4f4db5aa229bb7eaf243/quickevent/app/quickevent/plugins/Event/src/services/emmaclient.cpp#L440

**Comment by fvacek** [comment]
should be fixed in 2.5.1, testing needed

**Comment by paukert** [comment]
Import looks fine but I cannot change isRunning flag through Runs module, exception is thrown with same error.

> 2022-01-16T19:18:15.819	Warning		NOT NULL constraint failed: runs.isRunning Unable to fetch row

**Comment by fvacek** [comment]
fixed in 2.5.3
