### ISSUE TITLE
Implement IOF-XML-v3 ResultStatus flags

### ISSUE THREAD

**Issue by fvacek** [Quick-Event/quickbox#669]
IOF definuje ResultStatus v datastandardu v3
```
OK
Finished
MissingPunch
Disqualified
DidNotFinish
Active
Inactive
OverTime
SportingWithdrawal
NotCompeting
Moved
MovedUp
DidNotStart
DidNotEnter
Cancelled
```
Vybral jsem ty, ktere si myslim ze opravdu muzeme pouzivat :
OK - Finished and validated.
MissingPunch - Missing punch.
Disqualified - Disqualified (for some other reason than a missing punch).
DidNotFinish - Did not finish (i.e. conciously cancelling the race after having started, in contrast to MissingPunch).
OverTime - Overtime, i.e. did not finish within the maximum time set by the organiser.
NotCompeting - Not competing (i.e. running outside the competition).
DidNotStart - Did not start (in this race).
Cancelled
SportingWithdrawal

**Comment by arnost00** [comment]
O enumu jsem uz taky uvazoval, ale nechtel jsem to uz do reseni chyby v EmmaClientu psat. Sem se to hodi. @otahirs dik.

**Comment by jmacura** [comment]
> 
> všechny možnosti jsou si vzájemně neslučitelné.

To bych neřekl. *Disqualified* je slučitelné prakticky se vším, kromě *DidNotStart*. Stejně tak třeba *MissingPunch* + *DidNotFinish* nebo *MissingPunch* + *OverTime* nebo *MissingPunch* + *NotCompeting* nebo dokonce *MissingPunch* + *NotCompeting* + *OverTime*...

Čili pokud bude v QE implementováno vše dohromady jako přepínač, je potřeba správně nastavit priority jednotlivých "disk" stavů (*MissingPunch* důležitější, než *NotCompeting*, *Disqualified* důležitější, než vše ostatní atd.). Stejně tak je potřeba podchytit případ, kdy pořadatel někomu ručně nastaví *Disqualified* (protože omyl nebo protože to tak někdo chtěl) a poté tento příznak zruší, aby nedošlo ke ztrátě informace o těch ostatních stavech (*OverTime*, *NotCompeting*, ...), tj. aby se závodník, který byl v lese 4 hodiny, vynechal 3 kontroly a přeplaval řeku, nemohl objevit ve výsledcích jako OK jen proto, že někdo zmáčkl 2x tlačítko "diskvalifikovat".

**Comment by otahirs** [comment]
nějaké myšlenky, netvrdím ani že je to celé správná cesta
---

hodnoty které lze vypočíst:
- MissingPunch 
- OverTime 

defaultně pokud je vše vpořádku
- OK

musí se ručně nastavit
- Disqualified
- DidNotFinish
- NotCompeting
- DidNotStart

> To bych neřekl. Disqualified je slučitelné prakticky se vším, kromě DidNotStart. Stejně tak třeba MissingPunch + DidNotFinish nebo MissingPunch + OverTime nebo MissingPunch + NotCompeting nebo dokonce MissingPunch + NotCompeting + OverTime...

výše zmíněné by mohly vyřešit pravidla:
1) Ručně nastavené (Dsq, DNF, NC, DNS) přebijí automatiku (MP, OT, OK). 
2) MP má přednost před OT
3) Disqualified je nejobecnejsi a použije se pouze pokud disk nespadá pod jiný důvod.


bylo by třeba tlačítko/způsob, jak nechat systém znovuvyhodnotit výsledek závodníka.  
ručně nastavit musí jít vše (i OK, MP, OT), pokud by nekde selhla technika (asi nejaky flag jako isForcedResult, ktery by se nastavoval i u Dsq, DNF, NC, DNS)
mít vizuálně rozlišeno, co vynutila obsluha QE (isForcedResult) oproti timu co vypocital systém

**Comment by fvacek** [comment]
> Enum by byl určitě jednodušší do exportů a reportů, automatické vyhodnocení po vyčtení čipu také nebude větší problém (je potřeba si dát pouze pozor na prioritu).
> 
> Největší potencionální problémy vidím u zásahů obsluhy, jak už zmiňoval @jmacura - někdo např. běží mimo soutěž, nefungovala kontrola (tj. razil do mapy), v cíli ukáže hlavnímu rozhodčímu náhradní ražení, obsluha přepíná stav MissingPunch na OK a byl by problém.. Takže tohle je potřeba opravdu dobře promyslet (jaké ruční zásahy půjdou dělat a jak to bude fungovat), aby se při těchto změnách neztrácely nějaké informace. Další příklad - obsluha v případě enumu asi neuvidí, že závodník se statusem `MissingPunch` měl ještě před vyčtením `Disqualified` např. kvůli tomu, že byl v zakázaném prostoru - pokud se rozhodne `MissingPunch` zrušit, mělo by se automaticky asi nastavit `Disqualified` - takže by byl potřeba v DB asi další flag(y), jak psal @otahirs
> 
> S ohledem na to, kolik to bude práce, a na to, že v DB stejně IMO budou muset asi zůstat další příznaky, nevím, jestli to má cenu vlastně upravovat...

souhlasim, naimplementujeme bitfield a udelame funkci, ktera ho bude umet prevest na iof-xml enum pro ucely exportu

**Comment by fvacek** [comment]
some related discusion in #655

**Comment by fvacek** [comment]
Pridal jsem chbejici atributy do databaze, vypada to ted takhle:
<img width="343" alt="image" src="https://user-images.githubusercontent.com/4949019/148837924-4777858e-8fbe-403a-a30d-b2508cfaa001.png">

**Comment by fvacek** [comment]
since ver. 2.5.0
