### ISSUE TITLE
vyčtení nepřihlášeného závodníka s již vyčteným čipem

### ISSUE THREAD

**Issue by otahirs** [Quick-Event/quickbox#678]
1. vyčte závodník
2. vyčte jiný závodník který bežel se stejným čipem (nebyl přihlášen, vyčtení přepíše čas závodníka 1)
   a. závodník přidán v competitors
   b. v readout modulu  _assign card to runner_

konečný stav:
nový jiný závodník má vše v pořádku
u starého zůstal přepsaný čas, je třeba nechat přepočíst výsledky - *recalculate time in selected rows*

možnosti řešení:
1. nenechat vyčíst, viz #636
2. po assign přepočítat časy u všech vyčtených závodníků se stejným číslem čipu (může se něco rozbít?)

**Comment by fvacek** [comment]
hlasuji za 1, je to dalsi corner-case a budu rad, kdyz se toto issue podari vyresit v ramci #636
