### ISSUE TITLE
Remove redundant buttons

### ISSUE THREAD

**Issue by otahirs** [Quick-Event/quickbox#680]
Throughout the whole app, the tables contain `Post row edits` and `Revert row edits` buttons, is there any use for them as they are always disabled anyway as far as my memory goes or can they be removed?
![Screenshot from 2021-12-05 18-09-49](https://user-images.githubusercontent.com/24588500/144756331-07684c05-61af-4b0c-af64-3c8f9ad0e7b6.png)

**Comment by fvacek** [comment]
There are 2 post data strategies defined for table, when row is posted and when cell edit is finished. The buttons marked are usable only in the first one. AFAIK almost every table in QE is using the `when cell edit is finished` startege. So yes, buttons can be removed.
