### ISSUE TITLE
Formát tisknutého lístečku

### ISSUE THREAD

**Issue by horakmar** [Quick-Event/quickbox#687]
Ahoj.
Mám dotaz/námět: Je možné nějak ovlivnit formát tisknutého lístečku?
Zkoušel jsem tisk z QE na Bluetooth pokladní tiskárně Cashino PTP-II (běžně používané s SI-Droidem) a v grafickém režimu to sice lístečky tiskne, ale nevejdou se tam informace na řádek (papír 58mm). V textovém režimu se mi na ní tisknout nepodařilo - nevím jaké zadat zařízení aby to k BT tiskárně prošlo (na Linuxu).
Chtělo by to nějakou možnost zmenšit font, nebo upravit formát tisknutých informací.
Chápu, že QE je spíš pro větší akce, kde je elektrická přípojka na větší tiskárny, ale hodil by se mi občas i na tréninky uprostřed lesa.

S pozdravem,
Martin Horák

**Comment by otahirs** [comment]
1. může si vytvořil vlastní Qml soubor lístečku vycházející z https://github.com/Quick-Event/quickbox/blob/master/quickevent/app/quickevent/plugins/Receipts/qml/receipts/Classic.qml
a ten pak vložit do složky `./quickevent/data/`, tuto složku je třeba vytvořit vedle souboru co spouští aplikaci, lísteček by pak měl příbýt ve výběru lístečků

2. mohli bychom nabízet nějakou kompaktnější užší verzi

**Comment by horakmar** [comment]
Tak jsem si s tím ještě pohrál a podařilo se mi rozběhat tisk v textovém režimu. Pro ty kdo by řešili stejný problém mám stručný návod. Předem se omlouvám za neúplnost, nejsem odborník na Linux Bluetooth, pouze uživatel.

# Jak na tisk lístečků na bluetooth tiskárně
OS: Linux Ubuntu 20.04 (Focal Fossa)
Tiskárna: Cashino PTP-II

  1. Spárovat tiskárnu pomocí standardního bluetooth klikacího nástroje (omlouvám se, že jsem nenastudoval, jak to udělat v v CLI)
  2. Zjistit BDADDR tiskárny:
```bash
hcitool scan
 Scanning ...
	DC:0D:30:8F:3A:B8	PTP-II
	D4:9D:C0:43:68:C5	[TV] Samsung 7 Series (55)
```
  3. Nastavit RFCOMM komunikaci (emulace RS-232 sériového portu):
```bash
sudo rfcomm connect /dev/rfcomm0 DC:0D:30:8F:3A:B8
Connected /dev/rfcomm0 to DC:0D:30:8F:3A:B8 on channel 1
Press CTRL-C for hangup
```
  4. V QE nastavit v části **Mezičasy** tiskárnu *Znakově*, LPT zařízení: /dev/rfcomm0, 32 znaků na řádek, ASCII7

Pak to tiskne celkem slušně, šikla by se už jen drobná úprava formátu, ale i tak je to OK.

**Comment by fvacek** [comment]
diky za vyzkum, mohu zavrit?

**Comment by horakmar** [comment]
Přimlouval bych se za úpravu dokumentace (přidat informaci o možnosti úpravy šablony lístečku, případně tento návod jak tisknout znakově přes BT).
Jinak možno zavřít, díky.

**Comment by fvacek** [comment]
Idealni by bylo, kdybys dokumentaci mohl upravit ty, mas z BT momentalne nejvic zkusenosti, tak jestli te muzeme poprosit :)

**Comment by otahirs** [comment]
> # Jak na tisk lístečků na bluetooth tiskárně
> ...

dnes vyzkoušeno na Fedoře (program `rfcomm` je zde součástí balíčku `bluez-deprecated`) s tiskárničkou *SPORTident Printer*, vše bez problémů.

Díky

**Comment by otahirs** [comment]
Ještě jednodušeji jde tiskárna připojit na windows. 
Po spárování bluetooth, rozkliknout nastavení připojené bluetooth tiskárny, je tam záložka porty. Jeden COM port pro zápis, jeden pro čtení. Port pro zápis pak stačí zapsat jako cestu k LPT zařízení v nastavení tisku, např. `\\.\COM5`

**Comment by horakmar** [comment]
Doplněno do dokumentace (wiki). Možno uzavřít.
