### ISSUE TITLE
Nefunkční přiřazení čipu k závodníkovi u štafet pro druhý a další úsek

### ISSUE THREAD

**Issue by otahirs** [Quick-Event/quickbox#688]
Jediné místo, kde se v kódu nyní nastavuje startovní čas je až samotném vyčtení závodníka:
https://github.com/Quick-Event/quickbox/blob/94b1c2c90bffd26120d39257c792d41cbce58180/quickevent/app/quickevent/plugins/CardReader/src/cardreaderplugin.cpp#L504-L518

To by bylo v pořádku, akorát že ještě než se provede nastavení startovního času (viz výše), musí se u `findRunId` projít přes tuto podmínku, viz níže. Jenže zde `int st = q.value("startTimeMs").toInt();` skončí vždy na hodnotě `0`, podmínka je splněna a funkce nikdy nevrátí závodníka, kterému se má čip přiřadit.
https://github.com/Quick-Event/quickbox/blob/94b1c2c90bffd26120d39257c792d41cbce58180/quickevent/app/quickevent/plugins/CardReader/src/cardreaderplugin.cpp#L115-L120

Vyčítání druhého a dalěího úseku by tedy dle mých informací u štafet vždy selže, protože se v `CardReaderPlugin::findRunId` nenajde závodník, kterému by se čip přiřadil. 

Kód je však starý dva roky a štafety se bez problému pořádaly, otázka tedy zní, jak je to možné? Před mou nedávnou změnou https://github.com/Quick-Event/quickbox/pull/685 existovalo i přeskočení všech kontrol pokud se našel jen jeden záznam, viz níže. Ten jsem však v rámci změn odtranil.

https://github.com/Quick-Event/quickbox/blob/696b6f1592e701ea7a215bd8045736fd049de187/quickevent/app/quickevent/plugins/CardReader/src/cardreaderplugin.cpp#L168-L171

---

**TLDR;** 
1. na současném vydání nelze pořádat štafety, nefunguje automatické přířazení čipů pro druhé a další úseky
2. podmínka níže nedává smysl, protože startovní čas pro druhý a další úsek není při kontrole ještě nastaven. je nutne priradit startovni cas i pri vycteni predchoziho useku
https://github.com/Quick-Event/quickbox/blob/94b1c2c90bffd26120d39257c792d41cbce58180/quickevent/app/quickevent/plugins/CardReader/src/cardreaderplugin.cpp#L117-L120
3. navrátit původní přeskočení, nebo lépe -> doplnit chybějící error zprávy pokud se najde jedinný záznam, který však neprojde kontrolou

**Comment by fvacek** [comment]
@otahirs  prisel jsi na to, jak bylo mozne poradat stafety na nefunkcnim QE?

**Comment by otahirs** [comment]
zavlíkl jsem to tam já poslední změnou https://github.com/Quick-Event/quickbox/pull/685
díky tomuto to dříve propadlo 
https://github.com/Quick-Event/quickbox/blob/696b6f1592e701ea7a215bd8045736fd049de187/quickevent/app/quickevent/plugins/CardReader/src/cardreaderplugin.cpp#L168-L171

**Comment by fvacek** [comment]
oka, v tom pripade to zmerdzuju, asi budu muset vydat novy relaease, protoze ten vanocni obsahuje tuto chybu, je to tak?

**Comment by otahirs** [comment]
ano
