### ISSUE TITLE
Implementation of time limit for a stage

### ISSUE THREAD

**Issue by Amaroun** [Quick-Event/quickbox#69]
Time limit cannot be set for a stage (and reflected in results later on)

**Comment by fvacek** [comment]
Why cannot?

**Comment by fvacek** [comment]
partially duplicated in #655 

basicaly we have to;
1. add `overtime` flag to the `runs` table
2. add the overtime limit to the stage config
3. check overtime during card check after finish

**Comment by arnost00** [comment]
Solved in #841, with maximum simplicity :
- add ``overtime`` flag to the ``runs`` table
- extend Run flags dialog with "Over time" flag
- added in exports & results

**Comment by arnost00** [comment]
Can be closed. Merged with #841 to master.
