### ISSUE TITLE
Check for PostgreSQL schema name is run also for SQLite

### ISSUE THREAD

**Issue by paukert** [Quick-Event/quickbox#694]
Check for event name during import is run even if single file is set as a data storage. It does not break anything but error mentioning PostgreSQL could be confusing for users who are using SQLite.

https://github.com/Quick-Event/quickbox/blob/d4fb1d27e8b6f75b9c0f4f4db5aa229bb7eaf243/quickevent/app/quickevent/plugins/Event/src/eventplugin.cpp#L1156

```c++
const std::regex psqlschema_regex("[A-Za-z][A-Za-z0-9_]*");
if(!std::regex_match(event_name.toStdString(), psqlschema_regex)) {
	qfd::MessageBox::showError(fwk, tr("PostgreSql schema must start with letter and it may contain letters, digits and underscores only."));
	return;
}
```

Adding one of these conditions would solve this issue
```c++
connectionType() != ConnectionType::SingleFile
```
```c++
connectionType() == ConnectionType::SqlServer
```

**Comment by fvacek** [comment]
fixed in 2.5.2

**Comment by paukert** [comment]
Tested with PostgreSQL and SQLite, it works fine :)

**Comment by fvacek** [comment]
great, thanks
