### ISSUE TITLE
cards.id is misused instead of cards.siId 

### ISSUE THREAD

**Issue by otahirs** [Quick-Event/quickbox#703]
It is not directly related to this PR but IMO this does not work properly. First argument of function isCardLent should SI card number, not id from cards table.

_Originally posted by @paukert in https://github.com/Quick-Event/quickbox/pull/701#discussion_r794386583_

---
whole app should be checked

**Comment by paukert** [comment]
I checked whole app for calling isCardLent method in the wrong way, I found no more problems #704
