### ISSUE TITLE
Při přepnutí etapy v modulu Runs nedojde k aktualizaci záznamů

### ISSUE THREAD

**Issue by paukert** [Quick-Event/quickbox#705]
Přepnutí etapy v modulu Runs neaktualizuje záznamy a ani tlačítko Obnovit nepomáhá. Po přepnutí do jiného modulu a zpět nebo i zobrazení/skrytí nestartujících závodníků se záznamy aktualizují.

Video:

https://user-images.githubusercontent.com/15065907/152565619-4fccf08e-4181-4fe1-bcc5-f537bad61b97.mp4

**Comment by paukert** [comment]
Mělo by stačit sem přidat `reload();` ale možná existuje lepší úprava..
https://github.com/Quick-Event/quickbox/blob/dbae4b4f3775ede9f4a49e731fe9c4df48929658/quickevent/app/quickevent/plugins/Runs/src/runswidget.cpp#L929

```c++
void RunsWidget::onCbxStageCurrentIndexChanged()
{
	getPlugin<RunsPlugin>()->setSelectedStageId(m_cbxStage->currentData().toInt());
	// add reload();
	qfInfo() << "selected stage:" << selectedStageId();
}
```

**Comment by otahirs** [comment]
myslím že je to preferovana úprava
