### ISSUE TITLE
Tlacitko vlozit zavodnika v "Zavodnici" zustava zasedle

### ISSUE THREAD

**Issue by arnost00** [Quick-Event/quickbox#712]
Zavodnici -> zapnut filtr na zavodniky 
Prepnu jiny modul
Vratim se na modul zovodnici 
A tlacitko Vlozit zavodnika je zasedle
Je potreba smazat filtr a prepnout se z modulu a zpatky do mudulu

Jinak pokud zustanu v modulu zavodnici tak tlacitko zustane povolene.

**Comment by paukert** [comment]
Podobná chybička už byla i nahlášena https://github.com/Quick-Event/quickbox/issues/679

**Comment by arnost00** [comment]
> Podobná chybička už byla i nahlášena #679
Dik, ja si to myslel, ale nedokazal jsem to najit. Takze tohle muzeme oznacit jako duplicitu

**Comment by paukert** [comment]
Nevím, jestli se jedná o úplně stejnou chybu, ale mohlo by to spolu určitě souviset.

**Comment by arnost00** [comment]
Je to velice podobna chyba, skoro to vypada ze jsou to dva ruzne popisy jedne chyby.
A myslim si ze oprava nejspis bude spolecna pro obe issue.

**Comment by fvacek** [comment]
QE neumi dobre vkladat radky pri aktivnim fulltext filtru, takze chyba byla, ze tlacitko nebylo zasedle uz pred prekliknutim mezi moduly

fixed in 2.5.8
