### ISSUE TITLE
Vratit reporty z resources do adresaru, kde je QE vyhledava

### ISSUE THREAD

**Issue by fvacek** [Quick-Event/quickbox#722]
Duvody:
1. Uzivatele potrebuji mit moznost upravovat reporty, hlavne diplomy
2. Stejne je potreba mit nejaky adresar, kde by byly uzivatelske diplomy, tak proc to do neho hned nakopirovat
3. pozor appimage se rozbali do RO adresarove struktury, takze tam uzivatelske diplomy nemohou byt
4. Ukazalo se pomerne tezke jim vysvetlit, jak to udelat, kdyz jsou diplomy v resources nebo nekde na gitu
5. Bylo by prima napsat k uzivatelskym diplomum wikistranku

**Comment by lukaskett** [comment]
Souvisí s tím to, že aktuálně není možné si definovat vlastní diplom (bez úpravy zdrojáku)? To mě totiž teď docela vypeklo, když jsem nebyl schopný rozchodit vlastní diplom.

**Comment by fvacek** [comment]
Bohuzel ano, presunuti reportu do resources byl ukvapeny krok.

**Comment by lukaskett** [comment]
Tak to je nemilé. Můžete udělat krok zpět? Jen mě to zajímá s výhledem na závody co pořádáme začátkem července jestli fci budeme moci použít.

**Comment by paukert** [comment]
Přesunutí reportů do resourců proběhlo v rámci masivního refactoringu, konkrétně v #629 (pravděpodobně v commitu https://github.com/Quick-Event/quickbox/pull/629/commits/c8adc3f7909b009706a615dc76645eb0f687a2fd). Já se k navrácení v následujících dnech asi spíše nedostanu, ale možná se najde někdo jiný.

Další otázka je, co všechno chceme vrátit zpátky. Za mě by určitě bylo dobré vrátit lístečky, diplomy a možná i startovní listiny a výsledky.

**Comment by fvacek** [comment]
Pokusim se naimplementovat variantu, kdy vse bude v resources, jako nyni, ale bude jeste overlay adresar, kam si uzivatel bude moc davat svoje soubory. To bude mit nekolik vyhod:
1. bude nam nadale fungovat appimage
2. reinstalaci QE se nepremazou user defined reports

**Comment by paukert** [comment]
Pokud to chápu správně, tak takhle to nyní máme naimplementované u lístečků - jsou v resources a uživatelé si své mohou házet do `quickevent-data/receipts`. Pokud bychom podobnou logiku přidali i pro diplomy, tak pokryjeme asi dva nejčastější případy, kdy si uživatelé upravují reporty (startovní listiny / výsledky si upravuje asi málokdo). Jedinou nevýhodu u tohoto způsobu vidím v tom, že uživatel nemá na první dobrou k dispozici soubory, ze kterých by mohl při tvorbě vycházet - možná do adresářů přidat nějaké ukázkové?

**Comment by fvacek** [comment]
zcentralizoval jsem settings (az na nastaveni receipts)

![image](https://user-images.githubusercontent.com/4949019/179423726-a76ae558-9f1f-41d3-9a1e-8b72ab359d9a.png)

1. kliknutim na button `create` se vyrobi kopie reportu z resources ve vybranem adresari, 
2. v custom reports dir si kazdy muze upravovat, co chce
3. pokud soubor v adresari jiz existuje, kliknuti na `create` ho neprepise, tim se zabrani nechtenemu prepsani poeditovanych reportu
4. pokud si nekdo v adresari `receipts` nebo `awards` vytvori dalsi soubory, budou se mu nabizet v listboxech pro vyber ustrizku/diplomu vedle tech z resources

**Comment by lukaskett** [comment]
Není mi jasný význam jednotlivých adresářů, které příkaz `Create` v Settings v záložce Reports vytvoři:
![image](https://user-images.githubusercontent.com/29544822/225154997-23ab5ee3-8797-45a1-8319-781f05174fda.png)
Chápu a ověřil jsem si, že v `Receipts` jsou lístečky. To mi funguje.

Kde je možné si nastavit diplomy? Dřív se jmenovalo `awards`. To ale v adresářích nevidím.

Jaký význam mají `Classes`, `Competitors`, `Relays`, `Runs`? Váže se k tomuto nastavení i úprava fungování service `ResultsExporter`? Ta totiž aktuálně pro štafety nefunguje.

Díky za vysvětlení.

**Comment by fvacek** [comment]
Awards budou nekde v Runs. Jinak je adressre jmenuji pokud dle jednotlivych modulu.

**Comment by lukaskett** [comment]
Super,jsou v `\Runs\qml\reports\awards`, díky.

Já moduly detailně neznám, tak proto se ptám. Zajímá mě co můžu prakticky ovlivnit. Má to vliv na exporty startovek/výsledků individuálu/štafet? Hlavně mě zajímá automatický export pomocí služby `ResultsExporter`?

**Comment by fvacek** [comment]
muzeme zavrit?

**Comment by paukert** [comment]
> Já moduly detailně neznám, tak proto se ptám. Zajímá mě co můžu prakticky ovlivnit. Má to vliv na exporty startovek/výsledků individuálu/štafet? Hlavně mě zajímá automatický export pomocí služby `ResultsExporter`.

Ovlivnit takto jdou **tiskové** výstupy (vzhled a obsah startovek, výsledků, diplomy, lístečky z vyčítání atd.)

**Comment by lukaskett** [comment]
> Ovlivnit takto jdou tiskové výstupy (vzhled a obsah startovek, výsledků, diplomy, lístečky z vyčítání atd.)

Díky moc za upřesnění. Lístečky si upravujeme, to už máme odladěné.

Dala by se šablona pro diplom upravil, aby fungovalo pro štafety?

Ještě drobnost v překladu: `Settings` -> `Nastavení`
![image](https://user-images.githubusercontent.com/29544822/226208867-a6301270-12a5-43f9-b05c-89c3b3c0c4e9.png)

**Comment by paukert** [comment]
Překlady doladím v následujícím týdnu, chybí na více místech :)

Diplomy pro štafety myslím zatím nefungují a odhaduju, že editováním souborů v awards složce se to už nezachrání (ale těmito věcmi si tedy nejsem moc jistý).

**Comment by fvacek** [comment]
Diplomy pro stafety zatim nikdo nenapsal :(

**Comment by paukert** [comment]
Na přidání podpory pro tisk diplomů u štafetových závodů jsem založil novou issue: https://github.com/Quick-Event/quickbox/issues/869

Tahle issue je jinak vyřešená a může se zavřít.
