### ISSUE TITLE
Doplnění exportu výsledků v IOF XML 3.0

### ISSUE THREAD

**Issue by lukaskett** [Quick-Event/quickbox#724]
Ahoj,

můžete, prosím, do xml exportu výsledků doplnit:

1. Organization/Name

https://github.com/international-orienteering-federation/datastandard-v3/blob/24eb108e4c6b5e2904e5f8f0e49142e45e2c5230/IOF.xsd#L590

Aktuálně je v exportu jen registračka např:
```
<Organisation>
 <ShortName>KAM</ShortName>
</Organisation>
```
Chtěl bych
```
<Organisation>
 <ShortName>KAM</ShortName>
 <Name>OK Kamenice</Name>
</Organisation>
```

2. Result/TimeBehind
https://github.com/international-orienteering-federation/datastandard-v3/blob/24eb108e4c6b5e2904e5f8f0e49142e45e2c5230/IOF.xsd#L2441
```
<StartTime>2021-08-13T16:07:00+02:00</StartTime>
<FinishTime>2021-08-13T16:33:30+02:00</FinishTime>
<Time>1590</Time>
<Position>1</Position>
<Status>OK</Status>
```

Chtěl bych
```
<StartTime>2021-08-13T16:07:00+02:00</StartTime>
<FinishTime>2021-08-13T16:33:30+02:00</FinishTime>
<Time>1590</Time>
<TimeBehind>53</TimeBehind>
<Position>1</Position>
<Status>OK</Status>
```
3. Result/ControlCard
`<ControlCard>8516925</ControlCard>`

Díky
Cáš

[exportIOF_XMLv3.zip](https://github.com/Quick-Event/quickbox/files/8404772/exportIOF_XMLv3.zip)

**Comment by fvacek** [comment]
fixed in 2.4.7
