### ISSUE TITLE
Navrhuju odebrat v XML exportu element Time při chybějícím ražení

### ISSUE THREAD

**Issue by lukaskett** [Quick-Event/quickbox#729]
Ahoj,

při chybějícím ražení (`status='Missing'`) je hodnota 0 u času oražení kontroly matoucí a při zpracování může dělat problémy. Navrhuju ji odebrat. Napříkald export SI-Droidu záznam neobsahuje a přijde mi to blbuvzdornější. Plus stejně nedává smysl s nulou počítat.

Toto:
`<SplitTime status="Missing">`
`<ControlCode>108</ControlCode>`
`<Time>0</Time>`
`</SplitTime>`

Změnit na toto odebráním elementu `Time`:
`<SplitTime status="Missing">`
`<ControlCode>108</ControlCode>`
`</SplitTime>`

To samé je u celkového výsledku, ale tam mě to tolik netrápí, i když si často říkám proč QE ukazuje výsledný čas i např. při chybějící kontrola jako rozdíl čas cíle mínus čas startu.

Pro `OK` status:
`<Result>`
`<StartTime>2022-03-30T17:24:56</StartTime>`
`<FinishTime>2022-03-30T17:49:02</FinishTime>`
`<TimeBehind>760</TimeBehind>`
`<Position>36</Position>`
`<Status>OK</Status>`
`...`
`</Result>`

Pro `MissingPunch` status:
`<Result>`
`<StartTime>2021-08-13T17:03:00+02:00</StartTime>`
`<FinishTime>2021-08-13T17:35:38+02:00</FinishTime>`
`<Time>1958</Time>`
`<Status>MissingPunch</Status>`
`...`
`</Result>`

Odebrání elementu `Time`?
`<Result>`
`<StartTime>2021-08-13T17:03:00+02:00</StartTime>`
`<FinishTime>2021-08-13T17:35:38+02:00</FinishTime>`
`<Status>MissingPunch</Status>`
`...`
`</Result>`

Cáš

**Comment by paukert** [comment]
Koukal jsem do specifikace a na ukázkové IOF XML 3.0 výsledky (https://github.com/international-orienteering-federation/datastandard-v3/blob/master/examples/ResultList1.xml) a při chybějícím ražení by měl být element `Time` ve `SplitTime` opravdu vynechaný.

Naopak element `Time` v `Result` by měl být uveden i pokud závodník nějaké kontroly neorazil viz
https://github.com/international-orienteering-federation/datastandard-v3/blob/24eb108e4c6b5e2904e5f8f0e49142e45e2c5230/examples/ResultList1.xml#L170

**Comment by otahirs** [comment]
v ukázkové souboru `Time` v `Result` sice je, ale samotný standard (aspoň dle .xsd) ho nevyzaduje.

kazdopadne v mezicasech bych ho odebral - `<Time>0</Time>` nedava moc smyslu. v `Result` bych `Time` ponechal

**Comment by paukert** [comment]
> v ukázkové souboru `Time` v `Result` sice je, ale samotný standard (aspoň dle .xsd) ho nevyzaduje.

Máš pravdu, v xsd je opravdu uvedeno `minOccurs="0"`, to jsem přehlédl.

**Comment by lukaskett** [comment]
> pro zavodnika muze byt zajimave videt ve vysledkach svuj cas, i kdyz na konci s diskem

V čem to může být zajímavé? Já osobně bych ho dal taky klidně pryč, protože je z mého pohledu matoucí. Jak může mít diskvalifikovaný závodník čas?

**Comment by otahirs** [comment]
pokud jsem narazil spatnou kontrolu, neznamená to že se nechci porovnat s ostatními závodníky. :man_shrugging: 
![Untitled](https://user-images.githubusercontent.com/24588500/178158903-16798602-1619-45fe-a2cb-f67815025aef.png)

**Comment by paukert** [comment]
V #773 jsem připravil odebrání elementu `Time` v `SplitTime` pro závody jednotlivců i štafet. U štafet jsem taky přidal atribut `status="Missing"` do elementu `SplitTime`, stejně jako to je ve výsledkách pro závody jednotlivců.

**Comment by otahirs** [comment]
ps: ono cely element Time je vlastne zbytecny, protoze kdokoliv si ho muze vypocitat jako `FinishTime` - `StartTime` (ostatne je tomu tak i v obrazku vyse :sweat_smile: ). ale v ukazce od IOF je, tak bych hlasoval pro zachovani

**Comment by fvacek** [comment]
ja hlasuji take pro zachovani ze stejnych duvodu jako Ota

**Comment by paukert** [comment]
> V #773 jsem připravil odebrání elementu `Time` v `SplitTime` pro závody jednotlivců i štafet. U štafet jsem taky přidal atribut `status="Missing"` do elementu `SplitTime`, stejně jako to je ve výsledkách pro závody jednotlivců.

Nyní v #789. Pokud jsme se dohodli na zachování Time elementu v Result, tak je tato issue vyřešená a může se po mergnutí #789 zavřít.
