### ISSUE TITLE
Statistiky závodu nefungují pro štafety

### ISSUE THREAD

**Issue by Tomaqa** [Quick-Event/quickbox#733]
Dle statistik závodu lze velmi dobře kontrolovat počet nedoběhlých závodníků => informace pro sběrače kontrol.
Toto bohužel u štafet nefunguje.
Prozatímní workaround je výpis závodníků dané kategorie, seřazení dle cílového času a sledování, kolik jich ještě žádný nemá.

(Verze 2.4.7)

**Comment by paukert** [comment]
Může se zavřít, v #381 jsou popsány i potencionální problémy se statistikami u štafet.
