### ISSUE TITLE
Řazení v pdf startovce po klubech

### ISSUE THREAD

**Issue by lukaskett** [Quick-Event/quickbox#739]
Aktuálně jsou závodníci řazení abecedně dle kategorie a následně podle startovního času.

Dalo by se přidat nastavení tisku, které by řazení umožnilo ovládat? Osobně bych totiž u startovky po klubech preferoval řazení dle startovního času.
![Screenshot_20220525-084856_Drive](https://user-images.githubusercontent.com/29544822/170285965-173239fb-fc44-439d-8232-4426e7050c22.jpg)

**Comment by arnost00** [comment]
Par ukazek jak by to mohlo vypadat ...
![2023-04-17 22_26_25-Print Report Options](https://user-images.githubusercontent.com/8378685/232623316-b808a71a-57c2-4456-a46e-690e08b2fc9d.png)

-  (class name, start time,  runner name)
![2023-04-18 00_20_47-Window](https://user-images.githubusercontent.com/8378685/232623381-8735cbb0-71b6-4548-882b-406439b2e338.png)
 - (runner name, class name, start time)
![2023-04-18 00_21_04-Window](https://user-images.githubusercontent.com/8378685/232623383-cbe89ed0-de48-4936-9c90-c6ac629ffc2f.png)
 - (start time, class name, runner name)
![2023-04-18 00_21_27-Window](https://user-images.githubusercontent.com/8378685/232623384-457c274d-285e-4865-b373-187ec6f912c4.png)

**Comment by arnost00** [comment]
Prosim o komentare, nez to pripadne commitnu a poslu do PR

**Comment by otahirs** [comment]
1. osobně bych řazení dle jména nikdy nevyužil.
2. pokud se řadí prvně dle kategorie, dávalo by mi smysl aby byla v tomto případě v exportu jako první sloupec

**Comment by arnost00** [comment]
@otahirs 
ad 1) radi se celkem pres 3 sloupce, napsal jsem vsechny 3 zakladni moznosti - netusim zda se najde nekdo kdo to vyuzije.
ad 2)zatim jsem delal zmenu jen v radeni, zmeny vzhledu zobrazeni jsem zatim ani neuvazoval. Je to otazka, nejsem si jist co je lepsi zda pro kazde radeni vlastni vzhled, nebo jeden pro vsechny. Pri novem vzhledu pro kazde radeni by mely pribyt 2 nove reporty.

**Comment by paukert** [comment]
@arnost00 ještě je tam jedna drobnost: https://github.com/Quick-Event/quickbox/pull/889/files#r1174547080

**Comment by arnost00** [comment]
@paukert aha. Dik za vsimavost. Opravim ASAP.

**Comment by arnost00** [comment]
Opraveno, je to v PR #895
