### ISSUE TITLE
Synchronizovat záznamy aktuálního závodu neumožňuje uložit jen nové přihlášky 

### ISSUE THREAD

**Issue by lukaskett** [Quick-Event/quickbox#743]
`Možnost Soubor->Importovat->ORIS->Synchronizovat záznamy aktuálního závodu` nenabízí v rozdílovém okně možnost uložit pouze nové záznamy. Uložení přepíše provedené změny (přesuny v kategoriích, poznámky, ...). Jde jen uložit a uložit bez smazaných. Třeba pro stažení dohlášek do kategorií pro veřejnost je tak nepoužitelné.

![image](https://user-images.githubusercontent.com/29544822/170646525-f99fb488-8965-462c-91a0-eb980758f9ec.png)

**Comment by lukaskett** [comment]
Úplně ideální by byl výběr co chci synchronizovat za změny (default nic). Ukázka dohlášek `P` a `HDR` a zároveň změny (vyznačené žlutě), o které jsem nechtěl přijít. Značil jsem si vyřešené požadavky na start, o což mi tolik nevadilo přijít, ale pak jsem tam měl změny kategorií a registraček, které už jsou horší.

Synchronizace probíhá jednosměrně `Oris` -> `QE`, takže nejde provedené změny propsat zpět do Orisu.

![image](https://user-images.githubusercontent.com/29544822/171281822-db0ca62b-c01c-4e5f-b865-e262d997e76b.png)

**Comment by fvacek** [comment]
Moc tomu nerozumim, single source of truth je do uzavreni prihlasek Oris a po uzavreni QE, tak jaka obousmerna synchronizace nebo import pouze nekterych zmen?

**Comment by lukaskett** [comment]
Jestli tě dobře chápu, tak to znamená, že po stažení dat do QE už Oris vůbec neřeším a veškeré změny dělám v QE. Tohle chápu a běžné to tak děláme.

Já navrhuji právě přidat možnost stáhnout ještě nové přihlášky výběrem z rozdílového seznamu. Mohlo by to fungovat obecně, ale primárně by fce byla pro tratě pro veřejnost s volným startem. Tj i po stažení dat by bylo možné provést dodatečný import vybraných záznamů/dohlášek. 

Jaký jiný usecase synchronizační fce má?

**Comment by fvacek** [comment]
Ucel synchronizace je dotahnout z Orisu dodatecne zmeny, slo by take cely zavod smazat a naimportovat ho znovu, ovsem poradatel by tim prisel o informace, ktere Oris neobsahuje, jako jsou delky trati atd.

Kdybychom implementovali funkci `pouze nove zaznamy`, co by se stalo se zmenami v Orisu, ktere jsou jinak nez v QE? Vyhodily by se? Proc by je tam potom nekdo dopisoval? Je to nebezpecna funkcionalita, ktera by vedla k situacim typu: "V Orisu jsem to videl, tak jak to, ze to tam nemate".

**Comment by lukaskett** [comment]
Chápu, že hlavním zdrojem pravdy je na začátku Oris, stažením dat a založením závodu v QE se zdrojem pravdy v mém pohledu stává QE - dělám startovky, označuju si vyřešené požadavky na start (edituji/přidávám poznámky), provádím změny dle dodatečných požadavků (měním kategorie, přidávám závodníky, ...). Přístup k tomu všemu mám jen já, případně člověk s QE. Fce synchronizace mi upravené/přidané poznámky přepíše "pravdou" z Orisu.

Proto jsem si myslel, že by bylo šikovné mít možnost se ještě podívat na změny v Orisu a případně si vybrané záznamy stáhnout. Změny by do Orisu zanesl dle domluvy např. zpracovatel přihlášek, který nemá možnost udělat změnu přímo v QE.

Chápu na co narážíš a co se ti nelíbí. Myslel jsem si, že fce `Synchronizovat záznamy aktuálního závodu` má trošku jiný způsob fungování. Takhle to beru a zavírám. Upravím podle toho svojí práci s daty v Orisu a QE. Dle mého je fce velmi málo použitelná, když slouží jen k prostému přepsání dat v QE db tím, co je v Orisu (tvůj `Single source of truth`).
