### ISSUE TITLE
Nepovedené vyčtení SIACu

### ISSUE THREAD

**Issue by lukaskett** [Quick-Event/quickbox#744]
Při vyčítání se mi jedinkrát stalo, že se nepodařilo správně vyčíst čip, ačkoliv průkazně obsahoval data. Lísteček co vyjel vypadal takto:
![jardaHavlikVycetek](https://user-images.githubusercontent.com/29544822/171054622-a145e5cd-5869-452e-a0b7-ab525823ed06.jpg)

a data v čipu dle QE takto:

![jardaHavlikDataCipQE](https://user-images.githubusercontent.com/29544822/171054681-6cfbfa72-da4d-4bed-8810-55aa01b87ebd.jpg)

Po okamžitém vyčtení v SPORTident Configu se ukázalo:
![jardaHavlikCip](https://user-images.githubusercontent.com/29544822/171054749-0fad5e3c-003f-48bd-ade3-8d1f0d822bbb.png)

Situaci jsem vyřešil smazáním čipu u závodníka, opakovaným vyčtením čipu a přiřazením vyčtení k závodníkovi. Lísteček byl nakonec úplně v [pořádku](https://oris.orientacnisporty.cz/runner_split.php?sort=4&classid=153893&compid=6739).

Předpokládám, že s tím nejde nic dělat, tak jen přikládám dokumentaci, že není třeba panikařit a jde vyřešit opakovaným vyčtením.

**Comment by fvacek** [comment]
Smazani cipu zavodnika by na vycitni nemelo mit zadny vliv, opakovane vycteni se samozrejme muze povest lepe.

**Comment by lukaskett** [comment]
ok, chápu, vytvořil jsem pro evidenci.
