### ISSUE TITLE
Export into xml - need to escape &<>'" characters

### ISSUE THREAD

**Issue by xkenia** [Quick-Event/quickbox#751]
When export into xml format (at least startlist) it is needed to escape &<>'" characters.

https://www.xmltutorial.info/xml/special-characters-in-xml/

```
<Organisation>
	<ShortName>RCP</ShortName>
	<Name>RC&P TEAM Bratislava</Name>
</Organisation>
```

Note: to check this, xml is not valid with "&" inside (try to open in ay xml viewer/browser), once it is corrected, xml is valid.

**Comment by arnost00** [comment]
Koukal jsem ze ORIS to v prihlaskach dela dobre.
`<Name>RC&amp;P TEAM Bratislava</Name>`

**Comment by arnost00** [comment]
PR #756

**Comment by paukert** [comment]
Otestováno, znak `'` není oescapován.

![obrazek](https://user-images.githubusercontent.com/15065907/175811669-2bdf8987-4e30-452d-8c4a-7ddc22e3a604.png)

**Comment by arnost00** [comment]
Koukal jsem na XML podporu v QT, trida QXmlStreamWriter a ten pri zapisu znak ``'`` neprevede. Ulozi se :
``<Name>&lt;&gt;&quot;&amp;'</Name>``
se zobrazi se :
``Name = <>"&'``

Je opravdu potreba v XML kodovat i ``'`` ?

**Comment by xkenia** [comment]
Pokud je xml validni, tak bych rekl, ze escapovat ' nutne neni.

**Comment by arnost00** [comment]
Ono kdybychom na zapis XML pouzivali Qt objekty QXmlStreamWriter nebo QDomDocument tak by to za nas pri ukladani resily primo ty objekty. Maji escapovani zahrnuto v sobe.

**Comment by paukert** [comment]
Projel jsem to několika validátory a žádnému `'` nevadí, takže můžeme asi zavřít :)

**Comment by arnost00** [comment]
Prosim o znovu otevreni. Pouzite reseni toho problemu nam poskodilo HTML exporty :(
Je tam problem minimalne s ``&nbsp;``
Vysledek :
![html_export_1](https://user-images.githubusercontent.com/8378685/182480400-7219f72a-8ce7-4669-baa5-b7e0adb06cb7.PNG)
![html_export_2](https://user-images.githubusercontent.com/8378685/182480405-6f4c6128-6ca5-41f1-8075-d9f031e430e6.PNG)

Zdrojovy kod HTML:
![html_export_3](https://user-images.githubusercontent.com/8378685/182480609-9f468b1f-e574-4c7b-80e0-a9af1efb573c.PNG)

**Comment by arnost00** [comment]
Idealne je potreba aby se ``&nbsp;`` ne/preformatovalo tak aby jej html parsery jeste umely spravne zpracovat. Mozna se to tyka i dalsich znaku, ale aktualne vime hlavne o tom ``&nbsp;``
Kdyz jsem delal puvodni opravu tak me vubec nenapadlo ze to bude formatovat i html, toho jsem si tehda nevsiml.
Me se zatim "pekne" reseni nepodarilo vymyslel.
Jedno z reseni bylo ze by se to escapovani u html vypnulo, protoze zatim dela spis skodu nez uzitek. Ale neni to idealni.
Reseni ktere pouzil Ota je zajimave, takove me nenapadlo.

**Comment by otahirs** [comment]
spravne reseni je nepouzivat pri generovani html kodu na odsazeni `&nbsp;`  a zcela ho nahradit css styly

**Comment by arnost00** [comment]
> nestacilo by tedy ty `&nbsp;` smazat 🤔 ?
To me teda vubec jako reseni nenapadlo 😄 ... to se budu muset kouknout do kodu.

**Comment by fvacek** [comment]
podle me by stacila mezi temi odkazy obyc mezera `SP` `0x20`, bohuzel uz si nevzpomenu, proc jsem to tenkrat udelal takhle :(

**Comment by arnost00** [comment]
Ja zil v domeni ze tam ten nezlomna mezera je z nejakeho nutneho duvodu, takze me ani nenapadlo ji odstranovat.
Sveho casu se na formatovani hojne pouzivala, tak mi to neprislo divne.

**Comment by otahirs** [comment]
> bohuzel uz si nevzpomenu, proc jsem to tenkrat udelal takhle :( 

Myslím že prohlížeče aspoň kdysi nemusely vykreslit html element pokud byl prázdný a tedy se do něj házela např. `&nbsp`.
Ale řekl bych že dnes to minimálně u tabulek problém není.

**Comment by fvacek** [comment]
No je to mozny, jenom na nej ted nemuzu prijit :)

**Comment by fvacek** [comment]
fixed in 2.6.14
