### ISSUE TITLE
Ve vlastní šabloně lístečku mi nefunguje vložení obrázku

### ISSUE THREAD

**Issue by lukaskett** [Quick-Event/quickbox#757]
Ahoj,

měli jsme upravenou šablonu lístečku, kde jsme si vkládali qk kód s linkem na liveresultaty. S novější verzí mi šablona ([receipts.zip](https://github.com/Quick-Event/quickbox/files/8985557/receipts.zip)) přestala fungovat.

První problém s umístěním custom lístečku mi pomohl vyřešit @otahirs, nově je totiž default cesta v `C:\QuickEvent\quickevent-data\receipts` a po instalaci se adresář nevytvoří.

V logu QE je:
```log
2022-06-25T22:54:01.934	Warning		ERROR load image: file:/C:/QuickEvent/quickevent-data/receipts/images/qr-sobota.png	reportitemimage.cpp	183
2022-06-25T22:54:01.934	Warning		QImage('file:/C:/QuickEvent/quickevent-data/receipts/images/qr-sobota.png') constructor error.	reportitemimage.cpp	191
2022-06-25T22:54:01.936	Warning		Printing an empty image	reportitemimage.cpp	309
```

Obrázek mám ve správné cestě. Qml snippet v místě obrázku:
```qml
Frame {
	width: "%"
	halign: Frame.AlignHCenter
	hinset: 0	
	vinset: 1
	topBorder: Pen { basedOn: "black1" }
	bottomBorder: Pen { basedOn: "black1" }
	Image {
		width: 60
		dataSource: "./images/qr-sobota.png"
	}
	Para {
		width: "%"
		text: "Online výsledky na https://liveresultat.orientering.se/followfull.php?lang=cz&comp=20474"
	}
}

**Comment by lukaskett** [comment]
Ještě mě napadlo, že default lístečky Classic a Cassic Lotery nejsou v adresáři, takže se v nich nejde inspirovat pro vytvoření vlastního lístečky. To mi přijde ,že by mělo být. Používám verzi QE 2.4.7.

**Comment by paukert** [comment]
> Ještě mě napadlo, že default lístečky Classic a Cassic Lotery nejsou v adresáři, takže se v nich nejde inspirovat pro vytvoření vlastního lístečky. To mi přijde ,že by mělo být. Používám verzi QE 2.4.7.

Jo, tohle teď není moc šikovné, týká se to např. i diplomů viz issue https://github.com/Quick-Event/quickbox/issues/722.

**Comment by paukert** [comment]
@lukaskett zkusil bys cestu k tomu obrázku nahradit za obsolutní + případně vyměnit lomítka za zpětná lomítka a escapovat? Myslím, že jsem měl stejný problém, a tohle mi teď funguje:

`dataSource: "C:\\QuickEvent\\quickevent-data\\receipts\\private\\qr-code.png"`

(obrázek mám v C:\QuickEvent\quickevent-data\receipts\private\qr-code.png)

**Comment by lukaskett** [comment]
> @lukaskett zkusil bys cestu k tomu obrázku nahradit za obsolutní + případně vyměnit lomítka za zpětná lomítka a escapovat? Myslím, že jsem měl stejný problém, a tohle mi teď funguje:
> 
> `dataSource: "C:\\QuickEvent\\quickevent-data\\receipts\\private\\qr-code.png"`
> 
> (obrázek mám v `C:\QuickEvent\quickevent-data\receipts\private\qr-code.png`)

díky za tip, už to běhá.
