### ISSUE TITLE
Nejnovější dev build z actions nejde na W10 spustit

### ISSUE THREAD

**Issue by paukert** [Quick-Event/quickbox#758]
https://github.com/Quick-Event/quickbox/actions/runs/2556216254

![obrazek](https://user-images.githubusercontent.com/15065907/175809382-f6ed3425-fb17-4ec9-abaf-49810ecd9c9e.png)

Update: verze bez posledního commitu (https://github.com/Quick-Event/quickbox/actions/runs/2328375383), který opravuje escapování mi spustit jde. S ohledem na provedené změny si ale nemyslím, že samotné změny od @ arnost00 by to měly způsobovat.

**Comment by paukert** [comment]
V Github actions se `windows-latest` změnilo z `windows-2019` na `windows-2022` - bude potřeba důkladněji prozkoumat a zjistit přesnou příčinu problému (https://github.com/actions/virtual-environments/blob/main/images/win/Windows2022-Readme.md).

Dočasný fix #761

**Comment by fvacek** [comment]
https://stackoverflow.com/questions/71331756/zst28-throw-bad-array-new-lengthv-trying-to-import-c-code-in-python-after-co

**Comment by fvacek** [comment]
Necham issue jeste otevrenou, bylo by dobry, kdyby nam to fungovalo i s `windows-2022`

**Comment by paukert** [comment]
Souhlas, omylem jsem pojmenoval PR jako fix a sám jsem issue už potom nemohl otevřít, díky.

**Comment by fvacek** [comment]
Ma nekdo windows 22, aby to mohl vyzkouset, debugging na CI je dost nesikovny?

**Comment by jmacura** [comment]
Windows Server 2022 sice nemám (a asi nikdo, kdo to tady sleduje mít nebude), ale mám Win 10 21H1 (build 19043.1766), což je stejně asi podstatnější, protože kdo by chtěl instalovat QE na serveru...

Potvrzuji, že výše odkazovaný build https://github.com/Quick-Event/quickbox/actions/runs/2556216254 mi hází stejnou chybu jako @paukert, ale poslední build https://github.com/Quick-Event/quickbox/actions/runs/2556216254 nainstalovat jde.

**Comment by fvacek** [comment]
a neni to tim, ze posledni build obsahuje quick-fix? Tady by asi nejvic pomohlo, spustit build na tvem stroji a zkusit ho spustit. Pravdepodobne to pujde, pak bude nutne zjistit, cim se lisi od https://github.com/Quick-Event/quickbox/actions/runs/2556216254

**Comment by arnost00** [comment]
Problem se zdati byt v libstdc++-6.dl
Mezi 2019 a 2022 doslo ke zmene verze Mingw z 8.1.0 -> 11.2.0
Kdyz v testovaci instalaci nahradim "vadne" dll, verzi z Qt baliku (cesta Tools\mingw1120_64\x86_64-w64-mingw32\lib )
Tak mi QE najede. 
Ale kde se do instalace vezme jine dll to mi neni jasne.

Pri pohledu do "vadne" dll a quickevent.exe nesedi ani adresy, namatkou : 
Prijde mi pri pohledu do exe a pohledu do libstdc++-6.dll jak kdyby k sobe nepatrili. 
Exe : ```
        938   _ZNKSt5ctypeIcE13_M_widen_initEv
        959   _ZNKSt6locale2id5_M_idEv
       1086   _ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE7compareEPKc
```
Dll : 
```
      938   0x0002E090    _ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE13find_first_ofERKS4_y
      959   0x0002E4C0    _ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE4findERKS4_y
    1086   0x00030930    _ZNKSt7__cxx118messagesIcE7do_openERKNS_12basic_stringIcSt11char_traitsIcESaIcEEERKSt6locale
```

**Comment by arnost00** [comment]
Zda se ze problem je v tom ze se v 2022 builduje s Mingw 11.2.0 a do instalace se nakopiruji dll z verze 8.1.0
Proc to jsem zatim neobjevil
Tyka se to minimalne : libwinpthread-1.dll, libgcc_s_seh-1.dll, libstdc++-6.dll

**Comment by paukert** [comment]
Myslím si, že by to mohlo mít určitě souvislost s parametrem `arch` viz:
https://github.com/Quick-Event/quickbox/blob/a72f24175ab7ab1fda65dac6d18edadac60a2cd6/.github/workflows/c-cpp.yml#L101-L107

Dokumentace: https://github.com/jurplel/install-qt-action#arch

**Comment by arnost00** [comment]
Co jsem hledal tak to vypada ze Qt5 se s vyssim mingw uz nebuilduji. S vyssim mingw se builduje az Qt6. 
Rikal jsem si zda by nemohlo pomoct pridani `libwinpthread-1.dll`, `libgcc_s_seh-1.dll`, `libstdc++-6.dll` do seznamu v :
https://github.com/Quick-Event/quickbox/blob/a72f24175ab7ab1fda65dac6d18edadac60a2cd6/.github/workflows/c-cpp.yml#L76-L84

**Comment by fvacek** [comment]
za zkousku nic nedas, urcite to vyzkousej nebo zkus prijit na to, jak ten CI build pro Qt5 spustit s MinGW8.1

**Comment by jmacura** [comment]
> a neni to tim, ze posledni build obsahuje quick-fix?

Měl jsem za to, že poptávka byla právě po tom, aby někdo otestoval ten quick-fix.

**Comment by arnost00** [comment]
Tak jsem zkusil ten PR #777 a bohuzel to nepomohlo. Porad jsou tam ty DLL z mingw 8.1.0

**Comment by arnost00** [comment]
Zkousel jsem i nacist jine mingw - take se nezadarilo - [odkaz na actions](https://github.com/arnost00/quickbox/actions/runs/2683608998)

**Comment by paukert** [comment]
Vyzkoušeli byste prosím tuhle verzi: https://github.com/Quick-Event/quickbox/actions/runs/2685231962

Do CI jsem přidal downgrade MinGW na 8.1 a minimálně u mě se to zdá být funkční.

**Comment by jmacura** [comment]
> Vyzkoušeli byste prosím tuhle verzi: https://github.com/Quick-Event/quickbox/actions/runs/2685231962
> 

Nainstalovat jde, spustit jde.

**Comment by paukert** [comment]
Super, díky za zpětnou vazbu. Označuju PR jako ready na merge :)
