### ISSUE TITLE
Viditelné debugovací tlačítko v záložce Vyčítání SI čipů

### ISSUE THREAD

**Issue by paukert** [Quick-Event/quickbox#760]
Nevím, zda je to chtěné, ale v současném dev buildu je viditelné debugovací tlačítko v záložce Vyčítání SI čipů. Do oficiálního releasu by bylo určitě dobré ho schovat.

![obrazek](https://user-images.githubusercontent.com/15065907/175811357-6a969e68-f9c5-4aab-b7ca-ed4584e48a34.png)

**Comment by fvacek** [comment]
Rekl bych, ze je to tim, ze se dev build preklada jako debug a ne jako release

**Comment by paukert** [comment]
Tak je to má chyba, pardon - tohle bude asi screen z mého debug buildu. Build z actions je překládán jako release a tlačítko neobsahuje viz

https://github.com/Quick-Event/quickbox/blob/3e7811c6820df58d0c6173912e8ff464babe13b6/.github/workflows/c-cpp.yml#L111
