### ISSUE TITLE
Záložka Úseky / Etapy nereaguje na změnu etapy

### ISSUE THREAD

**Issue by frostidllo** [Quick-Event/quickbox#767]
Když v záložce Úseky / Etapy změním vlevo nahoře etapu z E1 na E2, tak se tabulka nijak nezmění, dokonce ani tlačítko refresh nic neudělá. Musím tedy překliknout v menu vlevo například na Vyčítání a zpět na Úseky / Etapy a pak už je tabulka aktuální.

Nicméně je to strašná otrava na to pořád myslet, abych si náhodou neudělal nějakou změnu startu v jiné etapě. Především když řeším požadavky na start a mám v hlavně 3 registračky, které mám dát k sobě / od sebe a do toho si musím hlídat, abych to dělal ve správné etapě.

PS: opravdu to přepínám tam, kde se má, nepřepínám aktuální etapu zcela vlevo nahoře :)

**Comment by paukert** [comment]
Tohle jsem v únoru opravoval v rámci https://github.com/Quick-Event/quickbox/pull/707. Zkusil bys to nasimulovat i na nejnovejší vývojářské verzi, kterou lze stáhnout třeba z actions? (https://github.com/Quick-Event/quickbox/actions/runs/2564726488)

**Comment by frostidllo** [comment]
Zkusím až budeme mít po pořádání (příští týden) a nebudu se bát s tím experimentovat

**Comment by fvacek** [comment]
zkousel jsem 2.6.4 a chybu se mi nepodrilo zreprodukovat

**Comment by lukaskett** [comment]
Plánujete udělat nějaký oficiální release? Chápu, že tady všichni kdo tomu trošku rozumí jedou z actions, ale ne každý má účet na githubu a od posledního releasu uběhl víc jak půlrok a zase je tam dost úprav.

Osobně bych ještě počkal na #722, protože lístečky a diplomy věřím, že používá víc lidí. Dík.

**Comment by paukert** [comment]
Myslím si, že bychom určitě mohli udělat oficiální release po HSH, kde bude QE poměrně dobře otestován.

**Comment by fvacek** [comment]
na #722 pracuji, ofiko release bych rad udelel po usporadani HSH, protoze se tam dost veci otestuje

**Comment by fvacek** [comment]
Ještě dodělávám nové settings, což bylo potřeba na custom reports #722  a bude release.

**Comment by paukert** [comment]
@frostidllo zkoušel jsi to? Jak to případně dopadlo? 🙂

**Comment by paukert** [comment]
Mělo by být opraveno, můžeme tedy uzavřít.
