### ISSUE TITLE
IOF XML missing `Name` element in Organization

### ISSUE THREAD

**Issue by otahirs** [Quick-Event/quickbox#775]
in the `Organization` element, it is mandatory to include the `Name`  
https://github.com/international-orienteering-federation/datastandard-v3/blob/24eb108e4c6b5e2904e5f8f0e49142e45e2c5230/IOF.xsd#L590-L596

we provide only the `ShortName`, which is optional. the required `Name` element is missing

**Comment by arnost00** [comment]
`runsplugin.cpp` function `exportResultsIofXml30Stage` & `exportStartListStageIofXml30` has `ShortName` & `Name`
Where is the `Name` missing ?

**Comment by arnost00** [comment]
Duplicate #724
