### ISSUE TITLE
Nenahrávat buildy QE k pull request workflows

### ISSUE THREAD

**Issue by paukert** [Quick-Event/quickbox#779]
Přijde mi trošku nebezpečná vlastnost, že se buildy QE nahrávají k workflows, které byly spuštěny na základě vytvoření pull requestu.

Chtěl bych navrhnout, aby se u vytvořených PR nadále CI spouštělo a zkusil se vytvořit build, ale už se tento build k dané workflow nenahrál (u PR buildů nemuselo ještě proběhnout code review, případně může jít ještě i o rozpracovanou PR).

Pro toto omezení by mělo být možné využít proměnnou prostředí `GITHUB_EVENT_NAME` viz https://docs.github.com/en/actions/learn-github-actions/environment-variables

**Comment by fvacek** [comment]
Takhle ale zase mame moznost nechat PR otestovat nekoho na jine platforme. Co ti prijde nebezpecne? Ze si nekdo muze stahnout build k PR a zkouset na nem neco poradat?

**Comment by paukert** [comment]
> Co ti prijde nebezpecne? Ze si nekdo muze stahnout build k PR a zkouset na nem neco poradat?

Jo, přesně z tohoto důvodu. Myslím si, že QE současné době používají i uživatelé, kteří neznají úplně koncepty Gitu (větví) a z actions stránky by tedy mohli stáhnout první položku ze seznamu. Možná je to ale jen můj pocit - proto jsem založil tuto issue, aby svůj názor mohli napsat i ostatní.

> Takhle ale zase mame moznost nechat PR otestovat nekoho na jine platforme.

Jo, o tuto možnost bychom tímto přišli.

**Comment by otahirs** [comment]
Nezaregistrovani uživatelé nemohou stahovat z GitHub actions.

Oceňuju možnost vyzkoušet si MR bez toho mít zrovna nainstalovaný Qt toolchain

**Comment by paukert** [comment]
> Nezaregistrovani uživatelé nemohou stahovat z GitHub actions.

O tomto omezení vím a určitě tato limitace popisované riziko výrazným způsobem snižuje.
