### ISSUE TITLE
Deaktivované tlačítko 'Vložit řádek' po aktivování a deaktivování filtru

### ISSUE THREAD

**Issue by lukaskett** [Quick-Event/quickbox#784]
Ahoj,

pokud v záložce _Závodníci_ provedu libovolné filtrování (dle jména, čipu, ...), které vrátí nějaké řádky a následně kliknu na řádek, tak se deaktivuje tlačítko pro přidávání nového závodníka. S tím jsem jakž takž ok, i když moc nechápu proč.

Když ovšem zruším filtr (vymažu nebo zmáčknu křížek), tak je tlačítko stále deaktivované a pomůže jen přepnutí na jinou záložku a zpět nebo přepnutí kategorie, abych mohl opět přidávat nové závodníky.

Stejné chování je v záložce _Kategorie_, tam to tolik neomezuje jako při dohlašování závodníků.

**Navození chyby:**

- filtrování

![image](https://user-images.githubusercontent.com/29544822/181103081-fa7d10a1-e71d-4ebe-88f7-493ecf00dc80.png)

- výběr řádku

![image](https://user-images.githubusercontent.com/29544822/181103110-0e4faa0a-7190-4ed7-bd26-6770c07ccc6d.png)

- Zrušení filtru

![image](https://user-images.githubusercontent.com/29544822/181103159-d0907cc6-8206-4f06-85e5-feb813872e3d.png)

**Comment by arnost00** [comment]
Neni to podobny problem jako v #712 a #679 ?

**Comment by lukaskett** [comment]
Je to duplicita s #679, neviděl jsem, zavírám. Zkoušel jsem na verzi 2.4.7, která už je očividně opravdu stará. Doufám, že kluci po HSH vydají oficiální release.

Kontrolně jsem vyzkoušel ještě na verzi 2.6.6 a tam je to již ok.

**Comment by fvacek** [comment]
ja mam pocit, ze jsem to uz opravoval

**Comment by lukaskett** [comment]
Jo opravoval, je to vyřešené v novější verzi. Testoval jsem. Už očekávám nový oficiální release, aby se to neletlo.
