### ISSUE TITLE
Run flags improvements

### ISSUE THREAD

**Issue by otahirs** [Quick-Event/quickbox#796]
1. whats the diference bewtween the first two options?
![image](https://user-images.githubusercontent.com/24588500/187092662-ffa0ef6a-f9bd-4efa-945b-b09450db2935.png)

---
2. the top check box `Disqualified` gets confusing really quickly. It gets selected automatically, but also can be un-checked afterwards.

**Comment by arnost00** [comment]
> 1. whats the diference bewtween the first two options?

Description:
`Disqualified` - i think this is summary flag. It means that runner is not OK and hasn't position in results.
`Disqualified by organiser` - flag which marks that runner is disqualified for some other reason (crossing olive color etc).
Difference:
`Disqualified` is set by program in readout or by check other DQ reasons (DNS, DNF, MP, NC, DISQ ...)
`Disqualified by organiser` is one of disqualification reason

**Comment by arnost00** [comment]
> 2. the top check box Disqualified gets confusing really quickly. It gets selected automatically, but also can be un-checked afterwards.

The dialog has some problems with DQ flags. We must improve this logic.
And add some DQ logic description for "normal" user. 
Not all checkbox has registered `updateState`, but the methon check all checkboxes.

Maybe first checkbox `Disqualified` make readonly ? And the other can user change manualy ?

**Comment by otahirs** [comment]
Maybe we could hide the disqualified checkbox and instead of it show something like `Result Status`, > `Ok` when ok and > `Disqualified` when one of the disq reasons/flags is selected.

**Comment by fvacek** [comment]
The reason, why the `Disqualified` checkbox is not read only is following scenario.

Competitor has not punched control xy in SI card but there is an evidence, that he was there. In this case the competitor can clear the `Disqualified` flag set automatically by card checker.

Another possibility is to clear the `mispunch` flag and make `Disqualified` RO. This is maybe more intuitive, but information that the card is missing the punch is cleared.

**Comment by otahirs** [comment]
i would rather miss the information (if its deliberately cleared), it can be re-evulated if neede.
In current state no user without deep knowledge of the codebase cannot deduce how to use this dialog.

my suggestion
```
Run status
---------------------------
status: Ok | Disqualified
[ ] Miss punch
[ ] Bad check
[ ] Did not start
[ ] Did not finish
[ ] Other (dsq by organizer)
--------------------------
[ ] Not competing  <--- in case this is checked, the upper part of widget is greyed out and disabled 

```
