### ISSUE TITLE
Problém se štafetami

### ISSUE THREAD

**Issue by BincikM** [Quick-Event/quickbox#807]
Prosím o radu, včera jsem pořádal klasiku a vše bylo OK, dnes jsem pořádal štafety (vše staženo z ORISU) a při vyčítání mi nepřiřadil údaje k danému závodníkovi. Navíc jsem zjistil, že jsou časy z vyčítání posunuty o 12 dopředu, místo 12:01:01 je ve výpisu 00:01:01.
Mohu zaslat vyexportovaný celý závod.
Moc děkuji
Milan

**Comment by lukaskett** [comment]
Ahoj, přilož prosím vyexportovaný qbe soubor. Na jaké verzi QE?

**Comment by BincikM** [comment]
Ahoj, závod byl pořádán na verzi 2.4.7 

Data pošlu odpoledne, mám je na jiném notebooku.

 

S pozdravem
Milan Binčík

**Comment by BincikM** [comment]
Ahoj, posílám exportovaný závod

Milan

**Comment by fvacek** [comment]
Prilohu jsem nenasel, ale posunuti casu o 12 hodin vypada na spatne nastaveni startu zavodu.

**Comment by BincikM** [comment]
Start závodu byl nastaven na 10:00.

 

S pozdravem
Milan Binčík

**Comment by lukaskett** [comment]
Přílohu jsem tay nenašel. Asi se budeš muset na Github přihlásit, aby se export závodu přiložil. poslední dvě odpovědi jsou emailem.

**Comment by BincikM** [comment]
Příloha.
[stafety_1.zip](https://github.com/Quick-Event/quickbox/files/9643454/stafety_1.zip)
