### ISSUE TITLE
XML export time format differences

### ISSUE THREAD

**Issue by otahirs** [Quick-Event/quickbox#808]
The function used for converting datetimes to string in XML export is not the same:

Individual startlist
`2022-01-22T12:00:00.000Z`

Individial resutls
Relay startlist
Relay results
`2022-01-22T13:00:00+01:00`

Both formats are technically correct, but we should unify the export format.
The version with time zone makes more sense to me, to do not lose time zone information.

**Comment by arnost00** [comment]
@otahirs Do you know which time zone is in export ? Time zone of event or time zone of computer ? 
It can be two different values. 
I think computer with different TZ (from event TZ) will have problem with export to ORIS.

For example in entries XML from ORIS, StartTime/Time is in local time without TZ (`<Time>10:30:00</Time>`)
But in createTime of whole entries XML from ORIS TZ is used (`createTime="2022-09-26T00:59:06+02:00"`)


> The version with time zone makes more sense to me, to do not lose time zone information.

I agree, better with TZ information

**Comment by fvacek** [comment]
It is always better to organize event on computer with the same TZ as the event has. So I think that we can presume, that local time on computer has the same TZ as event.

Time itself cannot have TZ, it doesn't make sense. Only date-time can have TZ.
