### ISSUE TITLE
OResults service - Better error message when request fails to be delivered.

### ISSUE THREAD

**Issue by otahirs** [Quick-Event/quickbox#811]
>Tušíš jak kvalitní připojení jste měli? LTE, 4G? My jsme dnes pozorovali problémy při uploadu pouze přes službu OResults. Po chvíli upload proběhl zase úspěšně. Chování jsme přisuzovali slabšímu mobilnímu připojení. Vliv na chod vyčítání jsem nepozoroval. Možná to spolu nesouvisí a je to spíš na jinou issue.
Fotku logu přímo z akce:
![log_oresults](https://user-images.githubusercontent.com/29544822/193473285-924e27b0-bdc2-40c5-b981-9ce8a5874ef2.jpg)

_Originally posted by @lukaskett in https://github.com/Quick-Event/quickbox/issues/809#issuecomment-1264719245_

**Comment by fvacek** [comment]
Koukal jsem do kodu a problem je, ze se neloguje errorString(), takze nevime, proc to vlastne nedopadlo, opravil jsem to, tak jestli nekdo muze, at to vyzkousi, mohli bychom byt chytrejsi. https://github.com/Quick-Event/quickbox/commit/33f00f45755b73cecb977ecf8a10809d17d2a08f

**Comment by otahirs** [comment]
kdybych se mohl assignout, tak se assignu. 
server vraci chybovy text, kdyz se mu na poslanych datech neco nelibi, proto zde bylo `QString(reply->readAll())`  
pokud vsak request selze jiz drive, tak dava smysl vypsat error z `reply->errorString()`
vyzkousim a asi prepisu na `QString(reply->readAll())`, pokud je prazdne tak na `reply->errorString()`. musim otestovat

**Comment by fvacek** [comment]
> kdybych se mohl assignout, tak se assignu. server vraci chybovy text, kdyz se mu na poslanych datech neco nelibi, proto zde bylo `QString(reply->readAll())` pokud vsak request selze jiz drive, tak dava smysl vypsat error z `reply->errorString()` vyzkousim a asi prepisu na `QString(reply->readAll())`, pokud je prazdne tak na `reply->errorString()`. musim otestovat

zkusim to nejak nakonfigurovat, aby jsi mohl
