### ISSUE TITLE
[Discussion] Removal of Receipts module

### ISSUE THREAD

**Issue by otahirs** [Quick-Event/quickbox#818]
As we moved the printing settings into the centralized settings, there is no benefit in keeping the Receipts module as all options are also available in the Card reader section (apart from the `print new` button).  
My question is if we should aim to remove the Receipts module to simplify the UI.

**Comment by fvacek** [comment]
QE allows to print receipts on different machine than one, which is reading receipts. I do not know, if this should be a case for some organizers.
