### ISSUE TITLE
 [Discussion] Export startovky do aplikace pro startery?

### ISSUE THREAD

**Issue by arnost00** [Quick-Event/quickbox#823]
Pro nase startery jsem delal experimentalni export z QE pro aplikaci [StarterClock](https://www.tak-soft.com/products/sport/starterclock/).
Nevim zda je vubec zajem takovou funkcnost v QE mit ?

Cela funkcnost je jeden CSV export startovky. 
K nahlednuti u me, vetev [starter_clock_sime_export](https://github.com/arnost00/quickbox/tree/starter_clock_sime_export)

**Comment by fvacek** [comment]
Ja myslim, ze to neni nic proti necemu, jestli to budes udrzovat, dame to tam.

**Comment by arnost00** [comment]
Dobre. Nachystam PR.

**Comment by arnost00** [comment]
Vytvoren PR #834

**Comment by arnost00** [comment]
Uprava je v hlavni vetvi QE.
