### ISSUE TITLE
 [Discussion] tlacitko Test Connection v nastaveni

### ISSUE THREAD

**Issue by arnost00** [Quick-Event/quickbox#826]
Tlacitko `Test Connection` v Settings > Card Reader pri svem zavolani pouziva hodnoty v `settings` a vubec nebere ohled na to zda jsem zmenil nejake hodnoty v dialogu nad nim.
To je spravne chovani ? 
Za me to pusobi lehce zmatene. Protoze pokud zmenim nejake hodnoty musim zavrit a pak otevrit dialog znovu abych se mi `Test Connection` zavolalo nad aktualnimi hodnotami.

![](https://user-images.githubusercontent.com/8378685/200206967-6f250c3b-1f09-404a-b040-73d33c01746d.png)

Verze QE 2.6.11

**Comment by fvacek** [comment]
to je urcite chyba

**Comment by fvacek** [comment]
fixed in 2.6.12
