### ISSUE TITLE
Startovní časy dalších úseků při štafetách se po přepočítání časů z vyčítání nepřepíší

### ISSUE THREAD

**Issue by Osin01** [Quick-Event/quickbox#829]
Narazil jsem na menší problém při nestandardním průběhu závodu štafet.
Na oddílových štafetách jsem změnil start prvních úseků až zpětně (ostartovali jsme později). 
Mezitím se mi stihlo vyčíst i několik lidí z druhého úseku, takže už měli přiřazený startovní čas podle doběhnutí prvního úseku (běžel jsem taky).
Po přepočtení časů ze záložky vyčítání se jim startovní čas nezměnil, pokud byl již vyplněný. Musel jsem jim startovní časy vymazat, potom to fungovalo, tak jak bych čekal. Je to asi nestandardní případ, ale logicky bych čekal, že se po přepočtení vyčítání opraví i startovní časy ostatních úseků. 
Dost dlouho mi trvalo, než jsem pochopil, proč mají některé štafety delší celkový čas, než by měly mít.

Když nad tím teď přemýšlím, je to asi logické, aby se např. nezměnil čas hanba startu, ale pokud by existoval nějaký návod pro štafety, bylo by dobré to tam napsat, dokážu si představit, že se start prvních úseků může měnit zpětně i na velkých závodech.

**Comment by fvacek** [comment]
jj, je to tak, jak pises, vcetne toho navodu. Mame nekolik (asi 2 ceske a 1 anglicky https://github.com/Quick-Event/quickbox/wiki ) navody k QE, ale nikdo se o ne soustavne nestara, ja na to nemam cas. Chtelo by to sjednotit na jeden cesky a jeden anglicky navod, kam by kazdy prispel, pokud necemu nerozumi nebo se mu stane to, co tobe. Ale to je idealisticka predstava. Kazdopadne, kdyby se ti chtelo, mohl bys napsat do https://github.com/Quick-Event/quickbox/wiki/QuickEvent-Users-Guide-CZ kapitolu o stafetach :)
