### ISSUE TITLE
Chyba exportu příznaku Mimo soutěž do IOF XML 3.0 výsledků

### ISSUE THREAD

**Issue by martinkrivda** [Quick-Event/quickbox#830]
Pokud nastavím závodníkovi příznak Mimo soutěž, v exportu výsledků je závodník označen jako Diskvalifikován, nikoliv Mimo soutěž (což IOF XML 3.0 schéma umožňuje).

Šablona IOF XML 3.0:
`<xsd:enumeration value="NotCompeting">
        <xsd:annotation>
          <xsd:documentation>
            Not competing (i.e. running outside the competition).
          </xsd:documentation>
        </xsd:annotation>
      </xsd:enumeration>`

Testováno ve verzi 2.6.12

### Testovací scénář

1. Přihlásím závodníka s příznakem Mimo soutěž
2. Vyčtu čip závodníkovi s řazením OK
3. Exportuji výsledky Úseky / Etapy -> Exportovat -> Výsledky -> Aktuální etapa -> IOF XML 3.0
4. Závodník má status Disqualified
5. Po úpravě XML v editoru na NotCompeting a následné nahrání do ORIS je OK

**Comment by arnost00** [comment]
Jaka verze QE ?
Zkusebne jsem v QE 2.6.11nastavil MS, vyexportoval vysledky do XML IOF 3.0 a nahral do ORISu
Vysledek je radek :

**Comment by arnost00** [comment]
A dival jsem se ze mezi 2.6.11 a 2.6.12 se v kodu nic co by melo zmenit chovani XML nedelalo.

**Comment by martinkrivda** [comment]
Závod jsem měl vytvořený ve verzi 2.6.9. Tam tento problém je. Pro ověření zda se to nějakým committem nevyřešilo jsem si ho naimportoval závod do 2.6.12. Datově se tam ty flagy nějak pomíchaly. V dialogu byl zaškrtnut jen Mimo soutěž, ale v DB byl i Disqulified. Tak asi vyřešeno. Dík.
