### ISSUE TITLE
Nevalidní XML IOF-XML 3.0 export

### ISSUE THREAD

**Issue by martinkrivda** [Quick-Event/quickbox#831]
Narazil jsem na nevalidní výstupy IOF-XML 3.0 z QE se schématem IOF. ORISu to zřejmě nevadí, ale vadí to ostatním aplikacím, které před zpracováním nahraného souboru XML validují.
Schéma IOF: https://github.com/international-orienteering-federation/datastandard-v3/blob/master/IOF.xsd

- [x] špatná posloupnost elementů v objektu PersonStart v exportu startovní listiny
- [x] špatná posloupnost elementů v objektu Organisation v exportu startovní listiny
- [x]  špatná posloupnost elementů v objektu Organisation v exportu výsledkové listiny

1. špatná posloupnost elementů v objektu PersonStart v exportu startovní listiny
_šablona definuje posloupnost Person, Organisation, Start. QE exportuje posloupnost Person, Start, Organisation_

2. špatné pořadí elementů v objektu Organisation v exportu startovní listiny
_šablona definuje posloupnost Name, ShortName. QE exportuje posloupnost ShortName, Name_ 

3. špatné pořadí elementů v objektu Organisation v exportu výsledkové listiny
_šablona definuje posloupnost Name, ShortName. QE exportuje posloupnost ShortName, Name_

Správně je to takto:
```
<Organisation>
  <Name>OK 99 Hradec Králové</Name>
  <ShortName>PHK</ShortName>
</Organisation>
```

Testováno ve verzi: 2.6.12

### Testovací scénář

1. Vyexportuji výsledkovou listinu do IOF XML (Úseky/Etapy -> Exportovat -> Výsledky -> Aktuální etapa -> IOF XML 3.0)
2. Provedu validaci s šablonou IOF
3. XML je nevalidní -> Element '{http://www.orienteering.org/datastandard/3.0}ShortName': This element is not expected. Expected is one of ( {http://www.orienteering.org/datastandard/3.0}Id, {http://www.orienteering.org/datastandard/3.0}Name )
4. Změním pořadí elementů Name, ShortName
5. XML je validní OK

**Comment by fvacek** [comment]
fixed in 2.6.13

prosim o otestovani

**Comment by martinkrivda** [comment]
Vypadá to dobře, alespoň podle definice IOF. 👌
