### ISSUE TITLE
Import dat z Orisu končí chybou

### ISSUE THREAD

**Issue by lukaskett** [Quick-Event/quickbox#849]
Ahoj,

QE mám připojený k db na [cockroachlabs](https://www.cockroachlabs.com/). Když importuju data z Orisu a vytvářím nový závod tak se mi objevují chyby:

Import závodu id `7371`
![image](https://user-images.githubusercontent.com/29544822/218858708-d0dfc8b4-9a14-4d12-95e1-aacd02920d94.png)

import závodu id `7372` po potvrzení dialogu se závodníky
![image](https://user-images.githubusercontent.com/29544822/218859732-8fe2d12a-fc91-4a59-a0df-29b1d825d8e2.png)

Importovat závod ze souboru jde v pohodě.

**Comment by fvacek** [comment]
a deje se to i s lokalni postgresql?

**Comment by lukaskett** [comment]
Neděje, tam mi to projde ok. Oba importy úspěšně bez chyb.

**Comment by fvacek** [comment]
pak je potreba zjistit, co maji na [cockroachlabs](https://www.cockroachlabs.com/) jinak

**Comment by fvacek** [comment]
to nemam tuseni, teoreticky by to melo byt jedno :(

**Comment by otahirs** [comment]
Jen pro pořádek. QE oficiálně podporuje jen postgresql, cocrouchdb má sice určitou kompatibilitu, ale vytvářet issue, že nefunguje něco co není podporované je trochu z ruky.

**Comment by lukaskett** [comment]
Rozumím a souhlasím. Chtěl jsem se s vámi poradit kde by mohl být problém. Zavírám ať to tady zbytečně neplaší.

**Comment by otahirs** [comment]
FYI: problém vidím v tom, že cocrouchdb nepodporuje `AUTO INCREMENT` https://www.cockroachlabs.com/docs/v22.2/sql-feature-support

**Comment by fvacek** [comment]
no tak to bude tim, protoze QE to vyzaduje, pokud se importuje `qbe`, tak se to naimportuje vcetne `id`

**Comment by lukaskett** [comment]
díky moc za rady
