### ISSUE TITLE
SQLITE - nejaky problem s null hodnotami

### ISSUE THREAD

**Issue by arnost00** [Quick-Event/quickbox#851]
Vypada to ze pri vytvareni noveho zavodu (import z ORISu) se v pripade ze je databaze SQLITE (qbe) spatne ulozi prazdne hodnoty (null).
Ze se vytvori misto hodnoty `null` hodnota `2`.
V PSQL je tam spravne `null`.
Testovano na 2.6.15 a aktualnim dev buildu.

Napr. v tabulce `runs` je to spatne ve vsech sloupeccich co maji mit `null` vcetne startovacich casu.

Setkal se s tim uz nekdo ?

**Comment by arnost00** [comment]
Tak jsem zkusil do SQLITE zalozit prazdny zavod.
A uz pridani nove kategorie u ni do sloupcu misto `null` ulozi `2`

**Comment by arnost00** [comment]
Muze nekdo prosim nezavisle overit zda se mu to deje taky?

**Comment by arnost00** [comment]
U me blbe funguje null u SQLITE i primo v SQL Monitoru napr. pri volani `INSERT INTO`

**Comment by arnost00** [comment]
Zkousel jsem dale, a prijde mi, ze je to problem "az" zobrazeni. Ze kdyz sqlite soubor zobrazim mimo QE tak tam zadne hodnoty `2` nejsou.

**Comment by fvacek** [comment]
podivam se na to

**Comment by fvacek** [comment]
Sorry, doslo k tomu behem uprav kodu pro prechod na Qt6
