### ISSUE TITLE
rozbite connectSlotsByName u LogWidget

### ISSUE THREAD

**Issue by arnost00** [Quick-Event/quickbox#855]
Vypada to ze je rozbite `connectSlotsByName` ktere fungovalo u `LogWidget`
Vypada to ze k rozbiti doslo odstranenim `Q_SLOT` u defininice nekterych member funkci.
A vypada to ze to bylo commitem 00057764bd1928c598622ff413e4e4fcdf4b545d
Bud to chce vratit `Q_SLOT` nebo dokoncit upravu zacatou jeho odstranenim
Testovano na aktualnim dev buildu, Qt5, Windows

**Comment by arnost00** [comment]
Nevim co tim autor toho commitu zamyslel, kdyz odstranil ty `Q_SLOT` tak moc nevim jestli oprava vracenim tech `Q_SLOT` je spravne reseni ?

**Comment by fvacek** [comment]
@arnost00  A udelas z toho PR?

**Comment by arnost00** [comment]
Pridal jsem chybejici 2 connecty. PR #864
