### ISSUE TITLE
Štafety: Název štafety v XML exportu

### ISSUE THREAD

**Issue by lukaskett** [Quick-Event/quickbox#860]
Ahoj,

současný export výsledků štafet do xml dává do názvu štafety (ClassResult/TeamResult/Name) `zkratku klubu + startovní číslo`, např. `DKP 63` v ukázce:
```xml
<ClassResult>
		<Class>
			<Id>168907</Id>
			<Name>D105</Name>
		</Class>
		<TeamResult>
			<Name>DKP 63</Name>
			<Organisation>
				<Name>Oddíl OB Kotlářka</Name>
				<ShortName>DKP</ShortName>
			</Organisation>
			<BibNumber>63</BibNumber>
```

Neměla by se místo startovního čísla, které je o pár tagů dál používat spíš hodnota ze sloupce `Jméno` v záložce `Relays`?
![image](https://user-images.githubusercontent.com/29544822/227000452-4389290e-8f4e-4894-8afe-0ed174a46d3c.png)
Ve výsledcích by pak bylo klasické označení štafet např. `DKP 1`, `DKP 2`, ... Startovní číslo nikoho až tak ve výsledcích nezajímá si myslím.

**Comment by arnost00** [comment]
Něco málo o jménech štafet lze nalézt v #674

**Comment by lukaskett** [comment]
> Něco málo o jménech štafet lze nalézt v https://github.com/Quick-Event/quickbox/issues/674

Celou issue jsem si 2x pročetl a relevantních informací tam moc nebylo. Dle mého jde o chybu, že je startovní číslo popletené s pořadovým číslem v rámci klubu (`KAM 1`, `KAM 2`, `KAM 3`).

Export ze záložky `Štafety->Exportovat->Výsledky` dává totožný výstup jako service `EmmaClient` (což je jediná možnost pravidelného automatického exportu výsledkového xml jestli jsem to dobře pochopil, čekal bych to spíš v `ResultsExporter`, ale tam xml export nefunguje).

**Comment by martinkrivda** [comment]
Souhlasím s Lukášem. Minimálně to není jednotné se startovkami.
Export `Štafety->Exportovat->Startovní listina`
```
<TeamStart>
	<Name>RIC 1</Name>
	<Organisation>
		<Name>OB Říčany</Name>
		<ShortName>RIC</ShortName>
	</Organisation>
	<BibNumber>61</BibNumber>
...
</TeamStart>
```
Export `Štafety->Exportovat->Výsledky`
```
<TeamResult>
	<Name>RIC 61</Name>
	<Organisation>
		<Name>OB Říčany</Name>
		<ShortName>RIC</ShortName>
	</Organisation>
	<BibNumber>61</BibNumber>
...
</TeamResult>
```
a ještě by bylo dobré, aby oba exporty (výsledky i startovky) měly nějaké ID, dle IOF definice, tam může být `EntryId` na **první** pozici v uzlu `TeamStart / TeamResult`, kam by se dle mého mělo plnit ID z tabulky Relays, usnadnilo by to spoustu dalších integrací (teď v exportech žádné ID štafety není)
````
<TeamResult / TeamStart>
        <EntryId>44</EntryId>
	<Name>RIC 1</Name>
	<Organisation>
		<Name>OB Říčany</Name>
		<ShortName>RIC</ShortName>
	</Organisation>
...
</TeamResult / TeamStart>

**Comment by fvacek** [comment]
`ID` mame, muzeme ho tam klidne pridat. Jinak si myslim, ze ve vysledcich by to melo byt stejne jako ve startovce.

**Comment by otahirs** [comment]
@martinkrivda `EntryId` se odkazuje na záznam v [EntryList](https://github.com/international-orienteering-federation/datastandard-v3/blob/24eb108e4c6b5e2904e5f8f0e49142e45e2c5230/IOF.xsd#L161l), což je jiný formát zprávy, ze stejn0 rodiny jako `StartList` nebo `ResultList`
> The id corresponding to this team's entry in an EntryList

pokud potřebuješ ID na integraci, tak můžeš využít u štafet `BibNumber`

**Comment by martinkrivda** [comment]
@otahirs vím, já jsem tu definici četl, ale právě proto, to ID bude vždy stejné ne? EntryList export se stejně pokud vím nikde nepoužívá. BibNumber, tak jak je QE implementované nemusí být unikátní, ID je auto increment. Dokonce mohu založit i štafetu bez čísla. 
Jasně zatím jsem použil BibNumber, ale myslím, že unikátní ID není nic proti ničemu, exporty z ostatních softwarů ho tam také mají.
