### ISSUE TITLE
Štafety: Nefunkční ResultsExporter

### ISSUE THREAD

**Issue by lukaskett** [Quick-Event/quickbox#863]
Export pomocí service `ResultsExporter` do formátu `IOF XML 3.0` generuje soubor `results-csos.txt`, který je obsahově xml (i přes příponu a automatický název), ale neobsahuje všechny data.

**Comment by fvacek** [comment]
Oto, nechces se na to mrknout, pred nedavnem jsi export stafet opravoval.
