### ISSUE TITLE
Wrong content of the <StartName> tag in the XML export of races with more than one start

### ISSUE THREAD

**Issue by zprecek** [Quick-Event/quickbox#876]
When there is more than one start in the race, each of them is identified by different type (S1,S2 etc) in the course description.
However, in the XML 3.0 startlist export the _StartName_ tag contains the "Start1" string even for classes with course that begins on start S2.
Discovered in version 2.6.14 after uploading the exported startlist into ORIS.
According to #253 this should be fixed, but apparently it is not.

**Comment by fvacek** [comment]
fixed in 2.6.18
