### ISSUE TITLE
QE 2.6.14 - odstránkování tisku startovek po kategoriích 

### ISSUE THREAD

**Issue by petrsv** [Quick-Event/quickbox#885]
Ahoj, myslím, že v této verzi chybí možnost nastavení odstránkování tisku startovek po kategoriích (pro vyvěšení na shromaždišti).
Musel jsem řešit tiskem ve starší verzi.

**Comment by paukert** [comment]
Již je opraveno v DEV verzi (https://github.com/Quick-Event/quickbox/issues/879).
