### ISSUE TITLE
Zobrazení času oražení check kontroly před 00

### ISSUE THREAD

**Issue by paukert** [Quick-Event/quickbox#890]
V záložce Úseky / Etapy se čas kontroly nulování čipu zobrazuje jako čas od 00. Aktuální implementace však nedokáže korektně zobrazit časy kontroly čipů, které proběhly před samotným začátkem závodu (týká se to tedy závodníků, kteří mají startovní čas 00 nebo 01). U nich je zobrazen čas o 12 hodin větší. V záložce vyčítání SI čipů se čas zobrazuje ve formátu H:i:s, takže tam se problém nevyskytuje.

**Možná řešení:**
- v záložce Úseky / Etapy zobrazovat čas také ve formátu H:i:s
- vymyslet mechanismus, který by takového případy zobrazoval např. jako -1.32
- nějaký další?

Edit: vypadá to, že špatné zobrazení je již jen následek toho, jak se data uloží do `runs` tabulky. Je otázka, jak dobře to půjde vyřešit i vzhledem k 12 hodinovému stylu ukládání dat na SI čipech.

Soubor (.qbe): [vcp_letohrad_2023_final.zip](https://github.com/Quick-Event/quickbox/files/11299611/vcp_letohrad_2023_final.zip)

![obrazek](https://user-images.githubusercontent.com/15065907/233708701-2eb946b2-45ad-4ccb-a557-40bd4a078bdc.png)

![obrazek](https://user-images.githubusercontent.com/15065907/233708896-73c08b64-4a11-49ca-89cd-667433e145cc.png)

**Comment by fvacek** [comment]
Myslim, ze vzhledem k tomu, ze je ten sloupec hned vedle startovniho casu, ktery je relativni, mel by byt check-time take relativni, tedy `-1.23`

**Comment by fvacek** [comment]
fixed in 2.6.19

**Comment by paukert** [comment]
Provedl jsem základní test a vypadá to dobře, díky :)

![obrazek](https://user-images.githubusercontent.com/15065907/236627277-36d6c093-b5c2-4b5e-8953-11cd4ec80eb4.png)
