### ISSUE TITLE
Pro kategorie s volným startem se vytváří prázdné řádky v nástroji pro losování

### ISSUE THREAD

**Issue by paukert** [Quick-Event/quickbox#891]
Soubor (.qbe): [vcp_letohrad_2023_final.zip](https://github.com/Quick-Event/quickbox/files/11299611/vcp_letohrad_2023_final.zip)

Nejsem si jistý, že to je správný postup, ale v [návodu pro pořádání závodů](https://github.com/Quick-Event/quickbox/wiki/Postup-p%C5%99i-po%C5%99%C3%A1d%C3%A1n%C3%AD-z%C3%A1vod%C5%AF) máme napsáno:

> kategoriím s volným startem (T, P, HDR) nastavit "Interval" na 0 a zaškrtnout "LU" = Losování uzamčeno

To má ale několik důsledků:
1) Při otevření nástroje pro losování se vždy objeví následující hláška:
![obrazek](https://user-images.githubusercontent.com/15065907/233779116-d12eccde-00f7-42ae-ad34-d0a60470664c.png)

2) V nástroji pro losování se pro kategorie s intervalem 0 (ale i s intervalem nastaveným na `null`) vytvoří prázdné řádky:
![obrazek](https://user-images.githubusercontent.com/15065907/233779167-8442ce76-68d7-4849-be0b-f452899f9a6b.png)

    Když následně u některého z prázdných řádků změním čas startu, tak ten se propíše k dané kategorii.
![obrazek](https://user-images.githubusercontent.com/15065907/233779386-4aab31cc-9ba5-41cf-9022-696cc219eb06.png)

    Pro kategorie s intervalem nastaveným na `0` nebo `null` by se IMO v nástroji pro losování neměl vůbec vytvářet řádek, protože to nedává smysl.

**Comment by fvacek** [comment]
Asi je spatne navod, u techto kategorii by se melo jen kliknout na zamecek, aby se vypnula automaticka kontrola kolize startovnich casu

**Comment by paukert** [comment]
Chápu správně, že postup u kategorií s volným startem by měl být tedy následující?
1) uzamknout losování
2) nastavit kategorii interval třeba na 1/2/3 minuty (nezáleží na hodnotě intervalu)
3) v nástroji pro losování kliknout na zámeček, aby se vypnula kontrola kolizí

Při tomto postupu se závodníkům v těchto kategoriích následně nenalosuje žádný čas, při otevírání nástroje pro losování nebude vyskakovat okno s upozorněním a v nástroji pro losování tyto kategorie budou normálně vidět.

**Comment by fvacek** [comment]
> Chápu správně, že postup u kategorií s volným startem by měl být tedy následující?
> 
>     1. uzamknout losování
> 
>     2. nastavit kategorii interval třeba na 1/2/3 minuty (nezáleží na hodnotě intervalu)
> 
>     3. v nástroji pro losování kliknout na zámeček, aby se vypnula kontrola kolizí
> 
> 
> Při tomto postupu se závodníkům v těchto kategoriích následně nenalosuje žádný čas, při otevírání nástroje pro losování nebude vyskakovat okno s upozorněním a v nástroji pro losování tyto kategorie budou normálně vidět.

presne

**Comment by paukert** [comment]
Dobrá, upravím v návodu :)
