### ISSUE TITLE
Postgres driver error in nightly build

### ISSUE THREAD

**Issue by otahirs** [Quick-Event/quickbox#894]
_more info needed_ (reported by Cáš)

**Comment by lukaskett** [comment]
Running version 2.6.18 from [actions](https://github.com/Quick-Event/quickbox/actions/runs/4743815957) pops up error message:
![image](https://user-images.githubusercontent.com/29544822/233864230-2c1246a8-0701-461e-9132-90eada191878.png) 

I am using PostgreSQL version 13. The last working build running on my computer with a working database connection is https://github.com/Quick-Event/quickbox/actions/runs/4714534158.

**Comment by fvacek** [comment]
AppImage 2.6.18 is running Ok on my box.

**Comment by fvacek** [comment]
2.4.7 is reported do be running well on computer where 2.6.18 PSQL error occurs.  I guess that some psql library is missing in the installer or Postgres installed is of some wrong version. In any case we have to find missing dependency of `libpq.dll`

**Comment by arnost00** [comment]
I try switch `libpq.dll` in version 2.6.19 for other (2.6.4 / 2.6.14) and it solve connection problems in 2.6.19
So it is problem with this DLL library.
Inner PQ versions of this libraries are :
- 2.6.19 - PQ 15.1 (15.0.1.23014) size 744kB - doesn't work
- 2.6.14 - PQ 15.1 (15.0.1.22315) size 369kB
- 2.6.4 - PQ 14.2

**Comment by arnost00** [comment]
`libpq.dll` version15.0.1.23014 depends on `libssl-3-x64.dll`

**Comment by fvacek** [comment]
will be fixed in 2.6.19

**Comment by fvacek** [comment]
released
