### ISSUE TITLE
ERR Windows: Modal okna mimo zobrazitelnou plochu

### ISSUE THREAD

**Issue by Nechanicky** [Quick-Event/quickbox#905]
Ahoj, 
zjistil jsem nepříjemné chování ve Windows 10 22H2 v kombinaci NB s FullHD a monitor 5k Ultra HD. 
Pokud připravuješ závod na monitoru s vyšším rozlišením např. 4k a více, a necháš si dialogová okna vložení zákazníka nebo nastavení služby např. OResults mimo nativní rozlišení notebooku a pak jedeš pouze na NB ve FHD, tak se ti dialog zobrazí mimo zobrazitenou plochu. 
Má to tten efekt, že nejsi schopen nic zadat, pouze pomocí ESC jsi chopen okno schodit, aby ses znovu dostal do programu. 
1. Je nějaký způsob jak přes klávesy dostat okno do zobrazitelné plochy? Win+Left nefunguje.
2. Dá se opravit QE tak, aby podle rozlišení připojeného monitoru ignoroval poslední umístění modálního dialogového okna?
Díky 
Pavel

PS. 
Řešením je, že před závodem nesmím zapomenot spustit program pouze na samotném NB a vrátit si tam okna :-)

**Comment by xkenia** [comment]
Tohle uz jsme resili, je k tomu i navod, jak okno dostat zpatky na aktivni plochu, ale nejak to nemuzu najit.

**Comment by paukert** [comment]
Ahoj, při pořádání jsem na to také narazil, u mě bez problému fungovalo tohle řešení: https://github.com/Quick-Event/quickbox/issues/754#issuecomment-1166506151.

Musím ale přiznat, že jsem se nejdříve dost lekt - když jsem chtěl dohlásit závodníka (klikl na tlačítko "+"), tak to vypadalo to, že celý QuickEvent zamrzl a nešel ani vypnout :smile:

**Comment by fvacek** [comment]
should be fixed in `qe3`

**Comment by fvacek** [comment]
Pro QE3 by to uz zlobit nemelo, viz. [69f43aa](https://github.com/Quick-Event/quickbox/commit/69f43aa0accbc46069657c7d7f889044d12437ab), prosim otestovat, nemam ted na cem.

**Comment by fvacek** [comment]
QE2 (master branch) fixed in [5a3b444](https://github.com/Quick-Event/quickbox/commit/5a3b444106f1cac0fb5700c86c04dc0f10d30906)
