### ISSUE TITLE
Kontrola pravidel losování nefunguje po spuštění programu

### ISSUE THREAD

**Issue by OndrejSpanel** [Quick-Event/quickbox#914]
Když QE spustím a přepnu se do Úseky a Etapy a vyberu kategorii, nefunguje zobrazení vakantů ani kontrola pravidel, i když mám řazení podle sloupce Start (na obrázku chybí zelené pruhy vakantů):

![image](https://github.com/Quick-Event/quickbox/assets/6927223/9e90eabc-f2b3-40ce-88c5-6a23273dd3ad)

Aby fugnovat začala, musím třídění podle Start ještě vynutit dvojím kliknutím na sloupec Start:

![image](https://github.com/Quick-Event/quickbox/assets/6927223/ee912f8a-a9ac-4925-8203-5043439cd31a)

Málem jsem se na to nepěkně napálil, spoléhal jsem na kontrolu pravidel, ale přitom neprobíhala, naštěstí jsme to při ruční kontrole startovky chytli.

**Comment by fvacek** [comment]
bohuzel se mi nedari zreprodukovat :(

**Comment by fvacek** [comment]
diky za podrobny navod, ted uz to umim zreprodukovat, tak to i opravim :)

**Comment by fvacek** [comment]
fixed in 2.6.23
