### ISSUE TITLE
XML export závodníků "mimo soutěž"

### ISSUE THREAD

**Issue by pili-BSO** [Quick-Event/quickbox#917]
Zdravím,

o víkendu jsem poprvé použil QE pro pořádání obl.ž. (BSO). A při řešení exportu do ORIS a následně zobrazení postupů v play-map.com jsme s adminem stránek narazili na nesrovnalost, že u závodníků, kteří byli označení v QE "mimo soutěž", tak v XML s výsledky mají status = ????. Zatímco dle informací by měli mít NotCompeting.
A jde o to, že místo toho, aby v ORIS měli uvedený čas a místo pořadí MS, tak jsou disk.
Příklad - závod 7683, H12 Milota Jan - má všechny kontroly, ale je disk, v XML je ten nepatřičný status.
QE jsem použil poslední verzi, tj. 2.6.20, db 1.11.0
qbe i xml file pro případnou analýzu přikládám.
[bso-7683.zip](https://github.com/Quick-Event/quickbox/files/11556238/bso-7683.zip)

Díky!

pili, BSO7801

**Comment by arnost00** [comment]
@pili-BSO Netušíte jak se vám podařilo pro : Frýdlová Michaela a Milota Jan dosáhnout stavu kdy maji jen příznak DISK a MS ?

![2023-05-26 00_25_22-Window](https://github.com/Quick-Event/quickbox/assets/8378685/06c5e2a0-16dc-4397-b544-f38a92a7e44f)
![2023-05-26 00_25_17-Příznaky závodníka](https://github.com/Quick-Event/quickbox/assets/8378685/3fbd53ce-75a0-4fee-abdc-9567efd419e9)

**Comment by arnost00** [comment]
Zatím jsem objevil jednu cestu ... zaškrtnout sloupec DISK ve Vyčítání SI čipů

![2023-05-26 00_32_43-Window](https://github.com/Quick-Event/quickbox/assets/8378685/1c1fa368-d82a-4d48-841d-1eef36dce363)

**Comment by paukert** [comment]
Relates to #691.

**Comment by pili-BSO** [comment]
Díky za odpovědi a tedy jak je napsáno výše, tak způsobené je to tou kombinací MS a DISK. Když jsem se více podíval do výsledků, tak vidím, že u záveodnice Haider, která jako třetí byla MS, tak je příznak správně a i v exportovaném XML má NotCompeting a tím je psrávně označená i v ORISu. Co si ale teď vybavuji, tak tuto závodnici jsem asi označoval MS až po jejím vyčtení, protože jsem na to před tím zapomněl.
Naopak, když jsem u těchto dvou v QE odškrtnul DISK, tak následně v XML již jsou správně. 

Ale k tomu, jak jsem se k tomu dopracoval, tak se přiznám, že si nedokáži vybavit co mohlo nastat. Zapsal jsem je (někdo byl dopředu, někdo na místě), označil MS, odběhli to, vyčetli bez problému (správný čip) a to bylo vše. 

Pro zajímavost jsem se díval i do nedělního našeho závodu 7684 a tam je to obdobný rébus, neboť tentokráte v D12 Frýdlová a Hejnicová jsou OK, ale zase Milota H12 a Haider v TF mají MS + DISK, ale kontroly mají všechny. 

Bohužel nemám již u sebe SIčka, takže nedokážu to nějak otestovat znovu...

**Comment by arnost00** [comment]
Takze to vypada na chybu QE.
Kdyz zavodnikovi dam pred vyctenim stav MS (NC), tak pri vycteni cipu se mu nastavi flag DISK ( je to i videt na radku zavodnika v modulu vycitani. V Useky/Etapy pak je videt ten divny stav `MS, DISK`, viz :
![2023-05-27 22_39_50-Window](https://github.com/Quick-Event/quickbox/assets/8378685/13833882-f72a-4c83-9983-e24945b81f31)

**Comment by arnost00** [comment]
V pripade ze je zavodnik mimo soutěž a ještě MP tak pak to vypada takto (prvni je vycitani, druhe Useky/Etapy:
![2023-05-27 22_44_55-Window](https://github.com/Quick-Event/quickbox/assets/8378685/8a94ea25-3b57-478d-a353-5167f59d386c)
![2023-05-27 22_45_21-Window](https://github.com/Quick-Event/quickbox/assets/8378685/074dc9c6-b42e-4ec8-84a1-24ab26e22061)

**Comment by arnost00** [comment]
cardreaderplugin.cpp, metode ``updateCheckedCardValuesSql`` radek 367 :
```c++
	bool should_be_disq = false;
	{
		q.execThrow("SELECT * FROM runs WHERE id=" + QString::number(run_id));
		if(q.next()) {
			if(q.value("disqualifiedByOrganizer").toBool()) should_be_disq = true;
			if(q.value("notCompeting").toBool()) should_be_disq = true;
			if(q.value("notStart").toBool()) should_be_disq = true;
			if(q.value("notFinish").toBool()) should_be_disq = true;
		}
	}
```

a o kousek dal :
```c++
 	q.bindValue(QStringLiteral(":disqualified"), should_be_disq || !checked_card.isOk());
```

Asi by se pro ``notCompeting`` nemelo nastavovat ``should_be_disq``

Co si o tom myslite ?

**Comment by paukert** [comment]
Mně to dává smysl, příznak `notCompeting` by měl stačit sám o sobě.

Koukal jsem to různých reportů a za sebe bych doplnil status `notCompeting` i do `libquickevent/libquickeventcore/js/ogtime.js:62`, aby ve výsledcích byl u závodníka nějaký příznak viz screen níže. Zároveň by bylo dobré v `ogtime.js` ve funkcích `ogTimeToString` a `detailRunStatusToString` upravit prioritu příznaků dle změn v https://github.com/Quick-Event/quickbox/pull/919.

![image](https://github.com/Quick-Event/quickbox/assets/15065907/10c6a73c-7fed-415a-a058-14aa00c6e9ec)

**Comment by arnost00** [comment]
>Koukal jsem do různých reportů a za sebe bych doplnil status notCompeting i do libquickevent/libquickeventcore/js/ogtime.js:62, aby ve výsledcích byl u závodníka nějaký příznak viz screen níže.

Jasne, souhlas, doplnim.

> Zároveň by bylo dobré v ogtime.js ve funkcích ogTimeToString a detailRunStatusToString upravit prioritu příznaků dle změn v https://github.com/Quick-Event/quickbox/pull/919.

Funkce ``ogTimeToString`` neni potreba upravovat, ``time_ms`` muze nabyt jen jedne hodnoty.
Funkci ``detailRunStatusToString`` upravim.
