### ISSUE TITLE
Qt6 build CI

### ISSUE THREAD

**Issue by fvacek** [Quick-Event/quickbox#922]

**Comment by arnost00** [comment]
I tried the Qt6 build.
I have a problem compiling QE with Qt6 under Windows. I had to make a few changes and still don't have it buildable. I'm a little surprised that it went on Actions.
I'm using Qt6.5.1, MinGW 11.2.0 64b, branch `qt6`, commit 7b8652d
I tried both QMake and CMake
Code changes I've made so far: [qt6.patch](https://github.com/Quick-Event/quickbox/files/11654845/qt6.patch)

**Comment by fvacek** [comment]
* qt6 cannot be built with qmake anymore
* make sure that you have switched to branch `qt6`, it seems to me (according to patch), that you are porting master to Qt6 :)

**Comment by arnost00** [comment]
FYI - Branch `qt6`, commit 1ad5b3c, CMake, Qt6.5.1, MinGW 11.2.0 64b, Windows debug build - Done.

**Comment by fvacek** [comment]
zkusel jsem ve wine, ze soucasny qt6 build z actions jde spustit, sqlite funguje, reporty jeste ne, v instalatoru chybi QML pluginy, windeployqt je nanejde, ale `cmake . --install` by je mel nahrat do spravneho adresare, jeste se na to podivam.

![image](https://github.com/Quick-Event/quickbox/assets/4949019/a90f8e74-b285-4cec-9b4c-d0be9b05998f)

**Comment by fvacek** [comment]
tak reporty uz chodi, zda se, ze se s Qt6 sam vyresil i problem s SSL, jeste nejde vytvorit DB a tim padem i import, ale asi uz vim, cim to je.

**Comment by fvacek** [comment]
DB jiz lze vytvorit tez, takze ted vlastne nevim o nicem, co v Qt6 nefunguje.

**Comment by arnost00** [comment]
> [37decb3](https://github.com/Quick-Event/quickbox/commit/37decb300870f725f70f08de5ebba76eaee158fc) DB jiz lze vytvorit tez, takze ted vlastne nevim o nicem, co v Qt6 nefunguje.

Zkusis H.S.H. Vysočina Cup uz udelat na teto branchi ?

**Comment by fvacek** [comment]
jj, pocitam s tim, jestli pujde vsechno hladce, zmergeoval bych qt6 a master

**Comment by fvacek** [comment]
pokracoval bych v #929
