### ISSUE TITLE
Switch to Qt6 and QE 3.0

### ISSUE THREAD

**Issue by fvacek** [Quick-Event/quickbox#929]
Functionality still missing or not tested
* [x] linux appimage 
* [x] windows installer
* [x] sqltool cannot be launched
* [x] libpsql.dll in windows installer
* [x] #932 
* [x] #933 
* [x] #934 
* [x] #935
* [x] #936

testing 1

* [ ] #938
* [x] #940
* [x] #939
* [x] #941 
* [x] #942 
* [x] #944
* [x] #945
* [x] #946
* [x] #947

**Comment by fvacek** [comment]
@paukert @Nechanicky @otahirs @arnost00 @xkenia if you will find some other issues with qt6 version, please let me know. I plan to switch to qt6 after H.S.H. in other case.

**Comment by arnost00** [comment]
I tried qt6, build debug on Windows and when running from the IDE it can't find the qml report files when I try to print preview.

**Comment by arnost00** [comment]
> did you call `cmake --install .` ?

No. I was only debuging in QtCreator. With CMake is necessary run install before debuging ?

**Comment by fvacek** [comment]
Yes, cmake copies all report files to correct directories. If you need to run QE directly from QTC, then bin/reports must be symlinked or copied from installation.

**Comment by arnost00** [comment]
Commit 146dfd5dbd09cba67dd1aa84cba3954ed706ce41
Fix of icons failed.
![Window_2023-07-18_12-47-43](https://github.com/Quick-Event/quickbox/assets/8378685/a7b0dc1f-87f9-4bb9-800a-01895397971b)

**Comment by arnost00** [comment]
> Yes, cmake copies all report files to correct directories. If you need to run QE directly from QTC, then bin/reports must be symlinked or copied from installation.

I'm a little surprised that qmake didn't need to do that. And that it is now less user-friendly :disappointed:

**Comment by fvacek** [comment]
> > Yes, cmake copies all report files to correct directories. If you need to run QE directly from QTC, then bin/reports must be symlinked or copied from installation.
> 
> I'm a little surprised that qmake didn't need to do that. And that it is now less user-friendly disappointed

`qmake` didn't neet to do that, because it almost was not able to do it. This is area, where `cmake` is much more powerful than `qmake`. We had so big troubles to do it with `qmake`, that decision was to move reports to resources. But now with `cmake`, we can easily solve all the installation problems. Look at `QT6` CI, how things got simpler.

**Comment by fvacek** [comment]
@otahirs @paukert @arnost00 @xkenia 

I'm ready to rename `qt6` branch to `master`, QE develpment will continue in Qt6 only.

QE 2.x development can continue in branch `QE2`, but only if somebody enrolls himself to be a  maintainer. 

Since I have to force push to move `master` branch `qe6`, I like to let you know about this violent action.

I'm waiting for your objections until Saturday.

Fanda

**Comment by arnost00** [comment]
Are all updates from the `master` branch merged into the `qt6` branch?

I think we will stay in `QE2` until the end of [WC](https://eventor.orienteering.org/Events/Show/7247), [WMOC ](https://eventor.orienteering.org/Events/Show/7476)and [WMTBOC](https://eventor.orienteering.org/Events/Show/6872). 
We are still fixing the QE version for these 3 races (PR #928)
After that we can move to `qt6`.

**Comment by fvacek** [comment]
No, they are not. This is why I've asked you to rebase your patches to qt6, although I understand that big competition is not good playground for qe3 testing.

QE3 diverged, so changes to QE2 must be cherry picked and ported and tested again. This is not convinient, but we cannot wait with switch to qt6 forewer.

**Comment by arnost00** [comment]
I understand. I'll see what's missing in `qt6` from my old patches and try to fix it.
PR #928 - I will try to prepare it as a patch for `qt6` too

**Comment by fvacek** [comment]
Qt6 is not only change in QE3, cmake build system comes also with QT6. CMAKE is much better than qmake, but it brings many incompatibilities in QML plugins build.

What has changes in qt6 build:
1. `cmake --install .` must be called after build to have runable QE instance with all QML plugins and report files installed at correct places. Assume that QE is installed to `/home/joe/qe3`
2. If developer do not want to call install after each build, then 3 symlinks must be created in directory `<build-dir>/quickevent/app/quickevent` where `cmake --build .` creates QE executable. 
   1. `<build-dir>/quickevent/app/quickevent/qml` ->` /home/joe/qe3/bin/qml`
   2. `<build-dir>/quickevent/app/quickevent/reports` ->` /home/joe/qe3/bin/reports`
   3. `<build-dir>/quickevent/app/quickevent/translations` ->` /home/joe/qe3/bin/translations`

**Comment by fvacek** [comment]
No objections?

**Comment by paukert** [comment]
I was quite busy for the last few weeks and I did not test QT6 version yet.

It would be nice if all fixed bugs and new features from QE 2.x were also fixed and added to QE 3.x as was already mentioned above.

During next week I would be able to test main QE features in Windows build as well as in AppImage build (I suppose that Linux build was probably already tested quite well by fvacek at HSH).

**Comment by arnost00** [comment]
So, the last merge from `master` to `qt6` is e7e2bd31f533026cf822d6d26e10495b5a422428 from 8 May.
This PR are missing in `qt6` branch are : #850, #915, #919, #920, #923, #926, #937, 
Commits : 2874dc1e03d21e5c5b5d720bb6c2b18449300eb4, 2dc2802406ccf4e1ec1297c8915e49812763ac15, (6x Update Readme.md), 81647145c4903a6dc764b3899c6b28d051234965, ace1b335bf814b6d719b3edae5f3048df1649eb8, 60aac7e8301093b24224b377eaff9e848da379ad

That's not a little work

**Comment by arnost00** [comment]
To me, it still looks like the `qt6` branch is in the development phase. Even @fvacek doesn't have all his commits from `master` there. And 7 merged PR from other developers is missing.

**Comment by fvacek** [comment]
> To me, it still looks like the `qt6` branch is in the development phase. Even @fvacek doesn't have all his commits from `master` there. And 7 merged PR from other developers are missing.
> 

That's OK, master is obviously development branch. https://github.com/Quick-Event/quickbox/pull/850, https://github.com/Quick-Event/quickbox/pull/915, https://github.com/Quick-Event/quickbox/pull/919, https://github.com/Quick-Event/quickbox/pull/920, https://github.com/Quick-Event/quickbox/pull/923, https://github.com/Quick-Event/quickbox/pull/926, https://github.com/Quick-Event/quickbox/pull/937 should be cherry-picked from `qe2`. I hope, that it will not be big problem regarding porting to Qt6, rather testing.

> I tried merging `origin\master` into `origin\qt6` - and it looks buildable (only append missing files to cmakelist).
That is not good way IMO, branches diverged too much because of build system change. I think, that cherry-picking issues commits will be faster and less painful.

**Comment by fvacek** [comment]
I tried to cherry-pick PR #850 without any problems in 5 minutes with originals commits. https://github.com/Quick-Event/quickbox/commits/qe3

**Comment by fvacek** [comment]
* [ ] https://github.com/Quick-Event/quickbox/pull/850, 
* [ ] https://github.com/Quick-Event/quickbox/pull/915, 
* [ ] https://github.com/Quick-Event/quickbox/pull/919, 
* [ ] https://github.com/Quick-Event/quickbox/pull/920, 
* [ ] https://github.com/Quick-Event/quickbox/pull/923, 
* [ ] https://github.com/Quick-Event/quickbox/pull/926, 
* [ ] https://github.com/Quick-Event/quickbox/pull/937

**Comment by paukert** [comment]
- I found few bugs in today's quick testing, [qbe file](https://github.com/Quick-Event/quickbox/files/12330476/vcp_letohrad_2023_final_2.zip)
- during app startup (Windows and AppImage), following errors are printed to the console
    ```
    PS C:\QuickEvent> .\quickevent.exe
    2023-08-13T18:37:58[main.cpp:66]|I| ========================================================
    2023-08-13T18:37:58[main.cpp:67]|I| 2023-08-13T20:37:58 starting quickevent ver: 3.0.4
    2023-08-13T18:37:58[main.cpp:68]|I| Log tresholds:
    qt.core.qobject.connect: QObject::connect(QObject, Unknown): invalid nullptr parameter
    qt.network.ssl: No functional TLS backend was found
    2023-08-13T18:37:58[main.cpp:69]|I| Open SSL:
    2023-08-13T18:37:58[main.cpp:70]|I| ========================================================
    2023-08-13T18:37:58[siid.cpp:14]|I| registerQVariantFunctions
    ```
- printing results (Current stage, Current stage for speaker, After n stages) is not working, only one empty page is in preview; After n stages for speaker is probably stuck in some loop — it was generating hundrets of pages
    - first problem is probably in report options — if the filter for categories is filled, the results are printed correctly
    ![obrazek](https://github.com/Quick-Event/quickbox/assets/15065907/126127c0-f18d-44e1-bacd-28154c517cfc)
    ![obrazek](https://github.com/Quick-Event/quickbox/assets/15065907/8a31ca83-566c-402b-a62d-af1feae7950a)
- translations does not work in AppImage:
    ```
    2023-08-12T22:23:52[main.cpp:114]|I| Loading translations for: cs_CZ
    2023-08-12T22:23:52[main.cpp:129]|I| Installing translator file: libqfcore  ...  ERROR
    2023-08-12T22:23:52[main.cpp:129]|I| Installing translator file: libqfqmlwidgets  ...  ERROR
    2023-08-12T22:23:52[main.cpp:129]|I| Installing translator file: libquickeventcore  ...  ERROR
    2023-08-12T22:23:52[main.cpp:129]|I| Installing translator file: libquickeventgui  ...  ERROR
    2023-08-12T22:23:52[main.cpp:129]|I| Installing translator file: libsiut  ...  ERROR
    2023-08-12T22:23:52[main.cpp:129]|I| Installing translator file: quickevent  ...  ERROR
    2023-08-12T22:23:52[main.cpp:139]|I| Installing translator file: qt ...  ERROR
    ```
- I was not able to select custom folder for report files in AppImage (folder is selected but the button for copying reports to the selected folder is missing)
    ![obrazek](https://github.com/Quick-Event/quickbox/assets/15065907/b63994c8-5dc8-4156-8754-d30361a2c8f1)
    ![obrazek](https://github.com/Quick-Event/quickbox/assets/15065907/c339050c-76d9-4b64-ae5c-7bfc8adf4e1e)
- suggestion: change GitHub runner for creating AppImage from `ubuntu-22.04` to `ubuntu-20.04` so the AppImage is also compatible with "older" distributions e.g. Ubuntu 20.04

**Comment by fvacek** [comment]
> suggestion: change GitHub runner for creating AppImage from ubuntu-22.04 to ubuntu-20.04 so the AppImage is also compatible with "older" distributions e.g. Ubuntu 20.04

Thanks for testing. If we switch to older Ubuntu, then users of old distributions will be happy, but what about users of recent distros?

**Comment by fvacek** [comment]
* [ ] #938

**Comment by arnost00** [comment]
Does anyone know why build in Actions for Windows does not work? It works for me locally, but I have no idea what's wrong yet.
Or at least a link to a functional build & install for Windows. I need to find out what is in it, because I still can't start printing locally (cannot load QML reports).

**Comment by fvacek** [comment]
```
Error 5 while parsing D:/a/quickbox/quickbox/build/libqf/plugins/qf/core/meta_types/qt6qfcoreplugin_release_metatypes.json: illegal value
```
This is not very descriptive bug report. I've found something here https://bugreports.qt.io/browse/QTBUG-95204, but all the bugs of this kind seems to be resolved in 6.6.2 :(

**Comment by arnost00** [comment]
libqf\CMakeLists.txt uses key QF_BUILD_QML_PLUGINS to switch plugins On
This value is not defined.

**Comment by fvacek** [comment]
running actions build in wine gives me this error:
```
Unhandled exception: page fault on write access to 0x00007fff00000008 in 64-bit code (0x006ffffc58f00e).
Register dump:
 rip:00006ffffc58f00e rsp:00007ffffe2ff5c0 rbp:00007ff94a16b4b8 eflags:00010202 (  R- --  I   - - - )
 rax:00007ff94a16b578 rbx:00007ffffe2ff620 rcx:00006ffffc5db960 rdx:00006ffffc5db960
 rsi:00007fff00000008 rdi:00006ffffc6610f0  r8:00007ff94a16b4f8  r9:00007ff94a43c1d0 r10:0000000000000030
 r11:0000000000000000 r12:00007ff94a16b3e0 r13:00006ffffc629770 r14:00006ffff71dbe20 r15:00006ffffc635bb0
Stack dump:
0x007ffffe2ff5c0:  00007fffff1e9e90 00007ffffe2ff648
0x007ffffe2ff5d0:  00007ff94a16b390 00007ff94a16b4a8
0x007ffffe2ff5e0:  00007ffffe2ff620 00007ff94a16b4a8
0x007ffffe2ff5f0:  00007ffffe2ff620 00006ffffc5b037a
0x007ffffe2ff600:  00007ff94a436b00 00007ff94a16b588
0x007ffffe2ff610:  00007ffffe2ff8d0 00007ffffe2ff6f0
0x007ffffe2ff620:  00006ffffc5db960 fec823fe7716d55e
0x007ffffe2ff630:  00007ff94a16b4a8 0000000000000000
0x007ffffe2ff640:  00007ffffe2ff6f0 00006ffffc5b1d01
0x007ffffe2ff650:  0000000000000079 0000000000000000
0x007ffffe2ff660:  0000000140002260 00007ff94a16b390
0x007ffffe2ff670:  00007ffffe2ff8d0 00007ff94a16b390
Backtrace:
=>0 0x006ffffc58f00e in libstdc++-6 (+0xff00e) (0x007ff94a16b4b8)
  1 0x006ffffc5b037a in libstdc++-6 (+0x12037a) (0x007ff94a16b4b8)
  2 0x006ffffc5b1d01 in libstdc++-6 (+0x121d01) (0x007ff94a16b4b8)
  3 0x000001400538c9 in quickevent (+0x538c9) (0x007ff94a16b4b8)
  4 0x0000014001f62f in quickevent (+0x1f62f) (0x007ff94a2f74c0)
  5 0x006ffffa7c57b1 in qt6core (+0x3657b1) (0x007ff94a3094e0)
  6 0x00000140251181 in quickevent (+0x251181) (0x007fffff14c800)
  7 0x0000014024f775 in quickevent (+0x24f775) (0x007fffff14c800)
  8 0x00000140257852 in quickevent (+0x257852) (0x006fffffa904f4)
  9 0x000001400012ef in quickevent (+0x12ef) (0x007ffffe456430)
  10 0x000001400013e6 in quickevent (+0x13e6) (0000000000000000)
  11 0x006fffffaa8ce9 BaseThreadInitThunk+0x9(unknown=<internal error>, entry=<internal error>, arg=<internal error>) [/build/wine/src/wine-64-build/../wine/dlls/kernel32/thread.c:61] in kernel32 (0000000000000000)
  12 0x006fffffca55af in ntdll (+0x555af) (0000000000000000)
0x006ffffc58f00e libstdc++-6+0xff00e: lock subl $0x01, (%rsi)
Modules:
Module  Address                                 Debug info      Name (151 modules)
PE-Wine         77710000-        77c84000       Deferred        opengl32
PE             140000000-       140386000       Dwarf-5         quickevent
PE-Wine     6ffff5890000-    6ffff58a8000       Deferred        msimg32
PE          6ffff58c0000-    6ffff58da000       Deferred        qsvgicon
PE          6ffff58f0000-    6ffff5903000       Deferred        qsvg
PE          6ffff5920000-    6ffff59ad000       Deferred        qjpeg
PE          6ffff59c0000-    6ffff59d5000       Deferred        qico
PE          6ffff59f0000-    6ffff5a20000       Deferred        qwindowsvistastyle
PE-Wine     6ffff5a30000-    6ffff5a62000       Deferred        wtsapi32
PE-Wine     6ffff5a80000-    6ffff5c16000       Deferred        d3d9
PE          6ffff5c30000-    6ffff5d36000       Deferred        qwindows
PE-Wine     6ffff5d50000-    6ffff5d9e000       Deferred        msv1_0
PE-Wine     6ffff5db0000-    6ffff5de2000       Deferred        kerberos
PE          6ffff5e00000-    6ffff5e25000       Deferred        qt6serialport
PE          6ffff5e40000-    6ffff5e83000       Deferred        libsiut
PE          6ffff5ea0000-    6ffff5f77000       Deferred        qt6multimedia
PE          6ffff5f90000-    6ffff6060000       Deferred        libquickeventgui
PE          6ffff6070000-    6ffff60c3000       Deferred        libquickeventcore
PE          6ffff60e0000-    6ffff6141000       Deferred        qt6svg
PE-Wine     6ffff6160000-    6ffff6185000       Deferred        dwmapi
PE          6ffff61a0000-    6ffff67fa000       Deferred        qt6widgets
PE-Wine     6ffff6810000-    6ffff6842000       Deferred        compstui
PE-Wine     6ffff6860000-    6ffff6927000       Deferred        winspool
PE-Wine     6ffff6940000-    6ffff6e9e000       Deferred        comctl32
PE-Wine     6ffff6eb0000-    6ffff7101000       Deferred        comdlg32
PE          6ffff7120000-    6ffff7188000       Deferred        qt6printsupport
PE          6ffff71a0000-    6ffff733b000       Deferred        libqfqmlwidgets
PE          6ffff7350000-    6ffff737d000       Deferred        qt6xml
PE          6ffff7390000-    6ffff73e4000       Deferred        qt6sql
PE          6ffff7400000-    6ffff792d000       Deferred        qt6qml
PE-Wine     6ffff7940000-    6ffff7a79000       Deferred        winhttp
PE-Wine     6ffff7a90000-    6ffff7b45000       Deferred        secur32
PE          6ffff7b60000-    6ffff7cf8000       Deferred        qt6network
PE-Wine     6ffff7d10000-    6ffff8030000       Deferred        dwrite
PE-Wine     6ffff8040000-    6ffff95e5000       Deferred        wined3d
PE-Wine     6ffff9600000-    6ffff9745000       Deferred        dxgi
PE-Wine     6ffff9760000-    6ffff9a4a000       Deferred        d3d11
PE          6ffff9a60000-    6ffffa44a000       Deferred        qt6gui
PE          6ffffa460000-    6ffffaad2000       Export          qt6core
PE-Wine     6ffffb060000-    6ffffb084000       Deferred        nsi
PE-Wine     6ffffb0a0000-    6ffffb0ed000       Deferred        dnsapi
PE-Wine     6ffffb100000-    6ffffb18e000       Deferred        iphlpapi
PE-Wine     6ffffb250000-    6ffffb2a8000       Deferred        winex11
PE-Wine     6ffffb2c0000-    6ffffb389000       Deferred        uxtheme
PE-Wine     6ffffb3a0000-    6ffffb41e000       Deferred        imm32
PE-Wine     6ffffb750000-    6ffffb77e000       Deferred        userenv
PE-Wine     6ffffb790000-    6ffffb964000       Deferred        setupapi
PE          6ffffb980000-    6ffffb996000       Deferred        qgif
PE-Wine     6ffffb9b0000-    6ffffb9f9000       Deferred        jsproxy
PE-Wine     6ffffba10000-    6ffffbee3000       Deferred        oleaut32
PE-Wine     6ffffbf00000-    6ffffbf5f000       Deferred        d3d12
PE-Wine     6ffffbf70000-    6ffffbfeb000       Deferred        msacm32
PE-Wine     6ffffc000000-    6ffffc1b5000       Deferred        winmm
PE-Wine     6ffffc1d0000-    6ffffc1f0000       Deferred        version
PE-Wine     6ffffc200000-    6ffffc2a6000       Deferred        netapi32
PE-Wine     6ffffc2c0000-    6ffffc326000       Deferred        mpr
PE-Wine     6ffffc340000-    6ffffc35d000       Deferred        authz
PE          6ffffc370000-    6ffffc47e000       Deferred        libqfcore
PE          6ffffc490000-    6ffffc6d2000       COFF            libstdc++-6
PE          6ffffc6f0000-    6ffffc706000       Deferred        libwinpthread-1
PE          6ffffc720000-    6ffffc744000       Deferred        libgcc_s_seh-1
PE          6ffffc760000-    6ffffc77a000       Deferred        libnecrolog
PE-Wine     6ffffc790000-    6ffffc7e2000       Deferred        shcore
PE-Wine     6ffffc800000-    6ffffc915000       Deferred        shlwapi
PE-Wine     6ffffc930000-    6ffffd6ad000       Deferred        shell32
PE-Wine     6ffffd6c0000-    6ffffd70c000       Deferred        coml2
PE-Wine     6ffffd720000-    6ffffd9a8000       Deferred        rpcrt4
PE-Wine     6ffffd9c0000-    6ffffd9fe000       Deferred        win32u
PE-Wine     6ffffda10000-    6ffffdfea000       Deferred        user32
PE-Wine     6ffffe000000-    6ffffe2ca000       Deferred        gdi32
PE-Wine     6ffffe2e0000-    6ffffe477000       Deferred        combase
PE-Wine     6ffffe490000-    6ffffea0d000       Deferred        ole32
PE-Wine     6ffffea20000-    6ffffeacd000       Deferred        ws2_32
PE-Wine     6ffffeae0000-    6ffffeecf000       Deferred        ucrtbase
PE-Wine     6ffffeee0000-    6ffffef9e000       Deferred        sechost
PE-Wine     6ffffefb0000-    6fffff301000       Deferred        msvcrt
PE-Wine     6fffff320000-    6fffff44b000       Deferred        advapi32
PE-Wine     6fffff460000-    6fffffa6b000       Deferred        kernelbase
PE-Wine     6fffffa80000-    6fffffc37000       Dwarf-4-5       kernel32
PE-Wine     6fffffc50000-    6ffffffef000       Dwarf-4-5       ntdll
ELF         7ff94a85e000-    7ff94a884000       Deferred        libgpg-error.so.0
ELF         7ff94a884000-    7ff94a8a9000       Deferred        libgcc_s.so.1
ELF         7ff94a8a9000-    7ff94a8ce000       Deferred        liblz4.so.1
ELF         7ff94a8ce000-    7ff94aa17000       Deferred        libgcrypt.so.20
ELF         7ff94aa17000-    7ff94aa23000       Deferred        libcap.so.2
ELF         7ff94aa23000-    7ff94ab17000       Deferred        libsystemd.so.0
ELF         7ff94ab17000-    7ff94ab68000       Deferred        libdbus-1.so.3
ELF         7ff94ab68000-    7ff94ab7b000       Deferred        libavahi-client.so.3
ELF         7ff94ab7b000-    7ff94ab8a000       Deferred        libavahi-common.so.3
ELF         7ff94ab8a000-    7ff94ac28000       Deferred        libcups.so.2
ELF         7ff94ac28000-    7ff94ac7c000       Deferred        libgssapi_krb5.so.2
ELF         7ff94ac7c000-    7ff94acaa000       Deferred        libk5crypto.so.3
ELF         7ff94acaa000-    7ff94ad82000       Deferred        libkrb5.so.3
ELF         7ff94adb7000-    7ff94adc2000       Deferred        libffi.so.8
ELF         7ff94adc2000-    7ff94ae68000       Deferred        libgmp.so.10
ELF         7ff94ae68000-    7ff94aeb1000       Deferred        libhogweed.so.6
ELF         7ff94aeb1000-    7ff94af09000       Deferred        libnettle.so.8
ELF         7ff94af09000-    7ff94af20000       Deferred        libtasn1.so.6
ELF         7ff94af20000-    7ff94b0da000       Deferred        libunistring.so.5
ELF         7ff94b0da000-    7ff94b0fc000       Deferred        libidn2.so.0
ELF         7ff94b0fc000-    7ff94b1cf000       Deferred        libzstd.so.1
ELF         7ff94b1cf000-    7ff94b281000       Deferred        libbrotlienc.so.1
ELF         7ff94b281000-    7ff94b417000       Deferred        libp11-kit.so.0
ELF         7ff94b417000-    7ff94b61b000       Deferred        libgnutls.so.30
ELF         7ff94b621000-    7ff94b627000       Deferred        winspool.so
ELF         7ff94b627000-    7ff94b62c000       Deferred        msv1_0.so
ELF         7ff94b62c000-    7ff94b633000       Deferred        libkeyutils.so.1
ELF         7ff94b633000-    7ff94b641000       Deferred        libkrb5support.so.0
ELF         7ff94b641000-    7ff94b647000       Deferred        libcom_err.so.2
ELF         7ff94b647000-    7ff94b650000       Deferred        kerberos.so
ELF         7ff94b672000-    7ff94b7b5000       Deferred        libx11.so.6
ELF         7ff94b7b5000-    7ff94b834000       Deferred        winex11.so
ELF         7ff94b931000-    7ff94b939000       Deferred        libxfixes.so.3
ELF         7ff94b939000-    7ff94b945000       Deferred        libxcursor.so.1
ELF         7ff94b945000-    7ff94b959000       Deferred        libxi.so.6
ELF         7ff94b959000-    7ff94ba39000       Deferred        opengl32.so
ELF         7ff94bb24000-    7ff94bb31000       Deferred        libxrandr.so.2
ELF         7ff94bb31000-    7ff94bb3e000       Deferred        libxrender.so.1
ELF         7ff94bb3e000-    7ff94bb69000       Deferred        libxcb.so.1
ELF         7ff94bb6a000-    7ff94bb74000       Deferred        secur32.so
ELF         7ff94bb74000-    7ff94bb7a000       Deferred        dwrite.so
ELF         7ff94bb9e000-    7ff94bbaf000       Deferred        libresolv.so.2
ELF         7ff94bbb0000-    7ff94bbb5000       Deferred        libxcomposite.so.1
ELF         7ff94bbb5000-    7ff94bbbc000       Deferred        libxxf86vm.so.1
ELF         7ff94bbbc000-    7ff94bbc1000       Deferred        libxinerama.so.1
ELF         7ff94bbc1000-    7ff94bbc9000       Deferred        libxdmcp.so.6
ELF         7ff94bbc9000-    7ff94bbde000       Deferred        libxext.so.6
ELF         7ff94bbde000-    7ff94bbe4000       Deferred        netapi32.so
ELF         7ff94bbf3000-    7ff94bbf8000       Deferred        libxau.so.6
ELF         7ff94bbf8000-    7ff94bbfe000       Deferred        ws2_32.so
ELF         7ff94bbfe000-    7ff94bc03000       Deferred        dnsapi.so
ELF         7ff94bc1a000-    7ff94bc43000       Deferred        libexpat.so.1
ELF         7ff94bc43000-    7ff94bc93000       Deferred        libfontconfig.so.1
ELF         7ff94bc93000-    7ff94bd2e000       Deferred        libpcre2-8.so.0
ELF         7ff94bd2e000-    7ff94bd51000       Deferred        libbrotlicommon.so.1
ELF         7ff94bd51000-    7ff94bd74000       Deferred        libgraphite2.so.3
ELF         7ff94bd74000-    7ff94bec0000       Deferred        libglib-2.0.so.0
ELF         7ff94bec0000-    7ff94becf000       Deferred        libbrotlidec.so.1
ELF         7ff94becf000-    7ff94bfdd000       Deferred        libharfbuzz.so.0
ELF         7ff94bfdd000-    7ff94c017000       Deferred        libpng16.so.16
ELF         7ff94c017000-    7ff94c02a000       Deferred        libbz2.so.1.0
ELF         7ff94c02a000-    7ff94c044000       Deferred        libz.so.1
ELF         7ff94c044000-    7ff94c112000       Deferred        libfreetype.so.6
ELF         7ff94c112000-    7ff94c200000       Deferred        libm.so.6
ELF         7ff94c200000-    7ff94c38d000       Deferred        win32u.so
ELF         7ff94ccf1000-    7ff94cd24000       Deferred        liblzma.so.5
ELF         7ff94cd24000-    7ff94cd3e000       Deferred        libunwind.so.8
ELF         7ff94cd3e000-    7ff94cdf6000       Export          ntdll.so
ELF         7ff94cdf9000-    7ff94cfdf000       Deferred        libc.so.6
ELF         7ff94d016000-    7ff94d04d000       Deferred        ld-linux-x86-64.so.2
ELF         7ff94d04d000-    7ff94d052000       Deferred        <wine-loader>
Threads:
process  tid      prio    name (all IDs are in hex)
00000038 services.exe
	0000003c    0     
	00000040    0     wine_rpcrt4_server
	0000004c    0     wine_rpcrt4_io
	00000070    0     wine_rpcrt4_io
	0000009c    0     wine_rpcrt4_io
	000000ac    0     wine_rpcrt4_io
	000000c4    0     wine_rpcrt4_io
	000000dc    0     
	000000f0    0     wine_rpcrt4_io
00000044 winedevice.exe
	00000048    0     
	00000054    0     
	00000058    0     wine_sechost_service
	0000005c    0     
	00000060    0     
	00000064    0     
	000000d4    0     
	000000d8    0     
00000068 winedevice.exe
	0000006c    0     
	00000074    0     
	00000078    0     wine_sechost_service
	0000007c    0     
	00000080    0     
	00000084    0     
	00000088    0     
	00000094    0     
	000000a0    0     
0000008c explorer.exe
	00000090    0     
	000000d0    0     
	000000e0    0     wine_rpcrt4_server
000000a4 plugplay.exe
	000000a8    0     
	000000b0    0     
	000000b4    0     wine_sechost_service
	000000b8    0     wine_rpcrt4_server
000000bc svchost.exe
	000000c0    0     
	000000c8    0     
	000000cc    0     wine_sechost_service
000000e8 rpcss.exe
	000000ec    0     
	000000f8    0     
	000000fc    0     wine_sechost_service
	00000100    0     wine_rpcrt4_server
	00000104    0     wine_rpcrt4_server
	00000108    0     wine_rpcrt4_io
00000148 (D) C:\QuickEvent\quickevent.exe
	0000014c    0 <== 
	00000150   15     
	00000164    0     
0000015c conhost.exe
	00000160    0     
System information:
    Wine build: wine-9.3
    Platform: x86_64 (guest: i386)
    Version: Windows 10
    Host system: Linux
    Host version: 5.15.154-1-MANJARO
```

**Comment by arnost00** [comment]
> > libqf\CMakeLists.txt uses key QF_BUILD_QML_PLUGINS to switch plugins On This value is not defined.
> > It is only defined in `.github\actions\cmake\action.yml` Should it also be defined in the root CMakeLists.txt ?
> 
> No, it shouldn't. Library is currently used also in other projects where QML is not used, so it cannot be implicitly enabled.

We didn't quite understand each other. I meant the CMakelist.txt of the entire QE, otherwise we have to solve it somehow differently.
Because if the developer wants to build the entire QE, he has to set this variable somehow.

**Comment by arnost00** [comment]
Why submodule `siutils` uses 
```
[remote "origin"]
url = git@github.com:Quick-Event/siutils.git 
```
and not 
```
[remote "origin"] 
url = https://github.com/fvacek/necrolog.git
``` 
as the two other 3rdParty libraries ?

`necrolog` & `libshv` uses `https` and works for me. `siutils` works not.

**Comment by fvacek** [comment]
`siutils` submodule was removed, sorry. I planned to use it in https://github.com/Quick-Event/startertool , but it turned out not to be necessary finally.
