### ISSUE TITLE
Remove disqualified field from DB

### ISSUE THREAD

**Issue by fvacek** [Quick-Event/quickbox#930]
`runs.disqualified` is calculated field in the latest implementation, so there is no need to store it in SQL. It can be always reconstructed. see https://github.com/Quick-Event/quickbox/blob/1ff0bcb8553e56e5993a2c2da9b464cf338ba087/quickevent/app/quickevent/plugins/CardReader/src/cardreaderplugin.cpp#L392

@otahirs @arnost00 @paukert @xkenia what do you think about?

**Comment by otahirs** [comment]
I would suggest turning `disqualified` field in database into read-only generated column

```
disqualified BOOLEAN GENERATED ALWAYS AS 
    (
        disqualifiedByOrganizer OR 
        misPunch OR 
        notStart OR 
        notFinish OR 
        badCheck OR 
        overTime OR
        notCompeting
    ) VIRTUAL;
```

**Comment by paukert** [comment]
@ otahirs suggestion makes sense to me because disqualified column is probably used in some queries so removing this column would imply some refactoring. In addition IMO it is quite handy to have the possibility to be able to filter disqualified competitors based on this simple condition.

Support should be good even for SQLite.

**Comment by fvacek** [comment]
If Sqlite and PostgreSQL support virtual columns, then it seems to me to be a perfect solution.

**Comment by paukert** [comment]
Support to SQLite was added in version 3.31.0 which was released on 2020-01-22 (https://www.sqlite.org/releaselog/3_31_0.html).

PostgreSQL supports generated columns since version 12.

**Comment by xkenia** [comment]
I agree with leave this field in DB (you may use this as quick check if user is ok or not and in direct query), but not sure about use of virtual columns (will it works on all platforms correctly, is it integrated in most of 3rd parties?). I don't think we will have so big database that we need to save any space and need to remove columns. But yes, this should be the way

**Comment by fvacek** [comment]
I do not plan to support more sql servers in near future and if yes, I suspect that they will be mature enough to supoort this. So I think that it still worth to avoid data redundancy.

**Comment by otahirs** [comment]
The feature is called  `generated` column (not virtual), which as _paukert_ pointed out, should be supported in SQLite plugin shipped with Qt. The minimal supported version of Postgres would become v12, which is more than acceptable to me.

The generated column can then be of one of two kinds, either `VIRTUAL` (computed on use) or `STORED` (computed on INSERT or UPDATE). 

I do not see a big difference between these two. The use of `STORED` can be just a little bit more helpful for debugging when looking at the table rows. The `VIRTUAL` can be easier to change in the DB schema, as `STORED` cannot be added to existing table using `ALTER TABLE`.
