### ISSUE TITLE
Question: QE application window is launched together with terminal window

### ISSUE THREAD

**Issue by paukert** [Quick-Event/quickbox#947]
Is there any reason why the terminal window is launched together with the application window? (if the `quickevent.exe` from QE installation dir is launched, two windows are opened - "normal application" window and window with terminal). This was not the case for QE2.

![obrazek](https://github.com/Quick-Event/quickbox/assets/15065907/6c97763f-0e7c-41f3-8d10-ea1e2b61fff9)

**Comment by fvacek** [comment]
I do not have windows, but according to documentation https://github.com/Quick-Event/quickbox/commit/6183f3b30948650e4976a59928287066858b7b21 should make the thinq

**Comment by paukert** [comment]
Tested, it's working 🎉
