### ISSUE TITLE
Námět - kompletní editace dat z čipu (mezičasů)

### ISSUE THREAD

**Issue by horakmar** [Quick-Event/quickbox#948]
Narazil jsem na případ, kdy bych potřeboval upravit záznamy kontrol načtené z čipu. Závodník si nevynuloval čip z předchozí etapy a staré záznamy kolidují s novými (do mezičasů se vezme poprvé oražená kontrola se správným kódem). Pro nápravu mezičasů by se hodila možnost editovat načtené záznamy, nebo alespoň smazat ty nechtěné.

**Comment by fvacek** [comment]
ja myslim, ze kdyz pouzijes SqlTool, tak ten zaznam poeditovat v tabulce `cards` muzes
