### ISSUE TITLE
Nefunkční sestava půjčených čipů

### ISSUE THREAD

**Issue by martinkrivda** [Quick-Event/quickbox#954]
Nelze otevřít sestavu půjčených čipů. Při otevření sestavy **Závodníci s půjčeným čipem** se otevře tiskové okno, ale report se nezobrazí a počet stránek se načítá do nekonečna ...

https://github.com/Quick-Event/quickbox/assets/30177677/dfd50790-9261-492b-9829-cee730251e7d

Testováno ve verzi 2.6.26

**Simulace chyby**
1. Otevřít závod
2. Přejít do sekce **Úseky / Etapy**
3. Menu Tisk->Závodníci s půjčeným čipem
4. Stránky se v reportu načítají do nekonečna ...

**Comment by arnost00** [comment]
Opraveno v PR #955, chybí tam volání dialogu a nastavení rozměru stránky.
