### ISSUE TITLE
Požadovaný start z ORISu

### ISSUE THREAD

**Issue by bestik** [Quick-Event/quickbox#960]
ORIS zavedl strukturovaný formát požadavků na start. Formát je podobný turnovskému viz. #749 

Popis formátu je v nápovědě ORISu: https://oris.orientacnisporty.cz/files/help/Pozadovane-starty-prihlasky.pdf?v=3

**Comment by fvacek** [comment]
diky :)

**Comment by fvacek** [comment]
example: `https://oris.orientacnisporty.cz/API/?format=xml&method=getEventEntries&eventid=2077`
```
<Entry_17952>
<ID>17952</ID>
<ClassID>39533</ClassID>
<ClassDesc>H55C</ClassDesc>
<RegNo>OOP5001</RegNo>
<Name>Ševčík Břetislav</Name>
<FirstName>Břetislav</FirstName>
<LastName>Ševčík</LastName>
<RentSI>0</RentSI>
<SI>49301</SI>
<Licence>C</Licence>
<RequestedStart/>
<UserID>3418</UserID>
<ClubUserID>3598</ClubUserID>
<ClubID>104</ClubID>
<Note/>
<Fee>70</Fee>
<EntryStop>1</EntryStop>
<CreatedDateTime>2013-04-08 19:18:14</CreatedDateTime>
<CreatedByUserID>3418</CreatedByUserID>
<UpdatedDateTime>2013-04-08 19:18:18</UpdatedDateTime>
<UpdatedByUserID>3418</UpdatedByUserID>
</Entry_17952>
```
@bestik ktere pole je `požadovaný start`, nebo v prikladu jeste chybi?

**Comment by jmacura** [comment]
Že by `<RequestedStart/>` ?

Ze stejného závodu:
```
<Entry_37924>
<ID>37924</ID>
<ClassID>39520</ClassID>
<ClassDesc>D35C</ClassDesc>
<RegNo>AOV6951</RegNo>
<Name>Mielcová Elena</Name>
<FirstName>Elena</FirstName>
<LastName>Mielcová</LastName>
<RentSI>0</RentSI>
<SI>896961</SI>
<Licence>C</Licence>
<RequestedStart>1</RequestedStart>
<UserID>242</UserID>
<ClubUserID>234</ClubUserID>
<ClubID>7</ClubID>
<Note>
Prosím o start na začátku kategorie. Mohu potom pomoci s hlídáním kontrol.
</Note>
<Fee>70</Fee>
<EntryStop>1</EntryStop>
<CreatedDateTime>2013-04-27 20:40:40</CreatedDateTime>
<CreatedByUserID>241</CreatedByUserID>
<UpdatedDateTime/>
<UpdatedByUserID/>
</Entry_37924>
```

Ale na strukturovaný zápis to moc nevypadá:
`<RequestedStart>prosím na začátek</RequestedStart>`
`<RequestedStart>na začátku</RequestedStart>`
`<RequestedStart>Prosím co nejpozději. Děkuji.</RequestedStart>`
`<RequestedStart>co nejpozději</RequestedStart>`

**Comment by bestik** [comment]
Ano, pole je <RequestedStart/>
Je treba se podivat na nejake aktualni prihlasky a ne na zavod z roku 2013. Data zpetne samozrejme v nove strukture nebudou...

**Comment by fvacek** [comment]
Koukal jsem se do kodu a QE requested start jiz importuje a pridava ho do poznamky, protoze nevim, co vic by s tim ted mohl delat, nechal bych to zatim takto jako dodatecnou informaci pro losovani.
