### ISSUE TITLE
Nefunkční copy&paste v záložce Úseky/Etapy

### ISSUE THREAD

**Issue by lukaskett** [Quick-Event/quickbox#969]
Řešil jsem export/tisk startovky se zobrazenými licencemi a rankingem pro oblastní mistrovství (Pha a Stc, nevím jak jinde) pro kontrolu hlavním rozhodčím. Potřebovali jsme exportovat startovku i se sloupci `licence` a `ranking`, které jsou pro losování klíčové. Nepodařilo se mi žádný takový výstup najít. 
Zkoušel jsem klasické copy&paste ze záložky `Úseky/Etapy`, ale to mi při vložení vkládalo data jen do řádků a nevytvářelo sloupce. Zatímco pro záložku `Závodnící` funguje ok.
Tohle
![image](https://github.com/Quick-Event/quickbox/assets/29544822/d97b6165-95ea-4386-acf4-4fbcb56fea4c)
vedlo k tomuto:
![image](https://github.com/Quick-Event/quickbox/assets/29544822/9824d7b9-7d4e-4b3c-89d9-a0d278f8807d)
ze záložky `Závodníci` vypadá takto:
![image](https://github.com/Quick-Event/quickbox/assets/29544822/097ed546-479a-41e2-b2e0-1259943b08c7)

Nakonec jsme řešili xml exportem a nahráním do Orisu, kde jsme jen nepotvrdili poslední krok uložení do databáze a kontrolovali to tak v náhledu.

![image](https://github.com/Quick-Event/quickbox/assets/29544822/08d7359f-8360-4648-80e6-b03d32366297)

**Comment by fvacek** [comment]
Nemam ted zadny qbe soubor se stafetami, muzes prosim prilozit ten svuj?

**Comment by lukaskett** [comment]
Tohle se týká individuálu. Qbe štafet mám na jiném pc. Kdybys ho fakt potřeboval, tak dodám.

**Comment by fvacek** [comment]
Paste funguje jenom do sloupcu, ktere nejsou RO (modre podbarvene).  Tak jestli to nemuze byt tim.

**Comment by arnost00** [comment]
A pouzivat export pres prave tlacitko v rozku tabulky ti taky nefunguje ?
![Window_2024-10-25_10-42-34](https://github.com/user-attachments/assets/52665a1f-d2a5-44b7-92a0-6e625b770b72)

**Comment by arnost00** [comment]
Zkousel jsem to nasimulovat a rozbije to ze mas presunut sloupec SI.
Kdyz si je das do puvodniho rozlozeni a ne vedle sebe (slopuce SI) tak funguje i export vyberem casti tabulky.

**Comment by lukaskett** [comment]
Zkoušel jsem, na první pokus se zdálo, že funguje a teď už taky nedokážu funkční copy&paste navodit ačkoliv jsem ve výchozím pořadí sekcí (SI již nemám posunuté k sobě). Jednou mi to zafungovalo a následně ani restart QE nepomohl.

Plus jsem narazil na drobnosti #987 .

**Comment by fvacek** [comment]
Porad tomu nerozumim, podle nahledu se do schranky dostal CSV text, kte jsou fieldy oddeleny `TAB` a radky `CRLF`, coz je na windows snad spravne, co je ta chyba?

**Comment by lukaskett** [comment]
Data zkopírovaná z QE se po `Cltr + V` vloží jako samostatné řádky a nejde docílit překopírování jako tabulka
![image](https://github.com/user-attachments/assets/2da50c60-1e6f-43ff-a5c5-26f5237afaa1)

**Comment by fvacek** [comment]
Asi jsem natvrdlej, v QE znacis nejakou cast tabulky a das `ctrl-c`, a paste delas do ceho? Nekam jinam v QE nebo do textoveho editoru nebo do excelu?

**Comment by arnost00** [comment]
Ukazka C&P z "Useky/Etapy" (not ok) a z "Zavodnici" (ok) :
![Window_2024-11-01_11-03-37](https://github.com/user-attachments/assets/7b34e39d-52f1-406d-9d6d-456bb34ad3ce)

Doufam ze jsem to pochopil spravne, v cem je problem

**Comment by fvacek** [comment]
aha, dik :)
