### ISSUE TITLE
Štafety: Příznak u nevyběhnutých úseků

### ISSUE THREAD

**Issue by lukaskett** [Quick-Event/quickbox#971]
Při pořádání sprintovek jsem řešil nulové časy u úseků, které nevyběhly a měly nahlášeného závodníka (např. poslední úsek, či kluk na 3.úseku, kde šla holčina z hambáče). Musel jsem manuálně nastavit DNS, aby byl závodník disk a nekazilo výsledky. Jaký je tady prosím doporučený postup? Řešil jsem seřazením závodníků dle cílového času a postupným procházením a nastavováním příznaku po uzavření cíle.

**Comment by fvacek** [comment]
Asi tomu uplne nerozumim, ale kdyz nebezel 3. usek, tak je stafeta preci DISK

**Comment by lukaskett** [comment]
Takhle to právě nefunguje. Po skončení závodu je potřeba nekompletní štafety projít a ručně je disknout.

**Comment by fvacek** [comment]
qbe prosim

**Comment by lukaskett** [comment]
Tady je [240420_kam_sprintove_stafety_vysledky_1756.zip](https://github.com/user-attachments/files/17513063/240420_kam_sprintove_stafety_vysledky_1756.zip)

**Comment by arnost00** [comment]
A neni tohle castecne reseno uz v oprave XML exportu v PR #984 ?
Resp. nekompletni stafety bez zadaneho useku se pro XML export resili.

Pokud je jmeno zadane a nevybehne tak se rucnimu nastaveni DNS asi nevyhneme, ne ?

**Comment by fvacek** [comment]
Muzu to teda zavrit?

**Comment by lukaskett** [comment]
Jo můžeš

Ověřoval jsem ještě to vyhodnocování a je tam správně status `DNF` u nevyběnutých. 
![qe_stafety_dnf](https://github.com/user-attachments/assets/1414942e-fb09-4ee5-899a-98836541b260)

Pokud nastavím, že závodník neběžel, tak jeho jméno zmizí. Mohlo by se to chovat lépe, ale není to nic kritického.
![qe_stafety_dns](https://github.com/user-attachments/assets/d9683dbe-5b4a-46ac-84ef-b168c9bfca14)

**Comment by arnost00** [comment]
> Pokud nastavím, že závodník neběžel, tak jeho jméno zmizí. Mohlo by se to chovat lépe, ale není to nic kritického.
