### ISSUE TITLE
Import rankingu importuje do IOF ID, ne do Ranking umístění

### ISSUE THREAD

**Issue by OndrejSpanel** [Quick-Event/quickbox#973]
V rámcí přípravy na středeční závod jsem nechal importovat ranking z ORIS textových exportů. Data se neobjevila ve sloupci Ranking umístění, ale v IOF ID. Je to normální? Bude mi správně fungovat losování, nebo musím data přestěhovat?

![image](https://github.com/Quick-Event/quickbox/assets/6927223/fd730eea-c7d7-4a14-955e-7d2cc50cc0bc)

Verze vánoční, 2.6.26

**Comment by OndrejSpanel** [comment]
Jsem zmaten. Teď už to ve sloupci ranking vidím. Nejspíš se to jen po importu neaktualizuje a je třeba se přepnout jinam a zase zpět, nebo ukončit a spustit aplikaci, nebo něco takového. IOF ID je pak asi něco nesouvisejícího.

**Comment by lukaskett** [comment]
`IOF ID` (identifikátor pro mezinárodní/WRE závody) se natáhne z Orisu (pokud ho mají závodníci v profilu nastavený), takže je tam ihned po naimportování závodu jestli používáš `Soubor->Importovat->ORIS->Závod`.

Taky jsem s tím laboroval a nakonec jsem zjistil, že v Orisu jsou dvě tlačítka na export Rankingu a jen jeden export jde načíst pomocí `Soubor->Importovat->Testový soubor->Rankingová data v CSV (formát Orisu)`. 
![image](https://github.com/Quick-Event/quickbox/assets/29544822/5e4c7b07-0cef-4e48-925e-83cdeccb9b62)
Je potřeba použít to z `Exportovat CSV`.

**Comment by OndrejSpanel** [comment]
To jsem dělal, jen se mi to ve sloupci neobjevilo, dokud jsem neodešel jinam a nevrátil se (takové věci se stávají v QE i v jiných tabulkách).

**Comment by Osin01** [comment]
Tabulky se obecně automaticky neaktualizují, když jsou zrovna otevřené. Je třeba dát ruční aktualizaci, nebo zavřít a otevřít znovu.
