### ISSUE TITLE
Rozvržení startu kategorií: Barevné označení

### ISSUE THREAD

**Issue by Blacktrz** [Quick-Event/quickbox#974]
Možná hloupý dotaz. Má mě na něco upozornit barevné označení kategorií nebo je to jen kvůli přehlednosti. Vím, že když je kategorie v červeném rámečku, tak je tam kolize na 1 kontrole.

![rozvrzenistartu](https://github.com/Quick-Event/quickbox/assets/132453862/605457dc-610b-4185-86cd-7f0e88807f9f)

**Comment by fvacek** [comment]
je to jen kvuli prehlednosti, stejnou barvu maji kategorie se stejnou prvni kontrolou
